{
  "hash": "a1956810d3c41c0f3335bf026c7fc214",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Contexto Externo — Encontros Presenciais e Fases do Relacionamento\"\nauthor: \"Marlon\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: show\n    code-tools: true\n    df-print: paged\n    theme: cosmo\n    number-sections: true\nexecute:\n  warning: false\n  message: false\n  freeze: true\n---\n\n# Introdução\n\nEste notebook integra **dados de encontros presenciais** ao dataset de mensagens.\n\nA análise temporal anterior identificou que **contexto externo** (presença física vs distância) é uma **variável crítica** para entender padrões de comunicação em relacionamentos à distância.\n\n**Hipótese a validar:**\n- Quando **juntos**: Volume de mensagens ≈ 0 msgs/dia\n- Quando **separados**: Volume ≈ 200-500 msgs/dia\n- **Gaps no timeline** coincidem com encontros presenciais\n\n---\n\n# Setup\n\n## Bibliotecas\n\n::: {#969fb91c .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport plotly.express as px\nimport plotly.graph_objects as go\nfrom plotly.subplots import make_subplots\nfrom pathlib import Path\nfrom datetime import datetime, timedelta\nimport warnings\n\nwarnings.filterwarnings('ignore')\n\n# Configurações de visualização\npd.set_option('display.max_columns', None)\npd.set_option('display.max_rows', 100)\n```\n:::\n\n\n## Caminhos\n\n::: {#502bcc44 .cell execution_count=2}\n``` {.python .cell-code}\n# Estrutura de diretórios\nPROJECT_ROOT = Path.home() / 'Desktop' / 'whatsapp-interaction-analysis'\nDATA_DIR = PROJECT_ROOT / 'data' / 'processed' / 'export_2024-10_2025-10'\n\n# Arquivo de entrada\nINPUT_FILE = DATA_DIR / 'messages.parquet'\n\n# Arquivo de saída\nOUTPUT_FILE = DATA_DIR / 'messages_with_context.parquet'\n\nprint(f\"📁 Diretório: {DATA_DIR}\")\nprint(f\"📂 Input: {INPUT_FILE.name}\")\nprint(f\"✅ Existe: {INPUT_FILE.exists()}\")\nprint(f\"📤 Output: {OUTPUT_FILE.name}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📁 Diretório: /Users/mosx/Desktop/whatsapp-interaction-analysis/data/processed/export_2024-10_2025-10\n📂 Input: messages.parquet\n✅ Existe: True\n📤 Output: messages_with_context.parquet\n```\n:::\n:::\n\n\n## Carregamento\n\n::: {#564cf726 .cell execution_count=3}\n``` {.python .cell-code}\n# Carrega dataset\ndf = pd.read_parquet(INPUT_FILE)\n\nprint(f\"📊 Shape: {df.shape}\")\nprint(f\"📅 Período: {df['timestamp'].min().date()} → {df['timestamp'].max().date()}\")\nprint(f\"👥 Remetentes: {df['remetente'].unique().tolist()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📊 Shape: (91924, 8)\n📅 Período: 2024-10-19 → 2025-10-20\n👥 Remetentes: ['P1', 'P2']\n```\n:::\n:::\n\n\n---\n\n# Definição dos Encontros\n\n## Datas dos Encontros Presenciais\n\nRelacionamento à distância **SP ↔ BSB** com encontros regulares ao longo de 1 ano.\n\n::: {#cdb64827 .cell execution_count=4}\n``` {.python .cell-code}\n# Define cores para visualizações\nCOLORS = {\n    'P1': '#3498db',\n    'P2': '#e74c3c',\n    'neutral': '#95a5a6',\n    'juntos': '#2ecc71'\n}\n\n# ============================================================================\n# DATAS PRECISAS DAS VIAGENS\n# ============================================================================\n\nencontros = [\n    {\n        'nome': 'Chapada/BSB (1ª viagem)',\n        'inicio': '2024-12-12',\n        'fim': '2024-12-24',\n        'tipo': 'Marlon @ BSB',\n        'local': 'Brasília',\n        'marco_especial': '2024-12-16',  # 1ª vez juntos\n        'marco_nome': '💕 1ª Vez Juntos'\n    },\n    {\n        'nome': 'BSB (Janeiro)',\n        'inicio': '2025-01-23',\n        'fim': '2025-01-29',\n        'tipo': 'Marlon @ BSB',\n        'local': 'Brasília',\n        'marco_especial': None,\n        'marco_nome': None\n    },\n    {\n        'nome': 'Letícia SP (Hostel)',\n        'inicio': '2025-02-06',\n        'fim': '2025-02-10',\n        'tipo': 'Letícia @ SP',\n        'local': 'São Paulo',\n        'marco_especial': None,\n        'marco_nome': None\n    },\n    {\n        'nome': 'BSB (Carnaval)',\n        'inicio': '2025-02-27',\n        'fim': '2025-03-10',\n        'tipo': 'Marlon @ BSB',\n        'local': 'Brasília',\n        'marco_especial': '2025-03-05',\n        'marco_nome': '🦷 Arrancou dente'\n    },\n    {\n        'nome': 'BSB (Abril-Maio)',\n        'inicio': '2025-04-16',\n        'fim': '2025-05-05',\n        'tipo': 'Marlon @ BSB',\n        'local': 'Brasília',\n        'marco_especial': None,\n        'marco_nome': None\n    },\n    {\n        'nome': 'Letícia Sorocaba',\n        'inicio': '2025-05-17',\n        'fim': '2025-05-24',\n        'tipo': 'Letícia @ Sorocaba',\n        'local': 'Sorocaba',\n        'marco_especial': None,\n        'marco_nome': None\n    },\n    {\n        'nome': 'Letícia SP (Trampo)',\n        'inicio': '2025-07-21',\n        'fim': '2025-07-26',\n        'tipo': 'Letícia @ SP',\n        'local': 'São Paulo',\n        'marco_especial': None,\n        'marco_nome': None\n    },\n    {\n        'nome': 'BSB (2 meses!)',\n        'inicio': '2025-08-22',\n        'fim': '2025-10-11',\n        'tipo': 'Marlon @ BSB',\n        'local': 'Brasília',\n        'marco_especial': '2025-08-22',\n        'marco_nome': '🏠 2 meses juntos'\n    },\n    {\n        'nome': 'BSB (Niver Letícia)',\n        'inicio': '2025-11-05',\n        'fim': '2025-11-19',\n        'tipo': 'Marlon @ BSB',\n        'local': 'Brasília',\n        'marco_especial': '2025-11-04',\n        'marco_nome': '🎂 Aniversário Letícia'\n    },\n    {\n        'nome': 'BSB (Fim de ano!)',\n        'inicio': '2025-12-12',\n        'fim': '2026-01-04',\n        'tipo': 'Marlon @ BSB',\n        'local': 'Brasília',\n        'marco_especial': None,\n        'marco_nome': None\n    }\n]\n\n# Converte para DataFrame\nencontros_df = pd.DataFrame(encontros)\nencontros_df['inicio'] = pd.to_datetime(encontros_df['inicio'])\nencontros_df['fim'] = pd.to_datetime(encontros_df['fim'])\nencontros_df['duracao_dias'] = (encontros_df['fim'] - encontros_df['inicio']).dt.days + 1\nencontros_df['encontro_id'] = range(1, len(encontros_df) + 1)\n\n# Converte marcos especiais\nencontros_df['marco_especial'] = pd.to_datetime(encontros_df['marco_especial'], errors='coerce')\n\nprint(\"=\"*80)\nprint(\"📅 ENCONTROS REGISTRADOS\")\nprint(\"=\"*80)\nprint(f\"\\nTotal de encontros: {len(encontros_df)}\\n\")\nprint(encontros_df[['encontro_id', 'nome', 'inicio', 'fim', 'duracao_dias', 'tipo']].to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n================================================================================\n📅 ENCONTROS REGISTRADOS\n================================================================================\n\nTotal de encontros: 10\n\n encontro_id                    nome     inicio        fim  duracao_dias               tipo\n           1 Chapada/BSB (1ª viagem) 2024-12-12 2024-12-24            13       Marlon @ BSB\n           2           BSB (Janeiro) 2025-01-23 2025-01-29             7       Marlon @ BSB\n           3     Letícia SP (Hostel) 2025-02-06 2025-02-10             5       Letícia @ SP\n           4          BSB (Carnaval) 2025-02-27 2025-03-10            12       Marlon @ BSB\n           5        BSB (Abril-Maio) 2025-04-16 2025-05-05            20       Marlon @ BSB\n           6        Letícia Sorocaba 2025-05-17 2025-05-24             8 Letícia @ Sorocaba\n           7     Letícia SP (Trampo) 2025-07-21 2025-07-26             6       Letícia @ SP\n           8          BSB (2 meses!) 2025-08-22 2025-10-11            51       Marlon @ BSB\n           9     BSB (Niver Letícia) 2025-11-05 2025-11-19            15       Marlon @ BSB\n          10       BSB (Fim de ano!) 2025-12-12 2026-01-04            24       Marlon @ BSB\n```\n:::\n:::\n\n\n## Estatísticas Gerais\n\n::: {#f88b339f .cell execution_count=5}\n``` {.python .cell-code}\n# Período do dataset\nperiodo_inicio = df['timestamp'].min().date()\nperiodo_fim = df['timestamp'].max().date()\ntotal_dias_dataset = (periodo_fim - periodo_inicio).days + 1\n\n# Encontros dentro do período do dataset\nencontros_no_dataset = encontros_df[\n    (encontros_df['inicio'].dt.date >= periodo_inicio) &\n    (encontros_df['inicio'].dt.date <= periodo_fim)\n]\n\n# Calcula dias juntos no período do dataset\ndias_juntos_no_dataset = 0\nfor _, encontro in encontros_no_dataset.iterrows():\n    inicio_efetivo = max(encontro['inicio'].date(), periodo_inicio)\n    fim_efetivo = min(encontro['fim'].date(), periodo_fim)\n    if inicio_efetivo <= fim_efetivo:\n        dias_juntos_no_dataset += (fim_efetivo - inicio_efetivo).days + 1\n\npct_juntos = (dias_juntos_no_dataset / total_dias_dataset) * 100\n\nprint(f\"\\n📊 Resumo Temporal:\")\nprint(f\"   • Período do dataset: {periodo_inicio} a {periodo_fim} ({total_dias_dataset} dias)\")\nprint(f\"   • Encontros no período: {len(encontros_no_dataset)} de {len(encontros_df)}\")\nprint(f\"   • Dias juntos: {dias_juntos_no_dataset} dias ({pct_juntos:.1f}% do período)\")\nprint(f\"   • Dias separados: {total_dias_dataset - dias_juntos_no_dataset} dias ({100-pct_juntos:.1f}%)\")\n\nprint(f\"\\n📊 Detalhes dos Encontros:\")\nprint(f\"   • Viagem mais longa: {encontros_df['duracao_dias'].max()} dias ({encontros_df.loc[encontros_df['duracao_dias'].idxmax(), 'nome']})\")\nprint(f\"   • Viagem mais curta: {encontros_df['duracao_dias'].min()} dias ({encontros_df.loc[encontros_df['duracao_dias'].idxmin(), 'nome']})\")\nprint(f\"   • Duração média: {encontros_df['duracao_dias'].mean():.1f} dias\")\n\nprint(f\"\\n📍 Distribuição por Local:\")\nprint(encontros_df['local'].value_counts().to_string())\n\nprint(f\"\\n✈️ Distribuição por Tipo:\")\nprint(encontros_df['tipo'].value_counts().to_string())\n\nprint(\"\\n\" + \"=\"*80)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n📊 Resumo Temporal:\n   • Período do dataset: 2024-10-19 a 2025-10-20 (367 dias)\n   • Encontros no período: 8 de 10\n   • Dias juntos: 122 dias (33.2% do período)\n   • Dias separados: 245 dias (66.8%)\n\n📊 Detalhes dos Encontros:\n   • Viagem mais longa: 51 dias (BSB (2 meses!))\n   • Viagem mais curta: 5 dias (Letícia SP (Hostel))\n   • Duração média: 16.1 dias\n\n📍 Distribuição por Local:\nlocal\nBrasília     7\nSão Paulo    2\nSorocaba     1\n\n✈️ Distribuição por Tipo:\ntipo\nMarlon @ BSB          7\nLetícia @ SP          2\nLetícia @ Sorocaba    1\n\n================================================================================\n```\n:::\n:::\n\n\n::: {.callout-warning}\n\n## 💡 Insight - Encontros Presenciais\n\n**Intensidade do relacionamento:**\n- **33.2% do tempo juntos** (122 de 367 dias) - proporção alta para relacionamento à distância\n- 8 encontros no período de 1 ano (média de 1 encontro/mês)\n- Duração média: **16 dias** por encontro (muito acima do típico)\n\n**Padrão de deslocamento:**\n- **Assimétrico:** Marlon viaja mais (7 de 10 encontros = 70%)\n- Brasília é destino principal (7 encontros)\n- Encontro mais longo: **51 dias** (BSB 2 meses - Ago-Out/2025)\n\n**Implicação crítica:**\n- Com 1/3 do tempo juntos, **presença física é moderador primário** da comunicação\n- Volume de mensagens deve cair drasticamente durante encontros\n- Padrões temporais (hora, dia) podem mudar completamente quando juntos\n- Gaps no timeline provavelmente coincidem com esses 122 dias\n\n**Validação necessária:** Confirmar se volume realmente cai e se gaps coincidem com encontros.\n:::\n\n---\n\n# Integração ao Dataset\n\n## Criação de Features Básicas\n\n::: {#bfa21f1c .cell execution_count=6}\n``` {.python .cell-code}\n# Cria coluna de data para merge\ndf['data_msg'] = df['timestamp'].dt.date\n\n# Inicializa colunas\ndf['em_encontro'] = False\ndf['encontro_id'] = None\ndf['encontro_nome'] = None\ndf['local_encontro'] = None\ndf['tipo_encontro'] = None\ndf['dia_do_encontro'] = None\ndf['eh_marco_especial'] = False\ndf['marco_nome'] = None\n\nprint(\"✅ Colunas inicializadas\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✅ Colunas inicializadas\n```\n:::\n:::\n\n\n## Integração - Encontros\n\n::: {#873a71da .cell execution_count=7}\n``` {.python .cell-code}\n# Para cada encontro, marca mensagens enviadas durante ele\nfor _, encontro in encontros_df.iterrows():\n    # Mascara de mensagens neste encontro\n    mask = (df['data_msg'] >= encontro['inicio'].date()) & (df['data_msg'] <= encontro['fim'].date())\n\n    # Atribui features básicas\n    df.loc[mask, 'em_encontro'] = True\n    df.loc[mask, 'encontro_id'] = encontro['encontro_id']\n    df.loc[mask, 'encontro_nome'] = encontro['nome']\n    df.loc[mask, 'local_encontro'] = encontro['local']\n    df.loc[mask, 'tipo_encontro'] = encontro['tipo']\n\n    # Calcula dia do encontro (1, 2, 3...)\n    df.loc[mask, 'dia_do_encontro'] = (\n        pd.to_datetime(df.loc[mask, 'data_msg']) - encontro['inicio']\n    ).dt.days + 1\n\nprint(f\"✅ Features de encontro atribuídas\")\nprint(f\"   • Mensagens durante encontros: {df['em_encontro'].sum():,}\")\nprint(f\"   • Mensagens fora de encontros: {(~df['em_encontro']).sum():,}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✅ Features de encontro atribuídas\n   • Mensagens durante encontros: 13,432\n   • Mensagens fora de encontros: 78,492\n```\n:::\n:::\n\n\n## Integração - Marcos Especiais\n\n::: {#46bac1cf .cell execution_count=8}\n``` {.python .cell-code}\n# Para cada marco especial, marca as mensagens daquele dia\nfor _, encontro in encontros_df.iterrows():\n    if pd.notna(encontro['marco_especial']):\n        mask = df['data_msg'] == encontro['marco_especial'].date()\n        df.loc[mask, 'eh_marco_especial'] = True\n        df.loc[mask, 'marco_nome'] = encontro['marco_nome']\n\nprint(f\"✅ Marcos especiais atribuídos\")\nprint(f\"   • Mensagens em marcos especiais: {df['eh_marco_especial'].sum():,}\")\nif df['eh_marco_especial'].sum() > 0:\n    print(f\"   • Marcos identificados:\")\n    for marco in df[df['eh_marco_especial']]['marco_nome'].unique():\n        count = df[df['marco_nome'] == marco].shape[0]\n        print(f\"      - {marco}: {count} mensagens\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✅ Marcos especiais atribuídos\n   • Mensagens em marcos especiais: 393\n   • Marcos identificados:\n      - 💕 1ª Vez Juntos: 11 mensagens\n      - 🦷 Arrancou dente: 279 mensagens\n      - 🏠 2 meses juntos: 103 mensagens\n```\n:::\n:::\n\n\n## Distância Temporal - Último Encontro\n\n::: {#e128a4e6 .cell execution_count=9}\n``` {.python .cell-code}\n# Calcula dias desde término do último encontro\ndf['dias_desde_ultimo_encontro'] = None\n\n# Ordena encontros por data\nencontros_ord = encontros_df.sort_values('inicio')\n\nfor idx, encontro in encontros_ord.iterrows():\n    # Período APÓS este encontro até o próximo (ou fim do dataset)\n    fim_encontro = encontro['fim'].date()\n\n    # Encontra próximo encontro\n    proximos = encontros_ord[encontros_ord['inicio'] > encontro['fim']]\n    if len(proximos) > 0:\n        inicio_proximo = proximos.iloc[0]['inicio'].date()\n    else:\n        inicio_proximo = df['data_msg'].max()\n\n    # Mensagens no período de separação\n    mask = (df['data_msg'] > fim_encontro) & (df['data_msg'] < inicio_proximo)\n    df.loc[mask, 'dias_desde_ultimo_encontro'] = (\n        pd.to_datetime(df.loc[mask, 'data_msg']) - pd.to_datetime(fim_encontro)\n    ).dt.days\n\n# Mensagens ANTES do primeiro encontro\nprimeiro_encontro = encontros_ord.iloc[0]['inicio'].date()\nmask = df['data_msg'] < primeiro_encontro\ndf.loc[mask, 'dias_desde_ultimo_encontro'] = None\n\nprint(f\"✅ 'dias_desde_ultimo_encontro' calculado\")\nprint(f\"   • Mensagens com valor: {df['dias_desde_ultimo_encontro'].notna().sum():,}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✅ 'dias_desde_ultimo_encontro' calculado\n   • Mensagens com valor: 76,042\n```\n:::\n:::\n\n\n## Distância Temporal - Próximo Encontro\n\n::: {#a928af58 .cell execution_count=10}\n``` {.python .cell-code}\n# Calcula dias até início do próximo encontro\ndf['dias_ate_proximo_encontro'] = None\n\nfor idx, encontro in encontros_ord.iterrows():\n    # Encontra período ANTES deste encontro (desde o anterior)\n    inicio_encontro = encontro['inicio'].date()\n\n    # Encontra encontro anterior\n    anteriores = encontros_ord[encontros_ord['fim'] < encontro['inicio']]\n    if len(anteriores) > 0:\n        fim_anterior = anteriores.iloc[-1]['fim'].date()\n    else:\n        fim_anterior = df['data_msg'].min()\n\n    # Mensagens no período de separação antes deste encontro\n    mask = (df['data_msg'] > fim_anterior) & (df['data_msg'] < inicio_encontro)\n    df.loc[mask, 'dias_ate_proximo_encontro'] = (\n        pd.to_datetime(inicio_encontro) - pd.to_datetime(df.loc[mask, 'data_msg'])\n    ).dt.days\n\n# Mensagens APÓS o último encontro\nultimo_encontro = encontros_ord.iloc[-1]['fim'].date()\nmask = df['data_msg'] > ultimo_encontro\ndf.loc[mask, 'dias_ate_proximo_encontro'] = None\n\nprint(f\"✅ 'dias_ate_proximo_encontro' calculado\")\nprint(f\"   • Mensagens com valor: {df['dias_ate_proximo_encontro'].notna().sum():,}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✅ 'dias_ate_proximo_encontro' calculado\n   • Mensagens com valor: 78,464\n```\n:::\n:::\n\n\n## Validação da Integração\n\n::: {#24ea05d9 .cell execution_count=11}\n``` {.python .cell-code}\n# Verifica integridade\nprint(\"\\n📊 Validação da Integração:\\n\")\n\n# 1. Mensagens durante encontros\nmsgs_durante = df[df['em_encontro']].shape[0]\nprint(f\"1. Mensagens durante encontros: {msgs_durante:,}\")\n\n# 2. Distribuição por encontro\nif msgs_durante > 0:\n    print(f\"\\n2. Distribuição por encontro:\")\n    dist_encontros = df[df['em_encontro']]['encontro_nome'].value_counts().sort_index()\n    for nome, count in dist_encontros.items():\n        print(f\"   • {nome}: {count:,} mensagens\")\n\n# 3. Mensagens em marcos especiais\nmsgs_marcos = df[df['eh_marco_especial']].shape[0]\nprint(f\"\\n3. Mensagens em marcos especiais: {msgs_marcos:,}\")\n\n# 4. Cobertura temporal\nprint(f\"\\n4. Cobertura de features temporais:\")\nprint(f\"   • dias_desde_ultimo_encontro: {df['dias_desde_ultimo_encontro'].notna().sum():,} msgs\")\nprint(f\"   • dias_ate_proximo_encontro: {df['dias_ate_proximo_encontro'].notna().sum():,} msgs\")\n\n# 5. Overlap\nprint(f\"\\n5. Verificação de overlap:\")\ndurante_e_com_dias = df[df['em_encontro'] & df['dias_desde_ultimo_encontro'].notna()].shape[0]\nprint(f\"   • Mensagens durante encontro E com dias_desde: {durante_e_com_dias} (deve ser 0)\")\n\nprint(\"\\n✅ Integração validada!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n📊 Validação da Integração:\n\n1. Mensagens durante encontros: 13,432\n\n2. Distribuição por encontro:\n   • BSB (2 meses!): 5,208 mensagens\n   • BSB (Abril-Maio): 1,618 mensagens\n   • BSB (Carnaval): 1,198 mensagens\n   • BSB (Janeiro): 1,108 mensagens\n   • Chapada/BSB (1ª viagem): 1,388 mensagens\n   • Letícia SP (Hostel): 669 mensagens\n   • Letícia SP (Trampo): 1,838 mensagens\n   • Letícia Sorocaba: 405 mensagens\n\n3. Mensagens em marcos especiais: 393\n\n4. Cobertura de features temporais:\n   • dias_desde_ultimo_encontro: 76,042 msgs\n   • dias_ate_proximo_encontro: 78,464 msgs\n\n5. Verificação de overlap:\n   • Mensagens durante encontro E com dias_desde: 0 (deve ser 0)\n\n✅ Integração validada!\n```\n:::\n:::\n\n\n::: {.callout-warning}\n## 💡 Insight - Integração de Contexto\n\n**Mensagens durante vs fora de encontros:**\n- **Durante encontros:** 13,432 mensagens (14.6% do total)\n- **Fora de encontros:** 78,492 mensagens (85.4% do total)\n\n**Paradoxo temporal identificado:**\n- Estão juntos **33.2% do tempo** (122 dias)\n- Mas enviam apenas **14.6% das mensagens** quando juntos\n- **Indicação forte:** Volume de comunicação CAI drasticamente quando estão presencialmente juntos\n\n**Distribuição por encontro:**\n- Encontro com MAIS mensagens: **BSB (2 meses!)** com 5,208 msgs (51 dias = 102 msgs/dia)\n- Encontro com MENOS mensagens: **Letícia Sorocaba** com 405 msgs (8 dias = 51 msgs/dia)\n- Variação: **2x** entre encontro mais/menos comunicativo\n\n**Marcos especiais:**\n- Apenas **393 mensagens** em datas marcantes (0.4% do total)\n- **\"Arrancou dente\"** tem mais msgs (279) - possivelmente contexto de cuidado/preocupação\n- **\"1ª Vez Juntos\"** tem apenas 11 msgs - momento presencial, pouca comunicação digital\n\n**Qualidade da integração:**\n- ✅ Cobertura temporal completa (76k-78k msgs com features de distância)\n- ✅ Zero overlap (mensagens durante encontro NÃO têm \"dias_desde\" - correto!)\n- ✅ Features prontas para análise comparativa\n\n**Próxima validação:** Confirmar quantitativamente a queda de volume e padrões temporais.\n:::\n\n---\n\n# Validação da Hipótese\n\n## Timeline com Encontros\n\n::: {#cell-fig-timeline-encontros .cell execution_count=12}\n``` {.python .cell-code}\n# Agrega mensagens por dia\nmsgs_por_dia = df.groupby('data_msg').size().reset_index(name='count')\nmsgs_por_dia['data_msg'] = pd.to_datetime(msgs_por_dia['data_msg'])\n\n# Cria gráfico\nfig = go.Figure()\n\n# Linha de volume\nfig.add_trace(go.Scatter(\n    x=msgs_por_dia['data_msg'],\n    y=msgs_por_dia['count'],\n    mode='lines',\n    name='Volume de Mensagens',\n    line=dict(color=COLORS['neutral'], width=1),\n    hovertemplate='%{x|%d/%m/%Y}<br>%{y} mensagens<extra></extra>'\n))\n\n# Adiciona retângulos para cada encontro\nfor _, encontro in encontros_df.iterrows():\n    # Só plota se estiver no período do dataset\n    if encontro['inicio'].date() <= periodo_fim and encontro['fim'].date() >= periodo_inicio:\n        fig.add_vrect(\n            x0=encontro['inicio'],\n            x1=encontro['fim'],\n            fillcolor=COLORS['juntos'],\n            opacity=0.2,\n            layer='below',\n            line_width=0,\n            annotation_text=encontro['nome'],\n            annotation_position='top left',\n            annotation=dict(font_size=9, textangle=-90)\n        )\n\nfig.update_layout(\n    title='Timeline de Mensagens com Períodos de Encontros',\n    xaxis_title='Data',\n    yaxis_title='Quantidade de Mensagens',\n    height=800,\n    hovermode='x unified',\n    showlegend=True\n)\n\nfig.show()\n```\n\n::: {#fig-timeline-encontros .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"ef7c0b9a-c64a-4c96-860c-db6d7c78c920\" class=\"plotly-graph-div\" style=\"height:800px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"ef7c0b9a-c64a-4c96-860c-db6d7c78c920\")) {                    Plotly.newPlot(                        \"ef7c0b9a-c64a-4c96-860c-db6d7c78c920\",                        [{\"hovertemplate\":\"%{x|%d\\u002f%m\\u002f%Y}\\u003cbr\\u003e%{y} mensagens\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"line\":{\"color\":\"#95a5a6\",\"width\":1},\"mode\":\"lines\",\"name\":\"Volume de Mensagens\",\"x\":[\"2024-10-19T00:00:00\",\"2024-10-23T00:00:00\",\"2024-10-24T00:00:00\",\"2024-11-21T00:00:00\",\"2024-11-22T00:00:00\",\"2024-11-23T00:00:00\",\"2024-11-26T00:00:00\",\"2024-11-27T00:00:00\",\"2024-11-28T00:00:00\",\"2024-11-29T00:00:00\",\"2024-11-30T00:00:00\",\"2024-12-02T00:00:00\",\"2024-12-03T00:00:00\",\"2024-12-04T00:00:00\",\"2024-12-05T00:00:00\",\"2024-12-06T00:00:00\",\"2024-12-08T00:00:00\",\"2024-12-09T00:00:00\",\"2024-12-10T00:00:00\",\"2024-12-11T00:00:00\",\"2024-12-12T00:00:00\",\"2024-12-13T00:00:00\",\"2024-12-14T00:00:00\",\"2024-12-15T00:00:00\",\"2024-12-16T00:00:00\",\"2024-12-17T00:00:00\",\"2024-12-18T00:00:00\",\"2024-12-19T00:00:00\",\"2024-12-20T00:00:00\",\"2024-12-21T00:00:00\",\"2024-12-22T00:00:00\",\"2024-12-23T00:00:00\",\"2024-12-24T00:00:00\",\"2024-12-25T00:00:00\",\"2024-12-26T00:00:00\",\"2024-12-27T00:00:00\",\"2024-12-28T00:00:00\",\"2024-12-29T00:00:00\",\"2024-12-30T00:00:00\",\"2024-12-31T00:00:00\",\"2025-01-01T00:00:00\",\"2025-01-02T00:00:00\",\"2025-01-03T00:00:00\",\"2025-01-04T00:00:00\",\"2025-01-05T00:00:00\",\"2025-01-06T00:00:00\",\"2025-01-07T00:00:00\",\"2025-01-08T00:00:00\",\"2025-01-09T00:00:00\",\"2025-01-10T00:00:00\",\"2025-01-11T00:00:00\",\"2025-01-12T00:00:00\",\"2025-01-13T00:00:00\",\"2025-01-14T00:00:00\",\"2025-01-15T00:00:00\",\"2025-01-16T00:00:00\",\"2025-01-17T00:00:00\",\"2025-01-18T00:00:00\",\"2025-01-19T00:00:00\",\"2025-01-20T00:00:00\",\"2025-01-21T00:00:00\",\"2025-01-22T00:00:00\",\"2025-01-23T00:00:00\",\"2025-01-24T00:00:00\",\"2025-01-25T00:00:00\",\"2025-01-26T00:00:00\",\"2025-01-27T00:00:00\",\"2025-01-28T00:00:00\",\"2025-01-29T00:00:00\",\"2025-01-30T00:00:00\",\"2025-01-31T00:00:00\",\"2025-02-01T00:00:00\",\"2025-02-02T00:00:00\",\"2025-02-03T00:00:00\",\"2025-02-04T00:00:00\",\"2025-02-05T00:00:00\",\"2025-02-06T00:00:00\",\"2025-02-07T00:00:00\",\"2025-02-08T00:00:00\",\"2025-02-09T00:00:00\",\"2025-02-10T00:00:00\",\"2025-02-11T00:00:00\",\"2025-02-12T00:00:00\",\"2025-02-13T00:00:00\",\"2025-02-14T00:00:00\",\"2025-02-15T00:00:00\",\"2025-02-16T00:00:00\",\"2025-02-17T00:00:00\",\"2025-02-18T00:00:00\",\"2025-02-19T00:00:00\",\"2025-02-20T00:00:00\",\"2025-02-21T00:00:00\",\"2025-02-22T00:00:00\",\"2025-02-23T00:00:00\",\"2025-02-24T00:00:00\",\"2025-02-25T00:00:00\",\"2025-02-26T00:00:00\",\"2025-02-27T00:00:00\",\"2025-02-28T00:00:00\",\"2025-03-01T00:00:00\",\"2025-03-02T00:00:00\",\"2025-03-03T00:00:00\",\"2025-03-04T00:00:00\",\"2025-03-05T00:00:00\",\"2025-03-06T00:00:00\",\"2025-03-07T00:00:00\",\"2025-03-08T00:00:00\",\"2025-03-09T00:00:00\",\"2025-03-10T00:00:00\",\"2025-03-11T00:00:00\",\"2025-03-12T00:00:00\",\"2025-03-13T00:00:00\",\"2025-03-14T00:00:00\",\"2025-03-15T00:00:00\",\"2025-03-16T00:00:00\",\"2025-03-17T00:00:00\",\"2025-03-18T00:00:00\",\"2025-03-19T00:00:00\",\"2025-03-20T00:00:00\",\"2025-03-21T00:00:00\",\"2025-03-22T00:00:00\",\"2025-03-23T00:00:00\",\"2025-03-24T00:00:00\",\"2025-03-25T00:00:00\",\"2025-03-26T00:00:00\",\"2025-03-27T00:00:00\",\"2025-03-28T00:00:00\",\"2025-03-29T00:00:00\",\"2025-03-30T00:00:00\",\"2025-03-31T00:00:00\",\"2025-04-01T00:00:00\",\"2025-04-02T00:00:00\",\"2025-04-03T00:00:00\",\"2025-04-04T00:00:00\",\"2025-04-05T00:00:00\",\"2025-04-06T00:00:00\",\"2025-04-07T00:00:00\",\"2025-04-08T00:00:00\",\"2025-04-09T00:00:00\",\"2025-04-10T00:00:00\",\"2025-04-11T00:00:00\",\"2025-04-12T00:00:00\",\"2025-04-13T00:00:00\",\"2025-04-14T00:00:00\",\"2025-04-15T00:00:00\",\"2025-04-16T00:00:00\",\"2025-04-17T00:00:00\",\"2025-04-19T00:00:00\",\"2025-04-20T00:00:00\",\"2025-04-21T00:00:00\",\"2025-04-22T00:00:00\",\"2025-04-23T00:00:00\",\"2025-04-24T00:00:00\",\"2025-04-25T00:00:00\",\"2025-04-27T00:00:00\",\"2025-04-28T00:00:00\",\"2025-04-29T00:00:00\",\"2025-04-30T00:00:00\",\"2025-05-01T00:00:00\",\"2025-05-02T00:00:00\",\"2025-05-03T00:00:00\",\"2025-05-04T00:00:00\",\"2025-05-05T00:00:00\",\"2025-05-06T00:00:00\",\"2025-05-07T00:00:00\",\"2025-05-08T00:00:00\",\"2025-05-09T00:00:00\",\"2025-05-10T00:00:00\",\"2025-05-11T00:00:00\",\"2025-05-12T00:00:00\",\"2025-05-13T00:00:00\",\"2025-05-14T00:00:00\",\"2025-05-15T00:00:00\",\"2025-05-16T00:00:00\",\"2025-05-17T00:00:00\",\"2025-05-18T00:00:00\",\"2025-05-19T00:00:00\",\"2025-05-21T00:00:00\",\"2025-05-22T00:00:00\",\"2025-05-23T00:00:00\",\"2025-05-24T00:00:00\",\"2025-05-25T00:00:00\",\"2025-05-26T00:00:00\",\"2025-05-27T00:00:00\",\"2025-05-28T00:00:00\",\"2025-05-29T00:00:00\",\"2025-05-30T00:00:00\",\"2025-05-31T00:00:00\",\"2025-06-01T00:00:00\",\"2025-06-02T00:00:00\",\"2025-06-03T00:00:00\",\"2025-06-04T00:00:00\",\"2025-06-05T00:00:00\",\"2025-06-06T00:00:00\",\"2025-06-07T00:00:00\",\"2025-06-08T00:00:00\",\"2025-06-09T00:00:00\",\"2025-06-10T00:00:00\",\"2025-06-11T00:00:00\",\"2025-06-12T00:00:00\",\"2025-06-13T00:00:00\",\"2025-06-14T00:00:00\",\"2025-06-15T00:00:00\",\"2025-06-16T00:00:00\",\"2025-06-17T00:00:00\",\"2025-06-18T00:00:00\",\"2025-06-19T00:00:00\",\"2025-06-20T00:00:00\",\"2025-06-21T00:00:00\",\"2025-06-22T00:00:00\",\"2025-06-23T00:00:00\",\"2025-06-24T00:00:00\",\"2025-06-25T00:00:00\",\"2025-06-26T00:00:00\",\"2025-06-27T00:00:00\",\"2025-06-28T00:00:00\",\"2025-06-29T00:00:00\",\"2025-06-30T00:00:00\",\"2025-07-01T00:00:00\",\"2025-07-02T00:00:00\",\"2025-07-03T00:00:00\",\"2025-07-04T00:00:00\",\"2025-07-05T00:00:00\",\"2025-07-06T00:00:00\",\"2025-07-07T00:00:00\",\"2025-07-08T00:00:00\",\"2025-07-09T00:00:00\",\"2025-07-10T00:00:00\",\"2025-07-11T00:00:00\",\"2025-07-12T00:00:00\",\"2025-07-13T00:00:00\",\"2025-07-14T00:00:00\",\"2025-07-15T00:00:00\",\"2025-07-16T00:00:00\",\"2025-07-17T00:00:00\",\"2025-07-18T00:00:00\",\"2025-07-19T00:00:00\",\"2025-07-20T00:00:00\",\"2025-07-21T00:00:00\",\"2025-07-22T00:00:00\",\"2025-07-23T00:00:00\",\"2025-07-24T00:00:00\",\"2025-07-25T00:00:00\",\"2025-07-26T00:00:00\",\"2025-07-27T00:00:00\",\"2025-07-28T00:00:00\",\"2025-07-29T00:00:00\",\"2025-07-30T00:00:00\",\"2025-07-31T00:00:00\",\"2025-08-01T00:00:00\",\"2025-08-02T00:00:00\",\"2025-08-03T00:00:00\",\"2025-08-04T00:00:00\",\"2025-08-05T00:00:00\",\"2025-08-06T00:00:00\",\"2025-08-07T00:00:00\",\"2025-08-08T00:00:00\",\"2025-08-09T00:00:00\",\"2025-08-10T00:00:00\",\"2025-08-11T00:00:00\",\"2025-08-12T00:00:00\",\"2025-08-13T00:00:00\",\"2025-08-14T00:00:00\",\"2025-08-15T00:00:00\",\"2025-08-16T00:00:00\",\"2025-08-17T00:00:00\",\"2025-08-18T00:00:00\",\"2025-08-19T00:00:00\",\"2025-08-20T00:00:00\",\"2025-08-21T00:00:00\",\"2025-08-22T00:00:00\",\"2025-08-23T00:00:00\",\"2025-08-24T00:00:00\",\"2025-08-25T00:00:00\",\"2025-08-26T00:00:00\",\"2025-08-27T00:00:00\",\"2025-08-28T00:00:00\",\"2025-08-29T00:00:00\",\"2025-08-31T00:00:00\",\"2025-09-01T00:00:00\",\"2025-09-02T00:00:00\",\"2025-09-03T00:00:00\",\"2025-09-04T00:00:00\",\"2025-09-05T00:00:00\",\"2025-09-06T00:00:00\",\"2025-09-07T00:00:00\",\"2025-09-08T00:00:00\",\"2025-09-09T00:00:00\",\"2025-09-10T00:00:00\",\"2025-09-11T00:00:00\",\"2025-09-12T00:00:00\",\"2025-09-13T00:00:00\",\"2025-09-14T00:00:00\",\"2025-09-15T00:00:00\",\"2025-09-16T00:00:00\",\"2025-09-17T00:00:00\",\"2025-09-18T00:00:00\",\"2025-09-19T00:00:00\",\"2025-09-22T00:00:00\",\"2025-09-23T00:00:00\",\"2025-09-24T00:00:00\",\"2025-09-25T00:00:00\",\"2025-09-26T00:00:00\",\"2025-09-27T00:00:00\",\"2025-09-29T00:00:00\",\"2025-09-30T00:00:00\",\"2025-10-01T00:00:00\",\"2025-10-02T00:00:00\",\"2025-10-03T00:00:00\",\"2025-10-04T00:00:00\",\"2025-10-05T00:00:00\",\"2025-10-06T00:00:00\",\"2025-10-07T00:00:00\",\"2025-10-08T00:00:00\",\"2025-10-09T00:00:00\",\"2025-10-10T00:00:00\",\"2025-10-12T00:00:00\",\"2025-10-13T00:00:00\",\"2025-10-14T00:00:00\",\"2025-10-15T00:00:00\",\"2025-10-16T00:00:00\",\"2025-10-17T00:00:00\",\"2025-10-18T00:00:00\",\"2025-10-19T00:00:00\",\"2025-10-20T00:00:00\"],\"y\":{\"dtype\":\"i2\",\"bdata\":\"HAAEACUACAAhAVsASABAAGUAFQFHAAsAqwCTADQA\\u002fQAmAH8A+ABpAW0AGAAEAAEACwBLAEkAcwCNAAcA7ADhAG8BDQNAAgcBjQHcAYYCbAKpAV0B3QL0AIgAZgFgATsBvQFYASQB4QBzAR4B1wDOAE0CpgGEAbYBzQCwAZUAhAADAMQAogDuAOQAmQDRAGYBZwHXAEMB7AEuAQgAEwBJAAsBuAHOATwB\\u002fgDnABABwACiALwAiAG1AHIBdwAaAW0BXAG0AQMAAwAYABIAJQAXAX0AMQABAAUA2gC+AewBhQHHALABmQGaALkBPAKGAeQAwQF1AMAA6gCeAHwA5gDjAM8ALQFwAW0AaQB1AFYBlAHIAMQAAQFfAJMAogCUABEBjQCqADEAAwAgAC8AiQBXAJoASgAXAGAALwA6AAEARQACAAEAOALwAVEAAQHWAJMAbwBzAL4A1wBgAS8BAgABAAIACQAOAAEAeAG2AO4A0AGcAMYCcgFwALIBsgCMAbAApgF8AgABsALEAEoBLgGyAHoAegFcAuACsAC+AaQBTgJ8AwgFgAGGARoCzAL4AtQCegEeARIC6gH6AeoChASuBKwBsAJ6AZ4CZgJyA+4DFgJQAjYECAJiAngBvAKuA54BogE0AAIACgAaADAA0gO2AYoBwAEoAQID7AFsAfgAagFEAlgBXAJSA\\u002fIBogFaAToCugJcBCoDVgPgAl4CZwAHAIkAWwDVAGYAkwAGAAcAeADzACYASwDWAAEAjQDcAGYAxwB\\u002fAMEAAwAMAH8AcAC4AIcADAB6AGoAogCeAE4AAQDPAKEAaABWAH8AAQBuAKIAkADYAHoARgBiAGkAkgBMAUoBJwFtASQBUwA=\"},\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"shapes\":[{\"fillcolor\":\"#2ecc71\",\"layer\":\"below\",\"line\":{\"width\":0},\"opacity\":0.2,\"type\":\"rect\",\"x0\":\"2024-12-12T00:00:00\",\"x1\":\"2024-12-24T00:00:00\",\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"},{\"fillcolor\":\"#2ecc71\",\"layer\":\"below\",\"line\":{\"width\":0},\"opacity\":0.2,\"type\":\"rect\",\"x0\":\"2025-01-23T00:00:00\",\"x1\":\"2025-01-29T00:00:00\",\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"},{\"fillcolor\":\"#2ecc71\",\"layer\":\"below\",\"line\":{\"width\":0},\"opacity\":0.2,\"type\":\"rect\",\"x0\":\"2025-02-06T00:00:00\",\"x1\":\"2025-02-10T00:00:00\",\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"},{\"fillcolor\":\"#2ecc71\",\"layer\":\"below\",\"line\":{\"width\":0},\"opacity\":0.2,\"type\":\"rect\",\"x0\":\"2025-02-27T00:00:00\",\"x1\":\"2025-03-10T00:00:00\",\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"},{\"fillcolor\":\"#2ecc71\",\"layer\":\"below\",\"line\":{\"width\":0},\"opacity\":0.2,\"type\":\"rect\",\"x0\":\"2025-04-16T00:00:00\",\"x1\":\"2025-05-05T00:00:00\",\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"},{\"fillcolor\":\"#2ecc71\",\"layer\":\"below\",\"line\":{\"width\":0},\"opacity\":0.2,\"type\":\"rect\",\"x0\":\"2025-05-17T00:00:00\",\"x1\":\"2025-05-24T00:00:00\",\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"},{\"fillcolor\":\"#2ecc71\",\"layer\":\"below\",\"line\":{\"width\":0},\"opacity\":0.2,\"type\":\"rect\",\"x0\":\"2025-07-21T00:00:00\",\"x1\":\"2025-07-26T00:00:00\",\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"},{\"fillcolor\":\"#2ecc71\",\"layer\":\"below\",\"line\":{\"width\":0},\"opacity\":0.2,\"type\":\"rect\",\"x0\":\"2025-08-22T00:00:00\",\"x1\":\"2025-10-11T00:00:00\",\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"}],\"annotations\":[{\"font\":{\"size\":9},\"showarrow\":false,\"text\":\"Chapada\\u002fBSB (1\\u00aa viagem)\",\"textangle\":-90,\"x\":\"2024-12-12T00:00:00\",\"xanchor\":\"left\",\"xref\":\"x\",\"y\":1,\"yanchor\":\"top\",\"yref\":\"y domain\"},{\"font\":{\"size\":9},\"showarrow\":false,\"text\":\"BSB (Janeiro)\",\"textangle\":-90,\"x\":\"2025-01-23T00:00:00\",\"xanchor\":\"left\",\"xref\":\"x\",\"y\":1,\"yanchor\":\"top\",\"yref\":\"y domain\"},{\"font\":{\"size\":9},\"showarrow\":false,\"text\":\"Let\\u00edcia SP (Hostel)\",\"textangle\":-90,\"x\":\"2025-02-06T00:00:00\",\"xanchor\":\"left\",\"xref\":\"x\",\"y\":1,\"yanchor\":\"top\",\"yref\":\"y domain\"},{\"font\":{\"size\":9},\"showarrow\":false,\"text\":\"BSB (Carnaval)\",\"textangle\":-90,\"x\":\"2025-02-27T00:00:00\",\"xanchor\":\"left\",\"xref\":\"x\",\"y\":1,\"yanchor\":\"top\",\"yref\":\"y domain\"},{\"font\":{\"size\":9},\"showarrow\":false,\"text\":\"BSB (Abril-Maio)\",\"textangle\":-90,\"x\":\"2025-04-16T00:00:00\",\"xanchor\":\"left\",\"xref\":\"x\",\"y\":1,\"yanchor\":\"top\",\"yref\":\"y domain\"},{\"font\":{\"size\":9},\"showarrow\":false,\"text\":\"Let\\u00edcia Sorocaba\",\"textangle\":-90,\"x\":\"2025-05-17T00:00:00\",\"xanchor\":\"left\",\"xref\":\"x\",\"y\":1,\"yanchor\":\"top\",\"yref\":\"y domain\"},{\"font\":{\"size\":9},\"showarrow\":false,\"text\":\"Let\\u00edcia SP (Trampo)\",\"textangle\":-90,\"x\":\"2025-07-21T00:00:00\",\"xanchor\":\"left\",\"xref\":\"x\",\"y\":1,\"yanchor\":\"top\",\"yref\":\"y domain\"},{\"font\":{\"size\":9},\"showarrow\":false,\"text\":\"BSB (2 meses!)\",\"textangle\":-90,\"x\":\"2025-08-22T00:00:00\",\"xanchor\":\"left\",\"xref\":\"x\",\"y\":1,\"yanchor\":\"top\",\"yref\":\"y domain\"}],\"title\":{\"text\":\"Timeline de Mensagens com Per\\u00edodos de Encontros\"},\"xaxis\":{\"title\":{\"text\":\"Data\"}},\"yaxis\":{\"title\":{\"text\":\"Quantidade de Mensagens\"}},\"height\":800,\"hovermode\":\"x unified\",\"showlegend\":true},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('ef7c0b9a-c64a-4c96-860c-db6d7c78c920');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nVolume de mensagens com encontros marcados\n:::\n:::\n\n\n## Volume: Junto vs Separado\n\n::: {#63e46cdb .cell execution_count=13}\n``` {.python .cell-code}\n# Calcula estatísticas\ndurante_encontros = df[df['em_encontro']].groupby('data_msg').size()\nfora_encontros = df[~df['em_encontro']].groupby('data_msg').size()\n\nprint(\"📊 Volume de Mensagens: Junto vs Separado\\n\")\nprint(f\"{'Estatística':<25} {'Juntos':<15} {'Separados':<15}\")\nprint(\"=\"*55)\nprint(f\"{'Média msgs/dia':<25} {durante_encontros.mean():<15.1f} {fora_encontros.mean():<15.1f}\")\nprint(f\"{'Mediana msgs/dia':<25} {durante_encontros.median():<15.0f} {fora_encontros.median():<15.0f}\")\nprint(f\"{'Desvio padrão':<25} {durante_encontros.std():<15.1f} {fora_encontros.std():<15.1f}\")\nprint(f\"{'Mínimo':<25} {durante_encontros.min():<15.0f} {fora_encontros.min():<15.0f}\")\nprint(f\"{'Máximo':<25} {durante_encontros.max():<15.0f} {fora_encontros.max():<15.0f}\")\n\n# Teste estatístico\nfrom scipy.stats import ttest_ind\n\nstat_t, p_value = ttest_ind(durante_encontros, fora_encontros)\n\nprint(f\"\\n📊 Teste T (volume juntos vs separados):\")\nprint(f\"   t-statistic: {stat_t:.4f}\")\nprint(f\"   p-value: {p_value:.6f}\")\n\nif p_value < 0.001:\n    print(f\"   ✅ Diferença ALTAMENTE significativa (p < 0.001)\")\nelif p_value < 0.05:\n    print(f\"   ✅ Diferença significativa (p < 0.05)\")\nelse:\n    print(f\"   ❌ Sem diferença significativa (p >= 0.05)\")\n\n# Efeito prático\nreducao_pct = ((fora_encontros.mean() - durante_encontros.mean()) / fora_encontros.mean()) * 100\nprint(f\"\\n📉 Efeito prático:\")\nprint(f\"   Volume CAI {reducao_pct:.1f}% quando estão juntos\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📊 Volume de Mensagens: Junto vs Separado\n\nEstatística               Juntos          Separados      \n=======================================================\nMédia msgs/dia            117.8           372.0          \nMediana msgs/dia          99              346            \nDesvio padrão             134.7           243.7          \nMínimo                    1               4              \nMáximo                    942             1288           \n\n📊 Teste T (volume juntos vs separados):\n   t-statistic: -10.3133\n   p-value: 0.000000\n   ✅ Diferença ALTAMENTE significativa (p < 0.001)\n\n📉 Efeito prático:\n   Volume CAI 68.3% quando estão juntos\n```\n:::\n:::\n\n\n::: {#cell-fig-volume-junto-separado .cell execution_count=14}\n``` {.python .cell-code}\n# Prepara dados\ndf_plot = pd.DataFrame({\n    'Contexto': ['Juntos', 'Separados'],\n    'Média': [durante_encontros.mean(), fora_encontros.mean()],\n    'Mediana': [durante_encontros.median(), fora_encontros.median()]\n})\n\n# Visualização\nfig = go.Figure()\n\nfig.add_trace(go.Bar(\n    x=df_plot['Contexto'],\n    y=df_plot['Média'],\n    name='Média',\n    marker_color=[COLORS['juntos'], COLORS['neutral']],\n    text=df_plot['Média'].round(1),\n    textposition='outside'\n))\n\nfig.update_layout(\n    title='Volume Médio de Mensagens por Dia: Junto vs Separado',\n    yaxis_title='Mensagens por Dia',\n    height=400,\n    showlegend=False\n)\n\nfig.show()\n```\n\n::: {#fig-volume-junto-separado .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"256106b0-c39b-4d98-9020-b896b319eae6\" class=\"plotly-graph-div\" style=\"height:400px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"256106b0-c39b-4d98-9020-b896b319eae6\")) {                    Plotly.newPlot(                        \"256106b0-c39b-4d98-9020-b896b319eae6\",                        [{\"marker\":{\"color\":[\"#2ecc71\",\"#95a5a6\"]},\"name\":\"M\\u00e9dia\",\"text\":{\"dtype\":\"f8\",\"bdata\":\"MzMzMzNzXUAAAAAAAEB3QA==\"},\"textposition\":\"outside\",\"x\":[\"Juntos\",\"Separados\"],\"y\":{\"dtype\":\"f8\",\"bdata\":\"TGcxncV0XUAAAAAAAEB3QA==\"},\"type\":\"bar\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"title\":{\"text\":\"Volume M\\u00e9dio de Mensagens por Dia: Junto vs Separado\"},\"yaxis\":{\"title\":{\"text\":\"Mensagens por Dia\"}},\"height\":400,\"showlegend\":false},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('256106b0-c39b-4d98-9020-b896b319eae6');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nComparação de volume: junto vs separado\n:::\n:::\n\n\n## Gaps Coincidem com Encontros?\n\n::: {#8c28888f .cell execution_count=15}\n``` {.python .cell-code}\n# Define threshold de \"gap\" (dias com volume muito baixo)\nTHRESHOLD_GAP = 10  # msgs/dia\n\n# Identifica dias com volume baixo\ndias_baixo_volume = msgs_por_dia[msgs_por_dia['count'] < THRESHOLD_GAP].copy()\ndias_baixo_volume['data'] = dias_baixo_volume['data_msg'].dt.date\n\n# Verifica quantos coincidem com encontros\ndias_baixo_volume['eh_encontro'] = dias_baixo_volume['data'].apply(\n    lambda d: any((e['inicio'].date() <= d <= e['fim'].date()) for _, e in encontros_df.iterrows())\n)\n\ntotal_gaps = len(dias_baixo_volume)\ngaps_em_encontros = dias_baixo_volume['eh_encontro'].sum()\npct_coincidencia = (gaps_em_encontros / total_gaps) * 100 if total_gaps > 0 else 0\n\nprint(f\"📊 Análise de Gaps (dias com < {THRESHOLD_GAP} msgs/dia):\\n\")\nprint(f\"   • Total de dias com volume baixo: {total_gaps}\")\nprint(f\"   • Coincidem com encontros: {gaps_em_encontros} ({pct_coincidencia:.1f}%)\")\nprint(f\"   • Não coincidem: {total_gaps - gaps_em_encontros} ({100-pct_coincidencia:.1f}%)\")\n\nif pct_coincidencia > 70:\n    print(f\"\\n   ✅ HIPÓTESE CONFIRMADA: Maioria dos gaps coincide com encontros!\")\nelif pct_coincidencia > 50:\n    print(f\"\\n   ⚠️ HIPÓTESE PARCIALMENTE CONFIRMADA: Metade dos gaps coincide com encontros\")\nelse:\n    print(f\"\\n   ❌ HIPÓTESE NÃO CONFIRMADA: Maioria dos gaps NÃO coincide com encontros\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📊 Análise de Gaps (dias com < 10 msgs/dia):\n\n   • Total de dias com volume baixo: 28\n   • Coincidem com encontros: 26 (92.9%)\n   • Não coincidem: 2 (7.1%)\n\n   ✅ HIPÓTESE CONFIRMADA: Maioria dos gaps coincide com encontros!\n```\n:::\n:::\n\n\n::: {.callout-warning}\n### 💡 Insight - Volume: Junto vs Separado\n\n**Impacto dramático da presença física:**\n- **Separados:** 372 msgs/dia (mediana: 346)\n- **Juntos:** 118 msgs/dia (mediana: 99)\n- **Redução:** 68.3% quando estão presencialmente juntos\n\n**Validação estatística:**\n- t-statistic: -10.31 (fortíssimo)\n- p-value < 0.001 (altamente significativo)\n- **Conclusão:** Presença física reduz comunicação digital em **mais de 2/3**\n\n**Variabilidade:**\n- Separados: Desvio padrão 244 (alta variabilidade - 4 a 1.288 msgs/dia)\n- Juntos: Desvio padrão 135 (variabilidade moderada - 1 a 942 msgs/dia)\n- Mesmo quando juntos, há dias com muita comunicação (máx: 942) - possivelmente em momentos específicos\n\n**Interpretação:**\n- Quando **separados**: Mensagens são o principal canal de conexão (372 msgs/dia = ~15 msgs/hora acordados)\n- Quando **juntos**: Comunicação digital complementa presença física (118 msgs/dia = ~5 msgs/hora)\n- Relacionamento mantém comunicação mesmo presencialmente - não há \"silêncio digital total\"\n\n**Validação visual (timeline):**\n- Períodos verdes (encontros) claramente coincidem com quedas no volume\n- Picos mais altos (Jun-Jul: 1.200+ msgs/dia) ocorrem ENTRE encontros\n- Padrão é sistemático e consistente ao longo do ano\n:::\n\n::: {.callout-warning}\n### 💡 Insight - Gaps e Encontros\n\n**Hipótese FORTEMENTE confirmada:**\n- **92.9% dos gaps coincidem com encontros** (26 de 28 dias)\n- Apenas **2 dias** com volume <10 msgs NÃO são encontros (7.1%)\n\n**Interpretação dos 2 dias não-encontros:**\n- Podem ser dias de viagem (deslocamento SP↔BSB)\n- Dias com problemas técnicos (internet, celular)\n- Dias atípicos por outros motivos externos\n\n**Conclusão robusta:**\n- **Presença física é o principal preditor de volume baixo**\n- \"Gap no timeline\" = 93% de chance de ser encontro presencial\n- Timeline de mensagens funciona como **proxy de distância física**\n\n**Implicação para modelagem:**\n- Feature `em_encontro` será CRÍTICA em qualquer modelo preditivo\n- Modelos que ignoram contexto externo terão poder limitado\n- Relacionamento à distância tem dinâmica própria - não pode ser analisado sem contexto físico\n:::\n\n---\n\n# Impacto nos Padrões Temporais\n\n## Hora do Dia: Junto vs Separado\n\n::: {#cell-fig-hora-contexto .cell execution_count=16}\n``` {.python .cell-code}\n# Calcula distribuição por hora e contexto\ndf['hora'] = df['timestamp'].dt.hour\n\nhora_junto = df[df['em_encontro']].groupby('hora').size()\nhora_separado = df[~df['em_encontro']].groupby('hora').size()\n\n# Normaliza (proporção)\nhora_junto_pct = (hora_junto / hora_junto.sum() * 100).reindex(range(24), fill_value=0)\nhora_separado_pct = (hora_separado / hora_separado.sum() * 100).reindex(range(24), fill_value=0)\n\n# Visualização\nfig = go.Figure()\n\nfig.add_trace(go.Scatter(\n    x=list(range(24)),\n    y=hora_separado_pct,\n    mode='lines+markers',\n    name='Separados',\n    line=dict(color=COLORS['neutral'], width=2),\n    marker=dict(size=6)\n))\n\nfig.add_trace(go.Scatter(\n    x=list(range(24)),\n    y=hora_junto_pct,\n    mode='lines+markers',\n    name='Juntos',\n    line=dict(color=COLORS['juntos'], width=2),\n    marker=dict(size=6)\n))\n\nfig.update_layout(\n    title='Distribuição por Hora do Dia: Junto vs Separado (%)',\n    xaxis_title='Hora do Dia',\n    yaxis_title='Proporção de Mensagens (%)',\n    height=800,\n    hovermode='x unified',\n    xaxis=dict(tickmode='linear', tick0=0, dtick=1)\n)\n\nfig.show()\n\n# Teste estatístico\nfrom scipy.stats import chi2_contingency\n\ncontingency = pd.crosstab(df['hora'], df['em_encontro'])\nchi2, p_val, dof, expected = chi2_contingency(contingency)\n\nprint(f\"\\n📊 Teste Chi-square (padrão horário junto vs separado):\")\nprint(f\"   p-value: {p_val:.6f}\")\nif p_val < 0.05:\n    print(f\"   ✅ Padrões horários SÃO diferentes quando juntos vs separados\")\nelse:\n    print(f\"   ❌ Padrões horários SÃO similares independente do contexto\")\n```\n\n::: {#fig-hora-contexto .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"4cf5c206-7c5c-46e0-85ae-79cbb56eaea0\" class=\"plotly-graph-div\" style=\"height:800px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"4cf5c206-7c5c-46e0-85ae-79cbb56eaea0\")) {                    Plotly.newPlot(                        \"4cf5c206-7c5c-46e0-85ae-79cbb56eaea0\",                        [{\"line\":{\"color\":\"#95a5a6\",\"width\":2},\"marker\":{\"size\":6},\"mode\":\"lines+markers\",\"name\":\"Separados\",\"x\":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],\"y\":{\"dtype\":\"f8\",\"bdata\":\"E7c5iNoH+j98iA7qHf3aP9yPS6AXS+w\\u002fFzRB9hyMxD9OfQ0alS22P5Fuk62hkbM\\u002fOLTmNK9m1z9VhuHfMYfjPyDrv0\\u002fJn\\u002fg\\u002fCcvDoNt7BkC0KLDXnfsPQNwWmJpaCRVAMwQS7VwLF0CB4iLCCcwUQJngQDVCCxNAzdAN22+uF0BsMIAyN98eQPnokkXdKSFAnGQg679PI0BcqJHlBWQlQPeQqCE0\\u002fCBAfHYK8iE6HEBAFaUe9e0UQIhBt\\u002fcMsghA\"},\"type\":\"scatter\"},{\"line\":{\"color\":\"#2ecc71\",\"width\":2},\"marker\":{\"size\":6},\"mode\":\"lines+markers\",\"name\":\"Juntos\",\"x\":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],\"y\":{\"dtype\":\"f8\",\"bdata\":\"6F9Ft9LGuD+dszoRAfe0PwAAAAAAAAAAWWJVMI1+fj8AAAAAAAAAAFliVTCNfp4\\u002f1bTCTd7S1z+ystQjG9LyP1\\u002ffyeyhhgdAJuesTkTAIEAYfmtRdogkQIAMcqybTR1AuZ6hZNQBJkDhc3h2GZclQDFixIgRIx5AXTU+GA8TGUANtkqKu64aQDWLIZwARApAl3H5pNo6EEDP4dllXD4dQKbzHvvfDRVAluBRKX9iCkDbXPGfKaEBQIRgiVXBNPo\\u002f\"},\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"title\":{\"text\":\"Hora do Dia\"},\"tickmode\":\"linear\",\"tick0\":0,\"dtick\":1},\"title\":{\"text\":\"Distribui\\u00e7\\u00e3o por Hora do Dia: Junto vs Separado (%)\"},\"yaxis\":{\"title\":{\"text\":\"Propor\\u00e7\\u00e3o de Mensagens (%)\"}},\"height\":800,\"hovermode\":\"x unified\"},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('4cf5c206-7c5c-46e0-85ae-79cbb56eaea0');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nDistribuição por hora: junto vs separado\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n📊 Teste Chi-square (padrão horário junto vs separado):\n   p-value: 0.000000\n   ✅ Padrões horários SÃO diferentes quando juntos vs separados\n```\n:::\n:::\n\n\n## Dia da Semana: Junto vs Separado\n\n::: {#cell-fig-dia-contexto .cell execution_count=17}\n``` {.python .cell-code}\n# Calcula distribuição por dia e contexto\ndf['dia_semana_num'] = df['timestamp'].dt.dayofweek\ndias_semana = ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo']\ndf['dia_semana'] = df['dia_semana_num'].apply(lambda x: dias_semana[x])\n\ndia_junto = df[df['em_encontro']].groupby('dia_semana').size().reindex(dias_semana, fill_value=0)\ndia_separado = df[~df['em_encontro']].groupby('dia_semana').size().reindex(dias_semana, fill_value=0)\n\n# Normaliza\ndia_junto_pct = (dia_junto / dia_junto.sum() * 100)\ndia_separado_pct = (dia_separado / dia_separado.sum() * 100)\n\n# Visualização\nfig = go.Figure()\n\nfig.add_trace(go.Bar(\n    x=dias_semana,\n    y=dia_separado_pct,\n    name='Separados',\n    marker_color=COLORS['neutral'],\n    text=dia_separado_pct.round(1),\n    textposition='outside'\n))\n\nfig.add_trace(go.Bar(\n    x=dias_semana,\n    y=dia_junto_pct,\n    name='Juntos',\n    marker_color=COLORS['juntos'],\n    text=dia_junto_pct.round(1),\n    textposition='outside'\n))\n\nfig.update_layout(\n    title='Distribuição por Dia da Semana: Junto vs Separado (%)',\n    yaxis_title='Proporção de Mensagens (%)',\n    height=400,\n    barmode='group'\n)\n\nfig.show()\n\n# Teste estatístico\ncontingency_dia = pd.crosstab(df['dia_semana'], df['em_encontro'])\nchi2_dia, p_val_dia, dof_dia, expected_dia = chi2_contingency(contingency_dia)\n\nprint(f\"\\n📊 Teste Chi-square (padrão semanal junto vs separado):\")\nprint(f\"   p-value: {p_val_dia:.6f}\")\nif p_val_dia < 0.05:\n    print(f\"   ✅ Padrões semanais SÃO diferentes quando juntos vs separados\")\nelse:\n    print(f\"   ❌ Padrões semanais SÃO similares independente do contexto\")\n```\n\n::: {#fig-dia-contexto .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"cc872592-55ea-4c98-a9d2-61552e1c8739\" class=\"plotly-graph-div\" style=\"height:400px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"cc872592-55ea-4c98-a9d2-61552e1c8739\")) {                    Plotly.newPlot(                        \"cc872592-55ea-4c98-a9d2-61552e1c8739\",                        [{\"marker\":{\"color\":\"#95a5a6\"},\"name\":\"Separados\",\"text\":{\"dtype\":\"f8\",\"bdata\":\"mpmZmZmZJ0AAAAAAAAAvQDMzMzMzMy5AzczMzMzMKkBmZmZmZmYsQGZmZmZmZitAzczMzMxMMEA=\"},\"textposition\":\"outside\",\"x\":[\"Segunda\",\"Ter\\u00e7a\",\"Quarta\",\"Quinta\",\"Sexta\",\"S\\u00e1bado\",\"Domingo\"],\"y\":{\"dtype\":\"f8\",\"bdata\":\"kbxmeyuNJ0AWrN+hOP0uQKj1PmpQNC5ADclrtrfSKkBSjKTNy3YsQKVpchL2XitAVvH78GhMMEA=\"},\"type\":\"bar\"},{\"marker\":{\"color\":\"#2ecc71\"},\"name\":\"Juntos\",\"text\":{\"dtype\":\"f8\",\"bdata\":\"zczMzMzMOkDNzMzMzMwxQM3MzMzMTDFAAAAAAACAMUBmZmZmZmYjQGZmZmZmZgpAmpmZmZmZHUA=\"},\"textposition\":\"outside\",\"x\":[\"Segunda\",\"Ter\\u00e7a\",\"Quarta\",\"Quinta\",\"Sexta\",\"S\\u00e1bado\",\"Domingo\"],\"y\":{\"dtype\":\"f8\",\"bdata\":\"Hiaao8HWOkBH8gUXh9YxQA+CJVYFUzFA0hwNtkqKMUD3chKJM3IjQJbgUSl\\u002fYgpAsUznPfa\\u002fHUA=\"},\"type\":\"bar\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"title\":{\"text\":\"Distribui\\u00e7\\u00e3o por Dia da Semana: Junto vs Separado (%)\"},\"yaxis\":{\"title\":{\"text\":\"Propor\\u00e7\\u00e3o de Mensagens (%)\"}},\"height\":400,\"barmode\":\"group\"},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('cc872592-55ea-4c98-a9d2-61552e1c8739');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nDistribuição por dia da semana: junto vs separado\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n📊 Teste Chi-square (padrão semanal junto vs separado):\n   p-value: 0.000000\n   ✅ Padrões semanais SÃO diferentes quando juntos vs separados\n```\n:::\n:::\n\n\n::: {.callout-warning}\n### 💡 Insight - Padrão Horário: Junto vs Separado\n\n**Mudança DRÁSTICA no comportamento (p < 0.001):**\n\n**Quando SEPARADOS (cinza - padrão unimodal):**\n- Pico único às **19h** (10.5%) - após expediente de trabalho\n- Crescimento gradual ao longo do dia\n- Comunicação concentrada no período **noturno** (18h-23h)\n- Madrugada praticamente vazia\n\n**Quando JUNTOS (verde - padrão bimodal):**\n- **Primeiro pico:** 12h-13h (11.5%) - horário de almoço/pausa 🍽️\n- **Segundo pico:** 18h (7.5%) - fim de expediente\n- Comunicação mais **distribuída** ao longo do dia\n- Inicio mais cedo (atividade desde 8h-9h)\n\n**Contexto explicativo:**\n- **Pico 12h-13h:** Momento em que ela consegue responder (trabalho puxado, pausa do almoço é janela de disponibilidade)\n- **Padrão bimodal:** Reflete rotina de trabalho - conversam nas \"brechas\" (almoço + fim do expediente)\n- Quando separados: Conversam após trabalho (noite livre)\n- Quando juntos: Conversam durante pausas do trabalho (presença física não impede rotina profissional)\n\n**Interpretação:**\n- Presença física NÃO elimina comunicação digital, mas **reorganiza** horários\n- Quando juntos, usam WhatsApp para **coordenação diária** (trabalho, logística)\n- Pico noturno desaparece - substituído por convívio presencial\n- Manhã/tarde ganham relevância - comunicação utilitária, não emocional\n\n**Implicação para FE:**\n- Feature `hora` interage FORTEMENTE com `em_encontro`\n- Criar `periodo_dia × em_encontro` será útil\n- Padrão horário sozinho tem poder limitado sem contexto\n:::\n\n\n::: {.callout-warning}\n### 💡 Insight - Padrão Semanal: Junto vs Separado\n\n**INVERSÃO completa do padrão (p < 0.001):**\n\n**Quando SEPARADOS (cinza - uniforme):**\n- Distribuição relativamente equilibrada (12-16%)\n- Levemente maior aos domingos (16.3%)\n- Sem padrão claro útil/FDS\n\n**Quando JUNTOS (verde - concentração em dias úteis):**\n- **Segunda DISPARA:** 26.8% - quase 1/3 da comunicação! 📈\n- Terça-Quinta: 15-18% (dias úteis normais)\n- **Sábado/Domingo CAEM:** 3.3% e 7.4% - quase desaparecem\n\n**Contexto explicativo:**\n- **Segunda alta (26.8%):** Discussões/ajuda sobre trabalho dela no início da semana\n- **FDS baixo:** Aproveitam presença física sem celular (lazer presencial)\n- Dias úteis: WhatsApp usado para **suporte profissional** e **coordenação logística**\n\n**Padrão identificado:**\n- Quando **juntos**: WhatsApp = ferramenta de **trabalho/coordenação** (dias úteis)\n- Quando **separados**: WhatsApp = ferramenta de **conexão emocional** (todos os dias)\n- FDS juntos: Presença física substitui comunicação digital\n\n**Interpretação:**\n- Relacionamento tem **dois modos** de operação claramente distintos\n- **Modo distância:** Comunicação constante (todos os dias ~igual)\n- **Modo presença:** Comunicação utilitária (concentrada em dias úteis, segundas especialmente)\n- Segunda = dia de \"resolver coisas\" - trabalho dela, planejamento da semana\n\n**Implicação para FE:**\n- Feature `dia_semana` interage FORTEMENTE com `em_encontro`\n- Quando separados: `dia_semana` tem pouco poder (uniforme)\n- Quando juntos: `dia_semana` vira discriminador forte (segunda vs FDS)\n- Criar `eh_segunda × em_encontro` pode ser útil\n:::\n\n\n::: {.callout-important}\n## 🎯 SÍNTESE - Contexto Externo é VARIÁVEL DOMINANTE\n\n**4 validações independentes, 4 confirmações:**\n\n| Validação | Métrica | Resultado | Interpretação |\n|-----------|---------|-----------|---------------|\n| **1. Volume** | t-test | t=-10.31, p<0.001 | ✅ Volume CAI 68% quando juntos |\n| **2. Gaps** | % coincidência | 92.9% | ✅ Gaps = Encontros (quase 100%) |\n| **3. Hora** | χ² | 5.467, p≈0 | ✅ Pico inverte (19h→12h) |\n| **4. Dia** | χ² | 3.867, p≈0 | ✅ Segunda explode, fim de semana some |\n\n**Padrão identificado - DOIS PROTOCOLOS DISTINTOS:**\n\n**PROTOCOLO SEPARADOS (Conexão Emocional):**\n- 📊 Volume: 372 msgs/dia (ALTO)\n- ⏰ Timing: Noturno (pico 19h)\n- 📅 Distribuição: Uniforme (todos os dias iguais)\n- 🎯 Função: Canal PRINCIPAL de relacionamento\n- 💬 Comportamento: Conversas longas, constantes, emocionais\n\n**PROTOCOLO JUNTOS (Coordenação Prática):**\n- 📊 Volume: 118 msgs/dia (BAIXO, -68%)\n- ⏰ Timing: Diurno (pico 12h)\n- 📅 Distribuição: Segunda ALTA (26.8%), fim de semana BAIXO (3-7%)\n- 🎯 Função: Canal SECUNDÁRIO de coordenação\n- 💬 Comportamento: Mensagens curtas, pontuais, práticas\n\n**Implicação CRÍTICA:**\n> `em_encontro` não é apenas uma feature - é um **SWITCH de protocolo** que muda volume, timing, frequência e função da comunicação digital. Análises que ignoram contexto externo perdem 68% da variância e interpretam padrões de forma EQUIVOCADA.\n\n**Próximos passos:**\n- ✅ Filtrar para relacionamento puro (pós 16/dez)\n- ✅ Exportar dataset com contexto integrado\n- ✅ EDA detalhada com protocolos validados\n:::\n\n---\n\n# Descoberta: Período Pré-Relacionamento\n\n::: {#0feca1b3 .cell execution_count=18}\n``` {.python .cell-code}\n# ============================================================================\n# DESCOBERTA CRÍTICA: Período Pré-Relacionamento\n# ============================================================================\n\nprint(\"\\n\" + \"=\"*80)\nprint(\"🔍 DESCOBERTA CRÍTICA - Período Pré-Relacionamento\")\nprint(\"=\"*80)\n\n# Define marco\ndata_marco = pd.Timestamp('2024-12-16')\n\n# Divide dataset\nmsgs_pre = df[df['timestamp'] < data_marco]\nmsgs_pos = df[df['timestamp'] >= data_marco]\n\nprint(f\"\\n📊 DIVISÃO PRÉ vs PÓS RELACIONAMENTO:\\n\")\nprint(f\"📅 Antes de 16/dez/2024 (AMIZADE):\")\nprint(f\"   • Mensagens: {len(msgs_pre):,}\")\nprint(f\"   • Percentual: {len(msgs_pre)/len(df)*100:.1f}%\")\nprint(f\"   • Período: {(data_marco - df['timestamp'].min()).days} dias\")\nprint(f\"   • Média/dia: {len(msgs_pre)/((data_marco - df['timestamp'].min()).days):.1f}\")\n\nprint(f\"\\n💕 Depois de 16/dez/2024 (RELACIONAMENTO):\")\nprint(f\"   • Mensagens: {len(msgs_pos):,}\")\nprint(f\"   • Percentual: {len(msgs_pos)/len(df)*100:.1f}%\")\nprint(f\"   • Período: {(df['timestamp'].max() - data_marco).days + 1} dias\")\nprint(f\"   • Média/dia: {len(msgs_pos)/((df['timestamp'].max() - data_marco).days + 1):.1f}\")\n\nprint(f\"\\n💡 Interpretação:\")\nprint(f\"   • Período de AMIZADE tem apenas 2.8% das mensagens\")\nprint(f\"   • Média de comunicação 6.4x MAIOR após início do relacionamento\")\nprint(f\"   • ⚠️ MISTURAR os dois períodos = VIÉS INEVITÁVEL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n================================================================================\n🔍 DESCOBERTA CRÍTICA - Período Pré-Relacionamento\n================================================================================\n\n📊 DIVISÃO PRÉ vs PÓS RELACIONAMENTO:\n\n📅 Antes de 16/dez/2024 (AMIZADE):\n   • Mensagens: 2,588\n   • Percentual: 2.8%\n   • Período: 57 dias\n   • Média/dia: 45.4\n\n💕 Depois de 16/dez/2024 (RELACIONAMENTO):\n   • Mensagens: 89,336\n   • Percentual: 97.2%\n   • Período: 309 dias\n   • Média/dia: 289.1\n\n💡 Interpretação:\n   • Período de AMIZADE tem apenas 2.8% das mensagens\n   • Média de comunicação 6.4x MAIOR após início do relacionamento\n   • ⚠️ MISTURAR os dois períodos = VIÉS INEVITÁVEL\n```\n:::\n:::\n\n\n::: {.callout-warning}\n## 🔍 Descoberta Crítica - Dataset Contém Dois Períodos Distintos\n\n**Divisão temporal identificada:**\n\n**📅 ANTES de 16/dez/2024 (AMIZADE):**\n- **2.588 mensagens** (2.8% do total)\n- **57 dias** de período\n- **45.4 msgs/dia** em média\n- Comunicação esporádica, dias sem contato eram comuns\n\n**💕 DEPOIS de 16/dez/2024 (RELACIONAMENTO):**\n- **89.336 mensagens** (97.2% do total)\n- **309 dias** de período\n- **289.1 msgs/dia** em média\n- **Aumento de 6.4x** na comunicação!\n\n**Contexto do marco:**\n- 16/dezembro/2024 = Primeiro encontro/beijo em Brasília\n- Marca transição de **amizade** para **relacionamento**\n- Mudança DRAMÁTICA no padrão de comunicação\n\n**Problema metodológico:**\n- Misturar amizade + relacionamento = **VIÉS INEVITÁVEL**\n- Comportamentos são fundamentalmente diferentes\n- Análises temporais ficam **CONTAMINADAS**\n- Médias ficam **DISTORCIDAS**\n\n**Decisão:**\n> **FILTRAR** análises de padrões temporais e de interação para **pós 16/dez/2024** (relacionamento puro). Período de amizade será excluído para garantir consistência metodológica.\n\n**Impacto:**\n- Dataset original: 91.924 mensagens\n- Dataset filtrado: 89.336 mensagens\n- Perda: Apenas 2.8% (marginal)\n- Ganho: Pureza analítica (crítico!)\n:::\n\n---\n\n# Validação: \"Nunca Ficaram Sem Falar\"\n\n::: {#560f9b70 .cell execution_count=19}\n``` {.python .cell-code}\n# ============================================================================\n# VALIDAÇÃO: \"Nunca Ficaram Sem Falar\" (Só Relacionamento)\n# ============================================================================\n\nprint(\"\\n\" + \"=\"*80)\nprint(\"🔍 VALIDAÇÃO - Hipótese 'Nunca Ficaram Sem Falar'\")\nprint(\"=\"*80)\n\n# Todos os dias no período de relacionamento\ninicio = data_marco.date()\nfim = df['timestamp'].max().date()\ntodos_dias = pd.date_range(inicio, fim, freq='D')\n\n# Dias COM mensagem no relacionamento\ndias_com_msg = set(msgs_pos['timestamp'].dt.date.unique())\n\n# Dias SEM mensagem\ndias_sem_msg = [dia.date() for dia in todos_dias if dia.date() not in dias_com_msg]\n\nprint(f\"\\n📊 Período de Relacionamento:\")\nprint(f\"   • Total de dias: {len(todos_dias)}\")\nprint(f\"   • Dias COM mensagem: {len(dias_com_msg)} ({len(dias_com_msg)/len(todos_dias)*100:.1f}%)\")\nprint(f\"   • Dias SEM mensagem: {len(dias_sem_msg)} ({len(dias_sem_msg)/len(todos_dias)*100:.1f}%)\")\n\n# Verifica se dias sem msg estão em encontros\nif len(dias_sem_msg) > 0:\n    print(f\"\\n📅 Dias SEM mensagem ({len(dias_sem_msg)}):\")\n\n    dias_sem_msg_info = []\n    for dia in dias_sem_msg:\n        em_encontro = False\n        encontro_nome = None\n\n        for _, enc in encontros_df.iterrows():\n            if enc['inicio'].date() <= dia <= enc['fim'].date():\n                em_encontro = True\n                encontro_nome = enc['nome']\n                break\n\n        dias_sem_msg_info.append({\n            'Data': dia,\n            'Em Encontro': em_encontro,\n            'Encontro': encontro_nome if em_encontro else 'Separados'\n        })\n\n    df_sem_msg = pd.DataFrame(dias_sem_msg_info)\n    print(df_sem_msg.to_string(index=False))\n\n    # Resumo\n    total_sem_msg = len(dias_sem_msg)\n    sem_msg_em_encontro = df_sem_msg['Em Encontro'].sum()\n    sem_msg_separados = total_sem_msg - sem_msg_em_encontro\n\n    print(f\"\\n📊 RESUMO:\")\n    print(f\"   • Total de dias sem mensagem: {total_sem_msg}\")\n    print(f\"   • Durante encontros: {sem_msg_em_encontro} ({sem_msg_em_encontro/total_sem_msg*100:.1f}%)\")\n    print(f\"   • Quando separados: {sem_msg_separados} ({sem_msg_separados/total_sem_msg*100:.1f}%)\")\n\n    if sem_msg_separados == 0:\n        print(f\"\\n✅ HIPÓTESE VALIDADA: 100% dos dias sem mensagem = Durante encontros!\")\n        print(f\"   → NUNCA ficaram sem falar quando separados\")\n    else:\n        print(f\"\\n⚠️ {sem_msg_separados} dia(s) sem mensagem quando separados - investigar!\")\nelse:\n    print(f\"\\n✅ ZERO dias sem mensagem no relacionamento!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n================================================================================\n🔍 VALIDAÇÃO - Hipótese 'Nunca Ficaram Sem Falar'\n================================================================================\n\n📊 Período de Relacionamento:\n   • Total de dias: 309\n   • Dias COM mensagem: 301 (97.4%)\n   • Dias SEM mensagem: 8 (2.6%)\n\n📅 Dias SEM mensagem (8):\n      Data  Em Encontro         Encontro\n2025-04-18         True BSB (Abril-Maio)\n2025-04-26         True BSB (Abril-Maio)\n2025-05-20         True Letícia Sorocaba\n2025-08-30         True   BSB (2 meses!)\n2025-09-20         True   BSB (2 meses!)\n2025-09-21         True   BSB (2 meses!)\n2025-09-28         True   BSB (2 meses!)\n2025-10-11         True   BSB (2 meses!)\n\n📊 RESUMO:\n   • Total de dias sem mensagem: 8\n   • Durante encontros: 8 (100.0%)\n   • Quando separados: 0 (0.0%)\n\n✅ HIPÓTESE VALIDADA: 100% dos dias sem mensagem = Durante encontros!\n   → NUNCA ficaram sem falar quando separados\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## 🎯 Validação - \"Nunca Ficaram Sem Falar Quando Separados\"\n\n**Hipótese testada:**\n> Durante o relacionamento, nunca passaram um único dia sem trocar mensagens quando estavam separados.\n\n**Resultado da validação:**\n\n**Período analisado:** 16/dez/2024 → 11/out/2025 (309 dias)\n\n**Estatísticas:**\n- **301 dias COM mensagem** (97.4%)\n- **8 dias SEM mensagem** (2.6%)\n\n**Dias sem mensagem identificados:**\n\n| Data | Contexto | Encontro |\n|------|----------|----------|\n| 18/abr/2025 | Durante encontro | BSB (Abril-Maio) |\n| 26/abr/2025 | Durante encontro | BSB (Abril-Maio) |\n| 20/mai/2025 | Durante encontro | Letícia Sorocaba |\n| 30/ago/2025 | Durante encontro | BSB (2 meses!) |\n| 20/set/2025 | Durante encontro | BSB (2 meses!) |\n| 21/set/2025 | Durante encontro | BSB (2 meses!) |\n| 28/set/2025 | Durante encontro | BSB (2 meses!) |\n| 11/out/2025 | Durante encontro | BSB (2 meses!) |\n\n**Resultado:**\n- ✅ **100% dos dias sem mensagem = Durante encontros presenciais**\n- ✅ **0% quando separados**\n\n**Interpretação:**\n\n**Consistência absoluta:**\n- Durante **309 dias** de relacionamento à distância\n- **ZERO dias** sem comunicação quando separados\n- Único motivo para ausência de mensagens = **presença física**\n\n**Padrão identificado:**\n- 5 dos 8 dias sem msg = Encontro longo (BSB 2 meses, 51 dias)\n- Dias sem msg nesse encontro = Momentos de **total imersão** no convívio\n- Mesmo durante encontros, comunicam **97% dos dias** (118 msgs/dia)\n\n**Conclusão validada:**\n> Relacionamento à distância opera com **ZERO gaps** de comunicação digital quando separados. WhatsApp funciona como **canal constante** de conexão emocional, substituído apenas por convívio presencial durante encontros.\n\n**Implicação para análise:**\n- Gaps no timeline (>24h) = **Sempre** durante encontros ou pré-relacionamento\n- Feature `em_encontro` é **ESSENCIAL** - único preditor de ausência de comunicação\n- Relacionamento tem dois modos: Conexão digital constante ↔ Convívio presencial\n:::\n\n---\n\n# Decisão Metodológica: Marcação de Períodos\n\n::: {#c005d525 .cell execution_count=20}\n``` {.python .cell-code}\n# ============================================================================\n# DECISÃO: Filtrar para Relacionamento (pós 16/dez/2024)\n# ============================================================================\n\nprint(\"\\n\" + \"=\"*80)\nprint(\"⚠️ DECISÃO METODOLÓGICA - Filtro de Relacionamento\")\nprint(\"=\"*80)\n\nprint(f\"\\n🎯 Razões para filtrar:\")\nprint(f\"   1. Amizade ≠ Relacionamento (contextos diferentes)\")\nprint(f\"   2. Apenas 2.8% das mensagens (impacto marginal)\")\nprint(f\"   3. Média 6.4x diferente (45 vs 290 msgs/dia)\")\nprint(f\"   4. Evitar viés em análises temporais\")\nprint(f\"   5. Foco em relacionamento (objetivo do estudo)\")\n\nprint(f\"\\n📊 Dataset ANTES do filtro:\")\nprint(f\"   • Mensagens: {len(df):,}\")\nprint(f\"   • Período: {df['timestamp'].min().date()} → {df['timestamp'].max().date()}\")\nprint(f\"   • Contexto: Amizade + Relacionamento (MISTURADO)\")\n\n# APLICA FILTRO\ndf_filtered = df[df['timestamp'] >= data_marco].copy()\n\nprint(f\"\\n📊 Dataset DEPOIS do filtro:\")\nprint(f\"   • Mensagens: {len(df_filtered):,}\")\nprint(f\"   • Período: {df_filtered['timestamp'].min().date()} → {df_filtered['timestamp'].max().date()}\")\nprint(f\"   • Contexto: Relacionamento PURO\")\nprint(f\"   • Removidas: {len(df) - len(df_filtered):,} mensagens de amizade\")\n\nprint(f\"\\n✅ Filtro aplicado - dados prontos para exportação\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n================================================================================\n⚠️ DECISÃO METODOLÓGICA - Filtro de Relacionamento\n================================================================================\n\n🎯 Razões para filtrar:\n   1. Amizade ≠ Relacionamento (contextos diferentes)\n   2. Apenas 2.8% das mensagens (impacto marginal)\n   3. Média 6.4x diferente (45 vs 290 msgs/dia)\n   4. Evitar viés em análises temporais\n   5. Foco em relacionamento (objetivo do estudo)\n\n📊 Dataset ANTES do filtro:\n   • Mensagens: 91,924\n   • Período: 2024-10-19 → 2025-10-20\n   • Contexto: Amizade + Relacionamento (MISTURADO)\n\n📊 Dataset DEPOIS do filtro:\n   • Mensagens: 89,336\n   • Período: 2024-12-16 → 2025-10-20\n   • Contexto: Relacionamento PURO\n   • Removidas: 2,588 mensagens de amizade\n\n✅ Filtro aplicado - dados prontos para exportação\n```\n:::\n:::\n\n\n::: {.callout-warning}\n## ⚠️ Decisão Metodológica - Marcação de Períodos\n\n**Descoberta fundamental:**\n> Dataset contém dois períodos com dinâmicas COMPLETAMENTE diferentes: Amizade (Out-15/Dez) e Relacionamento (16/Dez+).\n\n**Evidências da diferença:**\n\n1. **Contextos distintos:** Amizade ≠ Relacionamento (intenções diferentes)\n2. **Volume 6.4x diferente:** 45 msgs/dia vs 290 msgs/dia\n3. **Percentual:** Apenas 2.8% das mensagens (57 dias)\n4. **Impacto temporal:** Out-Dez/2024 mistura preparação de viagem + primeiros dias juntos\n5. **Objetivo do estudo:** Foco em relacionamento à distância\n\n---\n\n**Estatísticas comparativas:**\n\n**AMIZADE (Out-15/Dez/2024):**\n- 📊 Mensagens: **2.588** (2.8%)\n- 📅 Período: 57 dias\n- 💬 Média: **45.4 msgs/dia**\n- 🏷️ Contexto: Preparação para viagem, amizade evoluindo\n\n**RELACIONAMENTO (16/Dez/2024+):**\n- 📊 Mensagens: **89.336** (97.2%)\n- 📅 Período: 309 dias\n- 💬 Média: **289.1 msgs/dia**\n- 🏷️ Contexto: Relacionamento à distância estabelecido\n\n---\n\n**Decisão tomada:**\n> ✅ **MARCAR período** com feature `fase_relacionamento` (Amizade | Relacionamento)\n>\n> ✅ **EXPORTAR dataset COMPLETO** (91.924 mensagens)\n>\n> ✅ **Notebooks individuais decidem** se filtram ou não\n\n**Razão da estratégia:**\n- **Análises temporais/interação:** Filtrarão para relacionamento (padrões puros)\n- **Análise de conteúdo:** Usará todo período (estilo é mais estável)\n- **Comparações:** Possibilidade de comparar amizade vs relacionamento\n- **Flexibilidade:** Decisão por notebook, não irreversível\n\n---\n\n**Uso da feature `fase_relacionamento`:**\n```python\n# Notebook 04 (temporal) - FILTRA\ndf_rel = df[df['fase_relacionamento'] == 'Relacionamento']\n\n# Notebook 05 (interação) - FILTRA\ndf_rel = df[df['fase_relacionamento'] == 'Relacionamento']\n\n# Notebook 06 (conteúdo) - USA TUDO\n# (sem filtro - analisa todo período)\n```\n\n**Notebooks que FILTRARÃO:**\n- ✅ 05.1-eda-temporal.qmd (padrões temporais puros)\n- ✅ 05.2-eda-interacao.qmd (turnos/sequências puros)\n\n**Notebooks que USARÃO TUDO:**\n- ✅ 03-eda-overview.qmd (pode decidir por seção)\n- ✅ 06-eda-conteudo.qmd (estilo comunicativo geral)\n\n---\n\n**Por que NÃO eliminar:**\n1. Perda irreversível de dados\n2. Análise de conteúdo precisa do período completo\n3. Comparação amizade vs relacionamento valiosa\n4. Feature permite flexibilidade total\n:::\n\n---\n\n# Export Final\n\n::: {#87812cd9 .cell execution_count=21}\n``` {.python .cell-code}\n# ============================================================================\n# PREPARAÇÃO PARA EXPORTAÇÃO - Dataset COMPLETO e ENXUTO\n# ============================================================================\n\nprint(\"\\n\" + \"=\"*80)\nprint(\"💾 PREPARAÇÃO PARA EXPORTAÇÃO\")\nprint(\"=\"*80)\n\nprint(\"\\n📋 Estratégia:\")\nprint(\"   • Exportar TODAS as mensagens (91.924)\")\nprint(\"   • Adicionar 'fase_relacionamento'\")\nprint(\"   • Remover features redundantes/irrelevantes\")\nprint(\"   • Manter apenas 6 features contextuais essenciais\")\n\n# ============================================================================\n# 1. ADICIONA FEATURE DE FASE\n# ============================================================================\n\nprint(\"\\n\" + \"-\"*80)\nprint(\"1️⃣ Adicionando 'fase_relacionamento'\")\nprint(\"-\"*80)\n\n# Marca período (não remove!)\ndata_marco = pd.Timestamp('2024-12-16')\n\ndf['fase_relacionamento'] = df['timestamp'].apply(\n    lambda x: 'Relacionamento' if x >= data_marco else 'Amizade'\n)\n\nprint(f\"\\n✅ Feature 'fase_relacionamento' criada:\")\ncontagem_fases = df['fase_relacionamento'].value_counts()\nprint(f\"   • Amizade: {contagem_fases.get('Amizade', 0):,} mensagens\")\nprint(f\"   • Relacionamento: {contagem_fases.get('Relacionamento', 0):,} mensagens\")\n\n# ============================================================================\n# 2. REMOVE COLUNAS INDESEJADAS\n# ============================================================================\n\nprint(\"\\n\" + \"-\"*80)\nprint(\"2️⃣ Removendo colunas indesejadas\")\nprint(\"-\"*80)\n\n# Todas as colunas a remover (redundantes + auxiliares)\ncolunas_remover = [\n    # Redundantes/irrelevantes\n    'local_encontro',      # Redundante com encontro_nome\n    'tipo_encontro',       # Redundante com encontro_nome\n    'dia_do_encontro',     # Pouco útil (durações diferentes)\n    'eh_marco_especial',   # Irrelevante (0.4% msgs)\n    'marco_nome',          # Irrelevante (N=3)\n    # Auxiliares (temporárias)\n    'data_msg',            # Criada só para merge\n    'hora',                # Criada só para validação\n    'dia_semana'           # Criada só para validação\n]\n\n# Remove se existirem\nremovidas = []\nfor col in colunas_remover:\n    if col in df.columns:\n        df = df.drop(columns=[col])\n        removidas.append(col)\n\nif removidas:\n    print(f\"\\n✅ Removidas {len(removidas)} colunas:\")\n    for col in removidas:\n        print(f\"   ❌ {col}\")\nelse:\n    print(f\"\\n⚠️ Nenhuma coluna para remover (já removidas?)\")\n\n# ============================================================================\n# 3. VALIDAÇÕES PRÉ-EXPORTAÇÃO\n# ============================================================================\n\nprint(\"\\n\" + \"-\"*80)\nprint(\"3️⃣ Validações pré-exportação\")\nprint(\"-\"*80)\n\nprint(f\"\\n📊 Estatísticas do dataset:\")\nprint(f\"   • Total de mensagens: {len(df):,}\")\nprint(f\"   • Total de colunas: {len(df.columns)}\")\nprint(f\"   • Período: {df['timestamp'].min().date()} → {df['timestamp'].max().date()}\")\n\nprint(f\"\\n📊 Distribuição por fase:\")\nfor fase, count in df['fase_relacionamento'].value_counts().items():\n    pct = count / len(df) * 100\n    print(f\"   • {fase}: {count:,} ({pct:.1f}%)\")\n\nprint(f\"\\n🏷️ Features contextuais mantidas (6):\")\nfeatures_contextuais = [\n    'em_encontro',\n    'fase_relacionamento',\n    'encontro_id',\n    'encontro_nome',\n    'dias_desde_ultimo_encontro',\n    'dias_ate_proximo_encontro'\n]\n\nfor feat in features_contextuais:\n    if feat in df.columns:\n        n_validos = df[feat].notna().sum()\n        pct = n_validos / len(df) * 100\n        print(f\"   ✅ {feat}: {n_validos:,} válidos ({pct:.1f}%)\")\n    else:\n        print(f\"   ❌ {feat}: FALTANDO!\")\n\nprint(f\"\\n🔍 Validação de consistência:\")\n\n# Mensagens durante encontro NÃO devem ter dias_desde/ate\nmsgs_durante = df['em_encontro'].sum()\nmsgs_durante_com_dias_desde = df[df['em_encontro'] & df['dias_desde_ultimo_encontro'].notna()].shape[0]\nmsgs_durante_com_dias_ate = df[df['em_encontro'] & df['dias_ate_proximo_encontro'].notna()].shape[0]\n\nif msgs_durante_com_dias_desde == 0 and msgs_durante_com_dias_ate == 0:\n    print(f\"   ✅ Mensagens durante encontro: {msgs_durante:,}\")\n    print(f\"      → Nenhuma tem dias_desde/ate (CORRETO!)\")\nelse:\n    print(f\"   ⚠️ PROBLEMA detectado:\")\n    print(f\"      • Msgs durante com dias_desde: {msgs_durante_com_dias_desde}\")\n    print(f\"      • Msgs durante com dias_ate: {msgs_durante_com_dias_ate}\")\n\n# Todas mensagens devem ter fase_relacionamento\nmsgs_sem_fase = df['fase_relacionamento'].isna().sum()\nif msgs_sem_fase == 0:\n    print(f\"   ✅ Todas as mensagens têm 'fase_relacionamento'\")\nelse:\n    print(f\"   ⚠️ {msgs_sem_fase} mensagens SEM fase_relacionamento!\")\n\n# Verifica tipos de dados\nprint(f\"\\n📊 Tipos de dados principais:\")\nprint(f\"   • timestamp: {df['timestamp'].dtype}\")\nprint(f\"   • em_encontro: {df['em_encontro'].dtype}\")\nprint(f\"   • fase_relacionamento: {df['fase_relacionamento'].dtype}\")\nprint(f\"   • encontro_id: {df['encontro_id'].dtype}\")\n\n# ============================================================================\n# 4. LISTA FINAL DE COLUNAS\n# ============================================================================\n\nprint(\"\\n\" + \"-\"*80)\nprint(\"4️⃣ Colunas no dataset final\")\nprint(\"-\"*80)\n\nprint(f\"\\n📋 Total de colunas: {len(df.columns)}\\n\")\n\nprint(\"Colunas CONTEXTUAIS (adicionadas neste notebook):\")\nfor col in features_contextuais:\n    if col in df.columns:\n        print(f\"   ✅ {col}\")\n\nprint(f\"\\nColunas ORIGINAIS (do wrangling):\")\nfor col in df.columns:\n    if col not in features_contextuais:\n        print(f\"   • {col}\")\n\n# ============================================================================\n# 5. EXPORTAÇÃO\n# ============================================================================\n\nprint(\"\\n\" + \"=\"*80)\nprint(\"💾 EXPORTANDO DATASET\")\nprint(\"=\"*80)\n\ndf.to_parquet(OUTPUT_FILE, index=False)\n\nprint(f\"\\n✅ Exportação concluída!\")\nprint(f\"\\n📁 Arquivo: {OUTPUT_FILE.name}\")\nprint(f\"📏 Tamanho: {OUTPUT_FILE.stat().st_size / 1024 / 1024:.2f} MB\")\n\n# ============================================================================\n# 6. TESTE DE INTEGRIDADE\n# ============================================================================\n\nprint(\"\\n\" + \"-\"*80)\nprint(\"6️⃣ Teste de integridade (releitura)\")\nprint(\"-\"*80)\n\ndf_test = pd.read_parquet(OUTPUT_FILE)\n\nprint(f\"\\n✅ Arquivo recarregado com sucesso!\")\nprint(f\"   • Mensagens: {len(df_test):,}\")\nprint(f\"   • Colunas: {len(df_test.columns)}\")\nprint(f\"   • Período: {df_test['timestamp'].min().date()} → {df_test['timestamp'].max().date()}\")\n\n# Valida features contextuais\nprint(f\"\\n🏷️ Features contextuais verificadas:\")\nfor feat in features_contextuais:\n    if feat in df_test.columns:\n        print(f\"   ✅ {feat}\")\n    else:\n        print(f\"   ❌ {feat} - FALTANDO!\")\n\n# Valida que colunas removidas não existem\nprint(f\"\\n🗑️ Colunas removidas verificadas:\")\nfor col in colunas_remover:\n    if col not in df_test.columns:\n        print(f\"   ✅ {col} - removida\")\n    else:\n        print(f\"   ⚠️ {col} - ainda presente!\")\n\n# ============================================================================\n# 7. RESUMO FINAL\n# ============================================================================\n\nprint(\"\\n\" + \"=\"*80)\nprint(\"🎯 RESUMO FINAL - Dataset Exportado\")\nprint(\"=\"*80)\n\nprint(f\"\\n📊 Estatísticas:\")\nprint(f\"   • Arquivo: {OUTPUT_FILE.name}\")\nprint(f\"   • Mensagens: {len(df_test):,} (período completo)\")\nprint(f\"   • Colunas: {len(df_test.columns)}\")\nprint(f\"   • Tamanho: {OUTPUT_FILE.stat().st_size / 1024 / 1024:.2f} MB\")\n\nprint(f\"\\n📅 Período:\")\nprint(f\"   • Início: {df_test['timestamp'].min().date()}\")\nprint(f\"   • Fim: {df_test['timestamp'].max().date()}\")\nprint(f\"   • Dias: {(df_test['timestamp'].max() - df_test['timestamp'].min()).days + 1}\")\n\nprint(f\"\\n🏷️ Contexto:\")\nprint(f\"   • Amizade: {(df_test['fase_relacionamento'] == 'Amizade').sum():,} msgs\")\nprint(f\"   • Relacionamento: {(df_test['fase_relacionamento'] == 'Relacionamento').sum():,} msgs\")\nprint(f\"   • Durante encontros: {df_test['em_encontro'].sum():,} msgs\")\nprint(f\"   • Separados: {(~df_test['em_encontro']).sum():,} msgs\")\n\nprint(f\"\\n✅ Features contextuais (6):\")\nprint(f\"   1. em_encontro (boolean)\")\nprint(f\"   2. fase_relacionamento (string)\")\nprint(f\"   3. encontro_id (int)\")\nprint(f\"   4. encontro_nome (string)\")\nprint(f\"   5. dias_desde_ultimo_encontro (int/float)\")\nprint(f\"   6. dias_ate_proximo_encontro (int/float)\")\n\nprint(f\"\\n🎯 Pronto para EDA!\")\nprint(f\"   → Notebooks seguintes: Carregar '{OUTPUT_FILE.name}'\")\nprint(f\"   → Dataset: COMPLETO (91.924 msgs, todo período)\")\nprint(f\"   → Decisão de filtro: Por notebook\")\n\nprint(\"=\"*80)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n================================================================================\n💾 PREPARAÇÃO PARA EXPORTAÇÃO\n================================================================================\n\n📋 Estratégia:\n   • Exportar TODAS as mensagens (91.924)\n   • Adicionar 'fase_relacionamento'\n   • Remover features redundantes/irrelevantes\n   • Manter apenas 6 features contextuais essenciais\n\n--------------------------------------------------------------------------------\n1️⃣ Adicionando 'fase_relacionamento'\n--------------------------------------------------------------------------------\n\n✅ Feature 'fase_relacionamento' criada:\n   • Amizade: 2,588 mensagens\n   • Relacionamento: 89,336 mensagens\n\n--------------------------------------------------------------------------------\n2️⃣ Removendo colunas indesejadas\n--------------------------------------------------------------------------------\n\n✅ Removidas 8 colunas:\n   ❌ local_encontro\n   ❌ tipo_encontro\n   ❌ dia_do_encontro\n   ❌ eh_marco_especial\n   ❌ marco_nome\n   ❌ data_msg\n   ❌ hora\n   ❌ dia_semana\n\n--------------------------------------------------------------------------------\n3️⃣ Validações pré-exportação\n--------------------------------------------------------------------------------\n\n📊 Estatísticas do dataset:\n   • Total de mensagens: 91,924\n   • Total de colunas: 15\n   • Período: 2024-10-19 → 2025-10-20\n\n📊 Distribuição por fase:\n   • Relacionamento: 89,336 (97.2%)\n   • Amizade: 2,588 (2.8%)\n\n🏷️ Features contextuais mantidas (6):\n   ✅ em_encontro: 91,924 válidos (100.0%)\n   ✅ fase_relacionamento: 91,924 válidos (100.0%)\n   ✅ encontro_id: 13,432 válidos (14.6%)\n   ✅ encontro_nome: 13,432 válidos (14.6%)\n   ✅ dias_desde_ultimo_encontro: 76,042 válidos (82.7%)\n   ✅ dias_ate_proximo_encontro: 78,464 válidos (85.4%)\n\n🔍 Validação de consistência:\n   ✅ Mensagens durante encontro: 13,432\n      → Nenhuma tem dias_desde/ate (CORRETO!)\n   ✅ Todas as mensagens têm 'fase_relacionamento'\n\n📊 Tipos de dados principais:\n   • timestamp: datetime64[us]\n   • em_encontro: bool\n   • fase_relacionamento: str\n   • encontro_id: object\n\n--------------------------------------------------------------------------------\n4️⃣ Colunas no dataset final\n--------------------------------------------------------------------------------\n\n📋 Total de colunas: 15\n\nColunas CONTEXTUAIS (adicionadas neste notebook):\n   ✅ em_encontro\n   ✅ fase_relacionamento\n   ✅ encontro_id\n   ✅ encontro_nome\n   ✅ dias_desde_ultimo_encontro\n   ✅ dias_ate_proximo_encontro\n\nColunas ORIGINAIS (do wrangling):\n   • timestamp\n   • remetente\n   • tipo_mensagem\n   • grupo_mensagem\n   • conteudo\n   • arquivo\n   • transcricao\n   • date_match\n   • dia_semana_num\n\n================================================================================\n💾 EXPORTANDO DATASET\n================================================================================\n\n✅ Exportação concluída!\n\n📁 Arquivo: messages_with_context.parquet\n📏 Tamanho: 2.16 MB\n\n--------------------------------------------------------------------------------\n6️⃣ Teste de integridade (releitura)\n--------------------------------------------------------------------------------\n\n✅ Arquivo recarregado com sucesso!\n   • Mensagens: 91,924\n   • Colunas: 15\n   • Período: 2024-10-19 → 2025-10-20\n\n🏷️ Features contextuais verificadas:\n   ✅ em_encontro\n   ✅ fase_relacionamento\n   ✅ encontro_id\n   ✅ encontro_nome\n   ✅ dias_desde_ultimo_encontro\n   ✅ dias_ate_proximo_encontro\n\n🗑️ Colunas removidas verificadas:\n   ✅ local_encontro - removida\n   ✅ tipo_encontro - removida\n   ✅ dia_do_encontro - removida\n   ✅ eh_marco_especial - removida\n   ✅ marco_nome - removida\n   ✅ data_msg - removida\n   ✅ hora - removida\n   ✅ dia_semana - removida\n\n================================================================================\n🎯 RESUMO FINAL - Dataset Exportado\n================================================================================\n\n📊 Estatísticas:\n   • Arquivo: messages_with_context.parquet\n   • Mensagens: 91,924 (período completo)\n   • Colunas: 15\n   • Tamanho: 2.16 MB\n\n📅 Período:\n   • Início: 2024-10-19\n   • Fim: 2025-10-20\n   • Dias: 367\n\n🏷️ Contexto:\n   • Amizade: 2,588 msgs\n   • Relacionamento: 89,336 msgs\n   • Durante encontros: 13,432 msgs\n   • Separados: 78,492 msgs\n\n✅ Features contextuais (6):\n   1. em_encontro (boolean)\n   2. fase_relacionamento (string)\n   3. encontro_id (int)\n   4. encontro_nome (string)\n   5. dias_desde_ultimo_encontro (int/float)\n   6. dias_ate_proximo_encontro (int/float)\n\n🎯 Pronto para EDA!\n   → Notebooks seguintes: Carregar 'messages_with_context.parquet'\n   → Dataset: COMPLETO (91.924 msgs, todo período)\n   → Decisão de filtro: Por notebook\n================================================================================\n```\n:::\n:::\n\n\n---\n\n# Conclusões\n\n::: {.callout-important}\n### 🎯 Conclusão - Contexto Externo Integrado e Dataset Enriquecido\n\n**Contexto externo mapeado com sucesso:**\n- ✅ **10 encontros presenciais** identificados (122 dias juntos = 33.2% do período)\n- ✅ **Features de distância temporal** criadas (`dias_desde_ultimo_encontro`, `dias_ate_proximo_encontro`)\n- ✅ **Marcos especiais** identificados (3 datas marcantes)\n- ✅ **Período de amizade** descoberto e marcado (Out-15/Dez/2024)\n\n---\n\n**4 validações estatísticas confirmam impacto dramático do contexto:**\n\n**1. Volume de Mensagens:**\n- Separados: **372 msgs/dia**\n- Juntos: **118 msgs/dia**\n- Redução: **-68.3%** (p<0.001, t=-10.31)\n- ✅ Presença física reduz comunicação digital em mais de 2/3\n\n**2. Coincidência de Gaps:**\n- Dias com <10 msgs: **28 dias**\n- Coincidem com encontros: **26 dias (92.9%)**\n- ✅ Timeline de mensagens = proxy de distância física\n\n**3. Padrão Horário:**\n- Separados: Pico **19h** (10.7%) - noturno\n- Juntos: Pico **12h** (11.0%) - diurno\n- χ² = 5.467, p≈0\n- ✅ Contexto inverte completamente o timing da comunicação\n\n**4. Padrão Semanal:**\n- Separados: Uniforme (11-16% todos os dias)\n- Juntos: Segunda **26.8%**, Sábado **3.3%** (8x diferença!)\n- χ² = 3.867, p≈0\n- ✅ Protocolo semanal muda radicalmente quando juntos\n\n---\n\n**Descoberta crítica - Período pré-relacionamento:**\n- Dataset contém **2 períodos:** Amizade (2.8%, 57 dias) + Relacionamento (97.2%, 309 dias)\n- Média de comunicação **6.4x diferente** (45 vs 290 msgs/dia)\n- ⚠️ Misturar = viés em análises temporais/interação\n\n**Validação \"Nunca Ficaram Sem Falar\":**\n- 309 dias de relacionamento\n- 301 dias COM mensagem (97.4%)\n- 8 dias SEM mensagem (2.6%)\n- ✅ **100% dos dias sem mensagem = Durante encontros!**\n- ✅ **ZERO dias sem falar quando separados**\n\n---\n\n**Decisão metodológica - Marcação de períodos:**\n- ✅ Feature `fase_relacionamento` adicionada (Amizade | Relacionamento)\n- ✅ **Dataset COMPLETO exportado** (91.924 mensagens, todo período)\n- ✅ Notebooks individuais decidem se filtram ou não\n\n**Dataset exportado:**\n- 📁 Arquivo: `messages_with_context.parquet`\n- 📊 Mensagens: **91.924** (período completo)\n- 📅 Período: 19/out/2024 → 20/out/2025 (367 dias)\n- 🏷️ Features contextuais: 11 (em_encontro, fase_relacionamento, dias_desde/ate, marcos, etc.)\n\n---\n\n**Padrão identificado - DOIS PROTOCOLOS DE COMUNICAÇÃO:**\n\n| Aspecto | SEPARADOS (Conexão) | JUNTOS (Coordenação) |\n|---------|---------------------|----------------------|\n| **Volume** | 372 msgs/dia (ALTO) | 118 msgs/dia (-68%) |\n| **Timing** | Noturno (19h pico) | Diurno (12h pico) |\n| **Semanal** | Uniforme (todos iguais) | Segunda ALTA, fim de semana BAIXO |\n| **Função** | Canal PRINCIPAL | Canal SECUNDÁRIO |\n| **Comportamento** | Conversas longas, emocionais | Coordenação curta, prática |\n\n---\n\n**Estratégia de uso por notebook:**\n\n**Notebooks que FILTRARÃO para relacionamento:**\n- 📊 05.1-eda-temporal.qmd (padrões horários, evolução temporal - precisa pureza)\n- 💬 05.2-eda-interacao.qmd (turnos, sequências - precisa consistência)\n\n**Notebooks que USARÃO dataset completo:**\n- 📋 03-eda-overview.qmd (pode decidir por seção - volume filtra, tipos usa tudo)\n- 📝 06-eda-conteudo.qmd (estilo é estável, quer comparar amizade vs relacionamento)\n\n**Vantagens da estratégia:**\n- ✅ Flexibilidade total (cada notebook decide)\n- ✅ Sem perda irreversível de dados\n- ✅ Permite comparações amizade vs relacionamento\n- ✅ Análise de conteúdo completa\n\n---\n\n**Implicação para análises seguintes:**\n> `em_encontro` é um **SWITCH de protocolo** que muda volume, timing, frequência e função. `fase_relacionamento` permite separar dinâmicas de amizade vs relacionamento. Modelos que ignoram contexto externo perdem 68% da variância.\n\n**Próximos notebooks:**\n- Carregarão `messages_with_context.parquet` (**COMPLETO**, 91.924 msgs)\n- Decidirão individualmente se filtram para relacionamento\n- Trabalharão com dados **enriquecidos, validados e flexíveis**\n\n✅ **Dataset completo, enriquecido e pronto para EDA!**\n:::\n\n\n---\n\n\n# PRINCIPAIS DESCOBERTAS - Em Português Claro 🎯\n\n1. Quando estão juntos fisicamente:\n\nVolume de mensagens CAI 68% (372 → 118 msgs/dia)\nMudam horário: param de falar à NOITE (19h) e passam para MEIO-DIA (12h)\nSegunda explode (26.8%), fim de semana some (3-7%)\nWhatsApp vira só coordenação (\"onde vamos almoçar?\")\n\n2. Quando estão separados:\n\n372 msgs/dia (falam o dia TODO)\nPico NOTURNO (19h - contam sobre o dia)\nTodos os dias iguais (não muda fim de semana)\nWhatsApp = canal PRINCIPAL do relacionamento\n\n3. Gaps no WhatsApp:\n\n93% coincidem com encontros presenciais\nTimeline de mensagens = proxy perfeito de distância física\n\n4. Nunca ficaram sem falar:\n\n309 dias de relacionamento\nZERO dias sem mensagem quando separados\n8 dias sem msg = 100% durante encontros\n\n5. Antes do relacionamento:\n\nAmizade: 45 msgs/dia\nRelacionamento: 290 msgs/dia\n6.4x MAIS comunicação após ficarem juntos\n\n\nTL;DR:\n>\n> - Presença física = -68% mensagens.\n> - WhatsApp quando separados = conexão emocional noturna.\n> - WhatsApp quando juntos = coordenação diurna.\n> - Nunca ficaram sem falar quando longe. 🔥\n>\n\n",
    "supporting": [
      "03-contexto-externo_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n<script>\nwindow.PlotlyConfig = {MathJaxConfig: 'local'};\nif (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n</script>\n<script type=\"module\">import \"https://cdn.plot.ly/plotly-3.5.0.min\"</script>\n\n"
      ]
    }
  }
}