{
  "hash": "7da775468ca0a0d1b0c66269adbf93c5",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Análise Exploratória Completa (EDA)\"\nsubtitle: \"Volume, tipos, contexto e sentimento integrados\"\nauthor: \"Marlon\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    theme: cosmo\n    code-fold: show\n    code-tools: true\nexecute:\n  warning: false\n  echo: true\n  freeze: true\n---\n\n# Introdução\n\nEste notebook apresenta a **visão geral do dataset** com contexto externo integrado.\n\nO dataset foi enriquecido com informações de encontros presenciais, permitindo análises que consideram a diferença entre comunicação quando **juntos** vs **separados**.\n\n**Objetivo:** Visão panorâmica descritiva do dataset completo.\n\n**Estrutura:**\n- Estatísticas gerais\n- Volume diário (com contexto)\n- Distribuição por remetente\n- Tipos de mensagem\n- Análise de sentimento (DistilBERT vs RoBERTa)\n\n------------------------------------------------------------------------\n\n# Setup\n\n## Bibliotecas\n\n::: {#dfe3a8e3 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport plotly.express as px\nimport plotly.graph_objects as go\nfrom plotly.subplots import make_subplots\nfrom pathlib import Path\nimport warnings\n\nwarnings.filterwarnings('ignore')\n\n# Configurações de visualização\npd.set_option('display.max_columns', None)\npd.set_option('display.max_rows', 100)\n```\n:::\n\n\n## Caminhos\n\n::: {#e3625695 .cell execution_count=2}\n``` {.python .cell-code}\n# Estrutura de diretórios\nPROJECT_ROOT = Path.home() / 'Desktop' / 'whatsapp-interaction-analysis'\nDATA_DIR = PROJECT_ROOT / 'data' / 'processed' / 'export_2024-10_2025-10'\n\n# Arquivo de entrada (COM CONTEXTO INTEGRADO - do notebook 02)\nINPUT_FILE = DATA_DIR / 'messages_with_context.parquet'\n\n# Cores padronizadas\nCOLORS = {\n    'P1': '#636EFA',\n    'P2': '#EF553B',\n    'separados': '#636EFA',\n    'juntos': '#00CC96',\n    'TEXT': '#636EFA',\n    'AUDIO': '#EF553B',\n    'VID': '#00CC96',\n    'IMG': '#AB63FA'\n}\n\nprint(f\"📁 Diretório de dados: {DATA_DIR}\")\nprint(f\"📂 Arquivo de entrada: {INPUT_FILE.name}\")\nprint(f\"✅ Arquivo existe: {INPUT_FILE.exists()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📁 Diretório de dados: /Users/mosx/Desktop/whatsapp-interaction-analysis/data/processed/export_2024-10_2025-10\n📂 Arquivo de entrada: messages_with_context.parquet\n✅ Arquivo existe: True\n```\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Carregamento dos Dados\n\n::: {#82af6af2 .cell execution_count=3}\n``` {.python .cell-code}\n# Carrega dataset do wrangling\ndf = pd.read_parquet(INPUT_FILE)\n\nprint(f\"📊 Shape: {df.shape}\")\nprint(f\"📅 Período: {df['timestamp'].min().date()} → {df['timestamp'].max().date()}\")\nprint(f\"👥 Remetentes: {df['remetente'].unique().tolist()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📊 Shape: (91924, 15)\n📅 Período: 2024-10-19 → 2025-10-20\n👥 Remetentes: ['P1', 'P2']\n```\n:::\n:::\n\n\n## Estrutura do Dataset\n\n::: {#f09787c8 .cell execution_count=4}\n``` {.python .cell-code}\n# Exibe informações sobre as colunas\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.DataFrame'>\nRangeIndex: 91924 entries, 0 to 91923\nData columns (total 15 columns):\n #   Column                      Non-Null Count  Dtype         \n---  ------                      --------------  -----         \n 0   timestamp                   91924 non-null  datetime64[us]\n 1   remetente                   91924 non-null  category      \n 2   tipo_mensagem               91924 non-null  category      \n 3   grupo_mensagem              91924 non-null  category      \n 4   conteudo                    68686 non-null  str           \n 5   arquivo                     1254 non-null   str           \n 6   transcricao                 91924 non-null  bool          \n 7   date_match                  91924 non-null  bool          \n 8   em_encontro                 91924 non-null  bool          \n 9   encontro_id                 13432 non-null  float64       \n 10  encontro_nome               13432 non-null  str           \n 11  dias_desde_ultimo_encontro  76042 non-null  float64       \n 12  dias_ate_proximo_encontro   78464 non-null  float64       \n 13  dia_semana_num              91924 non-null  int32         \n 14  fase_relacionamento         91924 non-null  str           \ndtypes: bool(3), category(3), datetime64[us](1), float64(3), int32(1), str(4)\nmemory usage: 9.8 MB\n```\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Preview dos Dados\n\n::: {#compute-preview-stats .cell execution_count=5}\n``` {.python .cell-code}\n# Estatísticas para o preview e insights\ntotal_msgs = len(df)\n\n# Período\nperiodo_inicio = df['timestamp'].min()\nperiodo_fim = df['timestamp'].max()\ndias_total = (periodo_fim - periodo_inicio).days\nmsgs_por_dia_media = total_msgs / dias_total if dias_total > 0 else 0\n\n# Participantes\nparticipantes = None\np1_count = 0\np2_count = 0\np1_pct = 0\np2_pct = 0\nmais_ativo = 'N/A'\nmais_ativo_pct = 0\n\nif 'remetente' in df.columns:\n    participantes = df['remetente'].value_counts()\n    p1_count = participantes.iloc[0] if len(participantes) > 0 else 0\n    p2_count = participantes.iloc[1] if len(participantes) > 1 else 0\n    p1_name = participantes.index[0] if len(participantes) > 0 else 'P1'\n    p2_name = participantes.index[1] if len(participantes) > 1 else 'P2'\n    p1_pct = (p1_count / total_msgs * 100) if total_msgs > 0 else 0\n    p2_pct = (p2_count / total_msgs * 100) if total_msgs > 0 else 0\n    mais_ativo = p1_name if p1_count > p2_count else p2_name\n    mais_ativo_pct = max(p1_pct, p2_pct)\n\n# Tipo mais comum\ntipo_mais_comum = 0\ntipo_nome = 'N/A'\ntipo_pct = 0\n\nif 'tipo_mensagem' in df.columns:\n    tipo_mais_comum = df['tipo_mensagem'].value_counts().iloc[0]\n    tipo_nome = df['tipo_mensagem'].value_counts().index[0]\n    tipo_pct = (tipo_mais_comum / total_msgs * 100)\n\n# Transcrições\ncom_transcricao = 0\ntaxa_transcricao = 0\nif 'tem_transcricao' in df.columns:\n    com_transcricao = df['tem_transcricao'].sum()\n    taxa_transcricao = (com_transcricao / total_msgs * 100) if total_msgs > 0 else 0\n```\n:::\n\n\n**Resumo do dataset:**\n\n-   📊 Total: 91\\,924 mensagens\n-   📅 Período: 19/10/2024 até 20/10/2025 (366 dias)\n-   📋 Colunas: 15\n-   📈 Volume médio: 251\\.2 mensagens/dia\n-   💬 Tipo predominante: text\\_pure (68\\.4% das mensagens)\n-   🎙️ Taxa de transcrição: 0\\.00% (0 de 91\\,924)\n\n**Primeiras mensagens:**\n\n::: {#cell-preview-data .cell execution_count=6}\n``` {.python .cell-code}\n# Seleciona colunas para preview\npreview_cols = ['timestamp', 'remetente', 'tipo_mensagem']\nif 'conteudo_enriquecido' in df.columns:\n    preview_cols.append('conteudo_enriquecido')\nelif 'conteudo' in df.columns:\n    preview_cols.append('conteudo')\n\ndf[preview_cols].head(10)\n```\n\n::: {#preview-data .cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>timestamp</th>\n      <th>remetente</th>\n      <th>tipo_mensagem</th>\n      <th>conteudo</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2024-10-19 13:52:51</td>\n      <td>P1</td>\n      <td>text_pure</td>\n      <td>Le?</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2024-10-19 13:53:25</td>\n      <td>P2</td>\n      <td>text_with_link</td>\n      <td>https://www.localiza.com/brasil/pt-br/reservas...</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2024-10-19 13:53:25</td>\n      <td>P1</td>\n      <td>image_omitted</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2024-10-19 13:53:41</td>\n      <td>P2</td>\n      <td>sticker_omitted</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2024-10-19 13:53:43</td>\n      <td>P2</td>\n      <td>text_pure</td>\n      <td>Oi</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>2024-10-19 13:54:34</td>\n      <td>P1</td>\n      <td>image_omitted</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>2024-10-19 13:56:05</td>\n      <td>P1</td>\n      <td>image_omitted</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>2024-10-19 13:56:37</td>\n      <td>P2</td>\n      <td>text_pure</td>\n      <td>Arrasou</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>2024-10-19 13:56:49</td>\n      <td>P2</td>\n      <td>text_pure</td>\n      <td>confortável</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>2024-10-19 13:56:59</td>\n      <td>P2</td>\n      <td>text_pure</td>\n      <td>esse vai de boas</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#compute-transcribed .cell execution_count=7}\n``` {.python .cell-code}\ndf_trans = None\ntrans_count = 0\nif 'tem_transcricao' in df.columns:\n    df_trans = df[df['tem_transcricao'] == True]\n    trans_count = len(df_trans)\n```\n:::\n\n\n\n\n\n\n### Distribuição por Participante\n\n::: {#cell-show-participant-insights .cell execution_count=10}\n\n::: {#show-participant-insights .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_e9859\">\n  <thead>\n    <tr>\n      <th id=\"T_e9859_level0_col0\" class=\"col_heading level0 col0\" >Participante</th>\n      <th id=\"T_e9859_level0_col1\" class=\"col_heading level0 col1\" >Mensagens</th>\n      <th id=\"T_e9859_level0_col2\" class=\"col_heading level0 col2\" >%</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_e9859_row0_col0\" class=\"data row0 col0\" >P1</td>\n      <td id=\"T_e9859_row0_col1\" class=\"data row0 col1\" >46,948</td>\n      <td id=\"T_e9859_row0_col2\" class=\"data row0 col2\" >51.1%</td>\n    </tr>\n    <tr>\n      <td id=\"T_e9859_row1_col0\" class=\"data row1 col0\" >P2</td>\n      <td id=\"T_e9859_row1_col1\" class=\"data row1 col1\" >44,976</td>\n      <td id=\"T_e9859_row1_col2\" class=\"data row1 col2\" >48.9%</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n👤 **Mais ativo:** P1 (51\\.1% das mensagens)\n\n## Estatísticas Descritivas\n\n::: {#db000f5f .cell execution_count=11}\n``` {.python .cell-code}\n# Resumo estatístico\ndf.describe(include='all')\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>timestamp</th>\n      <th>remetente</th>\n      <th>tipo_mensagem</th>\n      <th>grupo_mensagem</th>\n      <th>conteudo</th>\n      <th>arquivo</th>\n      <th>transcricao</th>\n      <th>date_match</th>\n      <th>em_encontro</th>\n      <th>encontro_id</th>\n      <th>encontro_nome</th>\n      <th>dias_desde_ultimo_encontro</th>\n      <th>dias_ate_proximo_encontro</th>\n      <th>dia_semana_num</th>\n      <th>fase_relacionamento</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>91924</td>\n      <td>91924</td>\n      <td>91924</td>\n      <td>91924</td>\n      <td>68686</td>\n      <td>1254</td>\n      <td>91924</td>\n      <td>91924</td>\n      <td>91924</td>\n      <td>13432.000000</td>\n      <td>13432</td>\n      <td>76042.000000</td>\n      <td>78464.000000</td>\n      <td>91924.000000</td>\n      <td>91924</td>\n    </tr>\n    <tr>\n      <th>unique</th>\n      <td>NaN</td>\n      <td>2</td>\n      <td>21</td>\n      <td>11</td>\n      <td>41666</td>\n      <td>1254</td>\n      <td>2</td>\n      <td>2</td>\n      <td>2</td>\n      <td>NaN</td>\n      <td>8</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>top</th>\n      <td>NaN</td>\n      <td>P1</td>\n      <td>text_pure</td>\n      <td>TEXT</td>\n      <td>Sim</td>\n      <td>-0082879-Blip ViraTexto.vcf</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>NaN</td>\n      <td>BSB (2 meses!)</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>Relacionamento</td>\n    </tr>\n    <tr>\n      <th>freq</th>\n      <td>NaN</td>\n      <td>46948</td>\n      <td>62885</td>\n      <td>67297</td>\n      <td>394</td>\n      <td>1</td>\n      <td>91229</td>\n      <td>91645</td>\n      <td>78492</td>\n      <td>NaN</td>\n      <td>5208</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>89336</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>2025-05-16 17:51:51.580436</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>5.617406</td>\n      <td>NaN</td>\n      <td>20.943821</td>\n      <td>18.032257</td>\n      <td>2.938884</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>2024-10-19 13:52:51</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>1.000000</td>\n      <td>NaN</td>\n      <td>1.000000</td>\n      <td>1.000000</td>\n      <td>0.000000</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>2025-02-24 17:35:35.500000</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>4.000000</td>\n      <td>NaN</td>\n      <td>8.000000</td>\n      <td>7.000000</td>\n      <td>1.000000</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>2025-06-15 12:34:06.500000</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>7.000000</td>\n      <td>NaN</td>\n      <td>18.000000</td>\n      <td>16.000000</td>\n      <td>3.000000</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>2025-07-21 08:52:56</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>8.000000</td>\n      <td>NaN</td>\n      <td>30.000000</td>\n      <td>26.000000</td>\n      <td>5.000000</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>2025-10-20 15:25:49</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>8.000000</td>\n      <td>NaN</td>\n      <td>57.000000</td>\n      <td>57.000000</td>\n      <td>6.000000</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>2.523995</td>\n      <td>NaN</td>\n      <td>15.501643</td>\n      <td>13.134340</td>\n      <td>2.003681</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-warning}\n### 💡 Observação\n68.686 mensagens têm conteúdo textual (74.7%), o resto são mídias sem transcrição. Isso indica que análises de texto serão aplicáveis à maioria dos dados.\n:::\n\n------------------------------------------------------------------------\n\n# Visão Geral — Análise de Volume\n\n## Volume de Mensagens\n\n::: {#0f4ce802 .cell execution_count=12}\n``` {.python .cell-code}\n# Total de mensagens\ntotal_msgs = len(df)\nprint(f\"📊 Total de mensagens: {total_msgs:,}\")\n\n# Por fase\nprint(f\"\\n📊 Por fase do relacionamento:\")\nmsgs_por_fase = df['fase_relacionamento'].value_counts()\nfor fase, count in msgs_por_fase.items():\n    pct = (count / total_msgs) * 100\n    print(f\"   {fase}: {count:,} ({pct:.1f}%)\")\n\n# Por remetente\nprint(f\"\\n👥 Por remetente:\")\nmsgs_por_remetente = df['remetente'].value_counts()\nfor remetente, count in msgs_por_remetente.items():\n    pct = (count / total_msgs) * 100\n    print(f\"   {remetente}: {count:,} ({pct:.1f}%)\")\n\n# Por contexto\nprint(f\"\\n🏷️ Por contexto:\")\nmsgs_por_contexto = df['em_encontro'].value_counts()\nprint(f\"   Separados: {msgs_por_contexto[False]:,} ({msgs_por_contexto[False]/total_msgs*100:.1f}%)\")\nprint(f\"   Juntos: {msgs_por_contexto[True]:,} ({msgs_por_contexto[True]/total_msgs*100:.1f}%)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📊 Total de mensagens: 91,924\n\n📊 Por fase do relacionamento:\n   Relacionamento: 89,336 (97.2%)\n   Amizade: 2,588 (2.8%)\n\n👥 Por remetente:\n   P1: 46,948 (51.1%)\n   P2: 44,976 (48.9%)\n\n🏷️ Por contexto:\n   Separados: 78,492 (85.4%)\n   Juntos: 13,432 (14.6%)\n```\n:::\n:::\n\n\n## Distribuição por Remetente\n\n::: {#cell-fig-msgs-remetente .cell execution_count=13}\n``` {.python .cell-code}\n# Visualização\nfig = px.bar(\n    x=msgs_por_remetente.index,\n    y=msgs_por_remetente.values,\n    labels={'x': 'Remetente', 'y': 'Quantidade de Mensagens'},\n    title='Volume de Mensagens por Remetente',\n    color=msgs_por_remetente.index,\n    color_discrete_map={'P1': COLORS['P1'], 'P2': COLORS['P2']},\n    text=msgs_por_remetente.values\n)\n\nfig.update_traces(texttemplate='%{text:,}', textposition='outside')\nfig.update_layout(showlegend=False, height=400)\nfig.show()\n```\n\n::: {#fig-msgs-remetente .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"0bafd0d2-c1ec-49ef-a5ec-b52018206ad6\" class=\"plotly-graph-div\" style=\"height:400px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"0bafd0d2-c1ec-49ef-a5ec-b52018206ad6\")) {                    Plotly.newPlot(                        \"0bafd0d2-c1ec-49ef-a5ec-b52018206ad6\",                        [{\"hovertemplate\":\"color=P1\\u003cbr\\u003eRemetente=%{x}\\u003cbr\\u003eQuantidade de Mensagens=%{y}\\u003cbr\\u003etext=%{text}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"P1\",\"marker\":{\"color\":\"#636EFA\",\"pattern\":{\"shape\":\"\"}},\"name\":\"P1\",\"orientation\":\"v\",\"showlegend\":true,\"text\":{\"dtype\":\"f8\",\"bdata\":\"AAAAAIDs5kA=\"},\"textposition\":\"outside\",\"x\":[\"P1\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"i4\",\"bdata\":\"ZLcAAA==\"},\"yaxis\":\"y\",\"type\":\"bar\",\"texttemplate\":\"%{text:,}\"},{\"hovertemplate\":\"color=P2\\u003cbr\\u003eRemetente=%{x}\\u003cbr\\u003eQuantidade de Mensagens=%{y}\\u003cbr\\u003etext=%{text}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"P2\",\"marker\":{\"color\":\"#EF553B\",\"pattern\":{\"shape\":\"\"}},\"name\":\"P2\",\"orientation\":\"v\",\"showlegend\":true,\"text\":{\"dtype\":\"f8\",\"bdata\":\"AAAAAAD25UA=\"},\"textposition\":\"outside\",\"x\":[\"P2\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"i4\",\"bdata\":\"sK8AAA==\"},\"yaxis\":\"y\",\"type\":\"bar\",\"texttemplate\":\"%{text:,}\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Remetente\"}},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Quantidade de Mensagens\"}},\"legend\":{\"title\":{\"text\":\"color\"},\"tracegroupgap\":0},\"title\":{\"text\":\"Volume de Mensagens por Remetente\"},\"barmode\":\"relative\",\"showlegend\":false,\"height\":400},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('0bafd0d2-c1ec-49ef-a5ec-b52018206ad6');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nDistribuição de mensagens por remetente\n:::\n:::\n\n\n::: {.callout-note}\n### 💡 Insight - Visão Geral do Dataset\n\n**Período completo:** 367 dias (Out/2024 - Out/2025)\n\n**Composição:**\n- **97.2% Relacionamento** (89.336 msgs) vs 2.8% Amizade\n- **85.4% Separados** (78.492 msgs) vs 14.6% Juntos (13.432 msgs)\n- **51.1% P1** vs 48.9% P2 (quase simétrico)\n\n**Descobertas:**\n\n1. **Relacionamento domina:** Apenas 2.8% são de amizade - período pré-16/dez é marginal\n\n2. **Comunicação é majoritariamente à distância:** 85.4% das mensagens acontecem quando separados, mesmo estando juntos 33% do tempo (122 dias)\n\n3. **Simetria P1 × P2:** Diferença de apenas 2.2pp - participação equilibrada, baixo poder discriminatório para modelos\n:::\n\n## Volume Diário - Série Temporal\n\n::: {#cell-fig-volume-diario .cell execution_count=14}\n``` {.python .cell-code}\n# Agrega por dia\nmsgs_por_dia = df.groupby(df['timestamp'].dt.date).size().reset_index(name='count')\nmsgs_por_dia.columns = ['data', 'mensagens']\n\n# Visualização\nfig = px.line(\n    msgs_por_dia,\n    x='data',\n    y='mensagens',\n    title='Volume Diário de Mensagens',\n    labels={'data': 'Data', 'mensagens': 'Mensagens'}\n)\n\nfig.update_layout(height=400, hovermode='x')\nfig.show()\n\n# Estatísticas\nprint(f\"\\n📊 Estatísticas do volume diário:\")\nprint(f\"   Média: {msgs_por_dia['mensagens'].mean():.1f} msgs/dia\")\nprint(f\"   Mediana: {msgs_por_dia['mensagens'].median():.0f} msgs/dia\")\nprint(f\"   Máximo: {msgs_por_dia['mensagens'].max():,} msgs/dia\")\nprint(f\"   Mínimo: {msgs_por_dia['mensagens'].min()} msgs/dia\")\n```\n\n::: {#fig-volume-diario .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"2e59f215-20f2-4005-b7af-3661d0041029\" class=\"plotly-graph-div\" style=\"height:400px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"2e59f215-20f2-4005-b7af-3661d0041029\")) {                    Plotly.newPlot(                        \"2e59f215-20f2-4005-b7af-3661d0041029\",                        [{\"hovertemplate\":\"Data=%{x}\\u003cbr\\u003eMensagens=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"\",\"line\":{\"color\":\"#636efa\",\"dash\":\"solid\"},\"marker\":{\"symbol\":\"circle\"},\"mode\":\"lines\",\"name\":\"\",\"orientation\":\"v\",\"showlegend\":false,\"x\":[\"2024-10-19\",\"2024-10-23\",\"2024-10-24\",\"2024-11-21\",\"2024-11-22\",\"2024-11-23\",\"2024-11-26\",\"2024-11-27\",\"2024-11-28\",\"2024-11-29\",\"2024-11-30\",\"2024-12-02\",\"2024-12-03\",\"2024-12-04\",\"2024-12-05\",\"2024-12-06\",\"2024-12-08\",\"2024-12-09\",\"2024-12-10\",\"2024-12-11\",\"2024-12-12\",\"2024-12-13\",\"2024-12-14\",\"2024-12-15\",\"2024-12-16\",\"2024-12-17\",\"2024-12-18\",\"2024-12-19\",\"2024-12-20\",\"2024-12-21\",\"2024-12-22\",\"2024-12-23\",\"2024-12-24\",\"2024-12-25\",\"2024-12-26\",\"2024-12-27\",\"2024-12-28\",\"2024-12-29\",\"2024-12-30\",\"2024-12-31\",\"2025-01-01\",\"2025-01-02\",\"2025-01-03\",\"2025-01-04\",\"2025-01-05\",\"2025-01-06\",\"2025-01-07\",\"2025-01-08\",\"2025-01-09\",\"2025-01-10\",\"2025-01-11\",\"2025-01-12\",\"2025-01-13\",\"2025-01-14\",\"2025-01-15\",\"2025-01-16\",\"2025-01-17\",\"2025-01-18\",\"2025-01-19\",\"2025-01-20\",\"2025-01-21\",\"2025-01-22\",\"2025-01-23\",\"2025-01-24\",\"2025-01-25\",\"2025-01-26\",\"2025-01-27\",\"2025-01-28\",\"2025-01-29\",\"2025-01-30\",\"2025-01-31\",\"2025-02-01\",\"2025-02-02\",\"2025-02-03\",\"2025-02-04\",\"2025-02-05\",\"2025-02-06\",\"2025-02-07\",\"2025-02-08\",\"2025-02-09\",\"2025-02-10\",\"2025-02-11\",\"2025-02-12\",\"2025-02-13\",\"2025-02-14\",\"2025-02-15\",\"2025-02-16\",\"2025-02-17\",\"2025-02-18\",\"2025-02-19\",\"2025-02-20\",\"2025-02-21\",\"2025-02-22\",\"2025-02-23\",\"2025-02-24\",\"2025-02-25\",\"2025-02-26\",\"2025-02-27\",\"2025-02-28\",\"2025-03-01\",\"2025-03-02\",\"2025-03-03\",\"2025-03-04\",\"2025-03-05\",\"2025-03-06\",\"2025-03-07\",\"2025-03-08\",\"2025-03-09\",\"2025-03-10\",\"2025-03-11\",\"2025-03-12\",\"2025-03-13\",\"2025-03-14\",\"2025-03-15\",\"2025-03-16\",\"2025-03-17\",\"2025-03-18\",\"2025-03-19\",\"2025-03-20\",\"2025-03-21\",\"2025-03-22\",\"2025-03-23\",\"2025-03-24\",\"2025-03-25\",\"2025-03-26\",\"2025-03-27\",\"2025-03-28\",\"2025-03-29\",\"2025-03-30\",\"2025-03-31\",\"2025-04-01\",\"2025-04-02\",\"2025-04-03\",\"2025-04-04\",\"2025-04-05\",\"2025-04-06\",\"2025-04-07\",\"2025-04-08\",\"2025-04-09\",\"2025-04-10\",\"2025-04-11\",\"2025-04-12\",\"2025-04-13\",\"2025-04-14\",\"2025-04-15\",\"2025-04-16\",\"2025-04-17\",\"2025-04-19\",\"2025-04-20\",\"2025-04-21\",\"2025-04-22\",\"2025-04-23\",\"2025-04-24\",\"2025-04-25\",\"2025-04-27\",\"2025-04-28\",\"2025-04-29\",\"2025-04-30\",\"2025-05-01\",\"2025-05-02\",\"2025-05-03\",\"2025-05-04\",\"2025-05-05\",\"2025-05-06\",\"2025-05-07\",\"2025-05-08\",\"2025-05-09\",\"2025-05-10\",\"2025-05-11\",\"2025-05-12\",\"2025-05-13\",\"2025-05-14\",\"2025-05-15\",\"2025-05-16\",\"2025-05-17\",\"2025-05-18\",\"2025-05-19\",\"2025-05-21\",\"2025-05-22\",\"2025-05-23\",\"2025-05-24\",\"2025-05-25\",\"2025-05-26\",\"2025-05-27\",\"2025-05-28\",\"2025-05-29\",\"2025-05-30\",\"2025-05-31\",\"2025-06-01\",\"2025-06-02\",\"2025-06-03\",\"2025-06-04\",\"2025-06-05\",\"2025-06-06\",\"2025-06-07\",\"2025-06-08\",\"2025-06-09\",\"2025-06-10\",\"2025-06-11\",\"2025-06-12\",\"2025-06-13\",\"2025-06-14\",\"2025-06-15\",\"2025-06-16\",\"2025-06-17\",\"2025-06-18\",\"2025-06-19\",\"2025-06-20\",\"2025-06-21\",\"2025-06-22\",\"2025-06-23\",\"2025-06-24\",\"2025-06-25\",\"2025-06-26\",\"2025-06-27\",\"2025-06-28\",\"2025-06-29\",\"2025-06-30\",\"2025-07-01\",\"2025-07-02\",\"2025-07-03\",\"2025-07-04\",\"2025-07-05\",\"2025-07-06\",\"2025-07-07\",\"2025-07-08\",\"2025-07-09\",\"2025-07-10\",\"2025-07-11\",\"2025-07-12\",\"2025-07-13\",\"2025-07-14\",\"2025-07-15\",\"2025-07-16\",\"2025-07-17\",\"2025-07-18\",\"2025-07-19\",\"2025-07-20\",\"2025-07-21\",\"2025-07-22\",\"2025-07-23\",\"2025-07-24\",\"2025-07-25\",\"2025-07-26\",\"2025-07-27\",\"2025-07-28\",\"2025-07-29\",\"2025-07-30\",\"2025-07-31\",\"2025-08-01\",\"2025-08-02\",\"2025-08-03\",\"2025-08-04\",\"2025-08-05\",\"2025-08-06\",\"2025-08-07\",\"2025-08-08\",\"2025-08-09\",\"2025-08-10\",\"2025-08-11\",\"2025-08-12\",\"2025-08-13\",\"2025-08-14\",\"2025-08-15\",\"2025-08-16\",\"2025-08-17\",\"2025-08-18\",\"2025-08-19\",\"2025-08-20\",\"2025-08-21\",\"2025-08-22\",\"2025-08-23\",\"2025-08-24\",\"2025-08-25\",\"2025-08-26\",\"2025-08-27\",\"2025-08-28\",\"2025-08-29\",\"2025-08-31\",\"2025-09-01\",\"2025-09-02\",\"2025-09-03\",\"2025-09-04\",\"2025-09-05\",\"2025-09-06\",\"2025-09-07\",\"2025-09-08\",\"2025-09-09\",\"2025-09-10\",\"2025-09-11\",\"2025-09-12\",\"2025-09-13\",\"2025-09-14\",\"2025-09-15\",\"2025-09-16\",\"2025-09-17\",\"2025-09-18\",\"2025-09-19\",\"2025-09-22\",\"2025-09-23\",\"2025-09-24\",\"2025-09-25\",\"2025-09-26\",\"2025-09-27\",\"2025-09-29\",\"2025-09-30\",\"2025-10-01\",\"2025-10-02\",\"2025-10-03\",\"2025-10-04\",\"2025-10-05\",\"2025-10-06\",\"2025-10-07\",\"2025-10-08\",\"2025-10-09\",\"2025-10-10\",\"2025-10-12\",\"2025-10-13\",\"2025-10-14\",\"2025-10-15\",\"2025-10-16\",\"2025-10-17\",\"2025-10-18\",\"2025-10-19\",\"2025-10-20\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"i2\",\"bdata\":\"HAAEACUACAAhAVsASABAAGUAFQFHAAsAqwCTADQA\\u002fQAmAH8A+ABpAW0AGAAEAAEACwBLAEkAcwCNAAcA7ADhAG8BDQNAAgcBjQHcAYYCbAKpAV0B3QL0AIgAZgFgATsBvQFYASQB4QBzAR4B1wDOAE0CpgGEAbYBzQCwAZUAhAADAMQAogDuAOQAmQDRAGYBZwHXAEMB7AEuAQgAEwBJAAsBuAHOATwB\\u002fgDnABABwACiALwAiAG1AHIBdwAaAW0BXAG0AQMAAwAYABIAJQAXAX0AMQABAAUA2gC+AewBhQHHALABmQGaALkBPAKGAeQAwQF1AMAA6gCeAHwA5gDjAM8ALQFwAW0AaQB1AFYBlAHIAMQAAQFfAJMAogCUABEBjQCqADEAAwAgAC8AiQBXAJoASgAXAGAALwA6AAEARQACAAEAOALwAVEAAQHWAJMAbwBzAL4A1wBgAS8BAgABAAIACQAOAAEAeAG2AO4A0AGcAMYCcgFwALIBsgCMAbAApgF8AgABsALEAEoBLgGyAHoAegFcAuACsAC+AaQBTgJ8AwgFgAGGARoCzAL4AtQCegEeARIC6gH6AeoChASuBKwBsAJ6AZ4CZgJyA+4DFgJQAjYECAJiAngBvAKuA54BogE0AAIACgAaADAA0gO2AYoBwAEoAQID7AFsAfgAagFEAlgBXAJSA\\u002fIBogFaAToCugJcBCoDVgPgAl4CZwAHAIkAWwDVAGYAkwAGAAcAeADzACYASwDWAAEAjQDcAGYAxwB\\u002fAMEAAwAMAH8AcAC4AIcADAB6AGoAogCeAE4AAQDPAKEAaABWAH8AAQBuAKIAkADYAHoARgBiAGkAkgBMAUoBJwFtASQBUwA=\"},\"yaxis\":\"y\",\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Data\"}},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Mensagens\"}},\"legend\":{\"tracegroupgap\":0},\"title\":{\"text\":\"Volume Di\\u00e1rio de Mensagens\"},\"height\":400,\"hovermode\":\"x\"},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('2e59f215-20f2-4005-b7af-3661d0041029');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nVolume de mensagens ao longo do tempo\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n📊 Estatísticas do volume diário:\n   Média: 282.8 msgs/dia\n   Mediana: 216 msgs/dia\n   Máximo: 1,288 msgs/dia\n   Mínimo: 1 msgs/dia\n```\n:::\n:::\n\n\n::: {.callout-note}\n### 💡 Insight - Volume Diário\n\n**Padrão identificado no gráfico:**\n\n1. **Vale em Setembro = Encontro de 2 meses** (BSB, Ago-Out/2025)\n   - Volume cai drasticamente (quase zero)\n   - Confirma visualmente: presença física = menos WhatsApp\n\n2. **Picos em Jun-Jul = Separação máxima**\n   - Máximo: **1.288 msgs/dia** (4.5x acima da média!)\n   - Período de maior distância temporal entre encontros\n\n3. **Crescimento Nov-Dez 2024 = Início do relacionamento**\n   - Volume cresce de ~200 para ~700 msgs/dia\n   - Marca transição amizade → relacionamento\n\n4. **Variabilidade extrema:**\n   - Amplitude: 1 a 1.288 msgs/dia (1.288x!)\n   - Média (283) > Mediana (216) = distribuição assimétrica\n   - Picos puxam média para cima\n\n**Conclusão:** Volume diário é **altamente variável** e modulado por contexto externo (encontros). Não há padrão temporal intrínseco - padrão é REATIVO à distância física.\n:::\n\n## Volume por Contexto\n\n::: {#cell-fig-volume-contexto .cell execution_count=15}\n``` {.python .cell-code}\n# Calcula médias por contexto\nvolume_contexto = df.groupby([df['timestamp'].dt.date, 'em_encontro']).size().reset_index(name='count')\nmedia_por_contexto = volume_contexto.groupby('em_encontro')['count'].agg(['mean', 'median', 'std']).round(1)\nmedia_por_contexto.index = ['Separados', 'Juntos']\n\nprint(f\"\\n📊 Volume por contexto:\")\nprint(media_por_contexto)\n\n# Visualização\nfig = px.bar(\n    x=['Separados', 'Juntos'],\n    y=[media_por_contexto.loc['Separados', 'mean'], media_por_contexto.loc['Juntos', 'mean']],\n    labels={'x': 'Contexto', 'y': 'Média de Mensagens/Dia'},\n    title='Volume Médio Diário: Junto vs Separado',\n    color=['Separados', 'Juntos'],\n    color_discrete_map={'Separados': COLORS['separados'], 'Juntos': COLORS['juntos']},\n    text=[f\"{media_por_contexto.loc['Separados', 'mean']:.0f}\",\n          f\"{media_por_contexto.loc['Juntos', 'mean']:.0f}\"]\n)\n\nfig.update_traces(textposition='outside')\nfig.update_layout(showlegend=False, height=400)\nfig.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n📊 Volume por contexto:\n            mean  median    std\nSeparados  372.0   346.0  243.7\nJuntos     117.8    99.0  134.7\n```\n:::\n\n::: {#fig-volume-contexto .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"c5649f63-6a0d-4d7f-bd86-6910cb2ffac8\" class=\"plotly-graph-div\" style=\"height:400px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"c5649f63-6a0d-4d7f-bd86-6910cb2ffac8\")) {                    Plotly.newPlot(                        \"c5649f63-6a0d-4d7f-bd86-6910cb2ffac8\",                        [{\"hovertemplate\":\"color=Separados\\u003cbr\\u003eContexto=%{x}\\u003cbr\\u003eM\\u00e9dia de Mensagens\\u002fDia=%{y}\\u003cbr\\u003etext=%{text}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"Separados\",\"marker\":{\"color\":\"#636EFA\",\"pattern\":{\"shape\":\"\"}},\"name\":\"Separados\",\"orientation\":\"v\",\"showlegend\":true,\"text\":[\"372\"],\"textposition\":\"outside\",\"x\":[\"Separados\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"AAAAAABAd0A=\"},\"yaxis\":\"y\",\"type\":\"bar\"},{\"hovertemplate\":\"color=Juntos\\u003cbr\\u003eContexto=%{x}\\u003cbr\\u003eM\\u00e9dia de Mensagens\\u002fDia=%{y}\\u003cbr\\u003etext=%{text}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"Juntos\",\"marker\":{\"color\":\"#00CC96\",\"pattern\":{\"shape\":\"\"}},\"name\":\"Juntos\",\"orientation\":\"v\",\"showlegend\":true,\"text\":[\"118\"],\"textposition\":\"outside\",\"x\":[\"Juntos\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"MzMzMzNzXUA=\"},\"yaxis\":\"y\",\"type\":\"bar\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Contexto\"}},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"M\\u00e9dia de Mensagens\\u002fDia\"}},\"legend\":{\"title\":{\"text\":\"color\"},\"tracegroupgap\":0},\"title\":{\"text\":\"Volume M\\u00e9dio Di\\u00e1rio: Junto vs Separado\"},\"barmode\":\"relative\",\"showlegend\":false,\"height\":400},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('c5649f63-6a0d-4d7f-bd86-6910cb2ffac8');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nVolume médio: junto vs separado\n:::\n:::\n\n\n::: {.callout-important}\n### 💡 Insight - Contexto Domina Volume\n\n**Diferença DRAMÁTICA:**\n- **Separados:** 372 msgs/dia (média)\n- **Juntos:** 118 msgs/dia (média)\n- **Redução:** -68.3% quando juntos\n\n**Validação do notebook 02:**\n- Confirma visualmente a queda de -68% (p<0.001)\n- Presença física = WhatsApp vira coordenação (não conexão)\n\n**Variabilidade:**\n- Separados: Desvio 244 (alta oscilação - saudade varia)\n- Juntos: Desvio 135 (menor oscilação - convívio estável)\n- Mediana separados (346) < Média (372) = picos de saudade puxam média\n\n**Conclusão:** `em_encontro` é a feature mais importante do dataset - explica 68% da variância no volume.\n:::\n\n---\n\n## Síntese - Volume de Mensagens\n\n::: {.callout-tip}\n### 🎯 Conclusão - Padrões de Volume\n\n**Dataset caracterizado por:**\n- 91.924 mensagens em 367 dias (Out/2024 - Out/2025)\n- Participação equilibrada: P1 (51.1%) vs P2 (48.9%)\n- Dominância do relacionamento: 97.2% das mensagens (pós 16/dez)\n\n**Descoberta CRÍTICA - Contexto domina tudo:**\n\n| Métrica | Separados | Juntos | Diferença |\n|---------|-----------|--------|-----------|\n| **Volume médio** | 372 msgs/dia | 118 msgs/dia | **-68.3%** 🔥 |\n| **Variabilidade** | Alta (σ=244) | Moderada (σ=135) | Mais estável juntos |\n| **% do tempo** | 66.8% | 33.2% | Paradoxo: juntos 1/3 do tempo, mas apenas 14.6% msgs |\n\n**Padrões temporais identificados:**\n- ✅ Crescimento Nov-Dez/2024 = Início relacionamento (200→700 msgs/dia)\n- ✅ Pico Jun-Jul/2025 = Separação máxima (1.288 msgs/dia)\n- ✅ Vale Ago-Set/2025 = Encontro 2 meses (volume quase zero)\n\n**Implicação para análises seguintes:**\n> Volume NÃO é temporal intrínseco - é **REATIVO** à distância física. Feature `em_encontro` explica 68% da variância. Modelos sem contexto externo terão poder limitado.\n:::\n\n-----------------------------------------------------------------\n\n# Distribuição de Tipos de Mensagem\n\n## Por Tipo Específico\n\n::: {#51eb3e46 .cell execution_count=16}\n``` {.python .cell-code}\n# Contagem por tipo específico\ntipo_counts = df['tipo_mensagem'].value_counts()\nprint(f\"📋 Tipos de mensagem identificados: {len(tipo_counts)}\")\nprint(f\"\\nTipos mais frequentes:\")\nprint(tipo_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📋 Tipos de mensagem identificados: 21\n\nTipos mais frequentes:\ntipo_mensagem\ntext_pure             62885\nvideo_note_omitted     9168\naudio_omitted          8040\ntext_with_emoji        3858\nimage_omitted          3287\nsticker_omitted        1869\nmessage_edited          658\ntext_with_link          554\naudio_attached          512\nimage_attached          298\nsticker_attached        248\nvideo_omitted           248\nvideo_attached          186\ndocument_omitted         38\ngif_omitted              28\nmessage_deleted          22\nmissed_call              11\ncontact_attached          9\nsystem_message            2\nvoice_call                2\nfile_attached             1\nName: count, dtype: int64\n```\n:::\n:::\n\n\n::: {#cell-fig-tipos-especificos .cell execution_count=17}\n``` {.python .cell-code}\n# Visualização - Top 10\ntop_10_tipos = tipo_counts\n\nfig = px.bar(\n    x=top_10_tipos.values,\n    y=top_10_tipos.index,\n    orientation='h',\n    labels={'x': 'Quantidade', 'y': 'Tipo de Mensagem'},\n    title='Top 10 Tipos de Mensagem',\n    text=top_10_tipos.values\n)\n\nfig.update_traces(texttemplate='%{text:,}', textposition='outside')\nfig.update_layout(height=500, yaxis={'categoryorder': 'total ascending'})\nfig.show()\n```\n\n::: {#fig-tipos-especificos .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"31ee58e7-1cc1-4b89-b5ae-919ca7b4f66b\" class=\"plotly-graph-div\" style=\"height:500px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"31ee58e7-1cc1-4b89-b5ae-919ca7b4f66b\")) {                    Plotly.newPlot(                        \"31ee58e7-1cc1-4b89-b5ae-919ca7b4f66b\",                        [{\"hovertemplate\":\"Quantidade=%{x}\\u003cbr\\u003eTipo de Mensagem=%{y}\\u003cbr\\u003etext=%{text}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"\",\"marker\":{\"color\":\"#636efa\",\"pattern\":{\"shape\":\"\"}},\"name\":\"\",\"orientation\":\"h\",\"showlegend\":false,\"text\":{\"dtype\":\"f8\",\"bdata\":\"AAAAAKC07kAAAAAAAOjBQAAAAAAAaL9AAAAAAAAkrkAAAAAAAK6pQAAAAAAANJ1AAAAAAACQhEAAAAAAAFCBQAAAAAAAAIBAAAAAAACgckAAAAAAAABvQAAAAAAAAG9AAAAAAABAZ0AAAAAAAABDQAAAAAAAADxAAAAAAAAANkAAAAAAAAAmQAAAAAAAACJAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAPA\\u002f\"},\"textposition\":\"outside\",\"x\":{\"dtype\":\"i4\",\"bdata\":\"pfUAANAjAABoHwAAEg8AANcMAABNBwAAkgIAACoCAAAAAgAAKgEAAPgAAAD4AAAAugAAACYAAAAcAAAAFgAAAAsAAAAJAAAAAgAAAAIAAAABAAAA\"},\"xaxis\":\"x\",\"y\":[\"text_pure\",\"video_note_omitted\",\"audio_omitted\",\"text_with_emoji\",\"image_omitted\",\"sticker_omitted\",\"message_edited\",\"text_with_link\",\"audio_attached\",\"image_attached\",\"sticker_attached\",\"video_omitted\",\"video_attached\",\"document_omitted\",\"gif_omitted\",\"message_deleted\",\"missed_call\",\"contact_attached\",\"system_message\",\"voice_call\",\"file_attached\"],\"yaxis\":\"y\",\"type\":\"bar\",\"texttemplate\":\"%{text:,}\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Quantidade\"}},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Tipo de Mensagem\"},\"categoryorder\":\"total ascending\"},\"legend\":{\"tracegroupgap\":0},\"title\":{\"text\":\"Top 10 Tipos de Mensagem\"},\"barmode\":\"relative\",\"height\":500},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('31ee58e7-1cc1-4b89-b5ae-919ca7b4f66b');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nTipos de mensagem mais frequentes\n:::\n:::\n\n\n---\n\n## Por Grupo (Categoria)\n\n::: {#21f8bb2c .cell execution_count=18}\n``` {.python .cell-code}\n# Contagem por grupo\ngrupo_counts = df['grupo_mensagem'].value_counts()\nprint(f\"📦 Grupos de mensagem: {len(grupo_counts)}\")\nprint(f\"\\nDistribuição por grupo:\")\nfor grupo, count in grupo_counts.items():\n    pct = (count / total_msgs) * 100\n    print(f\"   {grupo}: {count:,} ({pct:.1f}%)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📦 Grupos de mensagem: 11\n\nDistribuição por grupo:\n   TEXT: 67,297 (73.2%)\n   VID: 9,602 (10.4%)\n   AUDIO: 8,552 (9.3%)\n   IMG: 3,585 (3.9%)\n   STICKER: 2,117 (2.3%)\n   SYSTEM: 682 (0.7%)\n   DOC: 38 (0.0%)\n   GIF: 28 (0.0%)\n   CALL: 13 (0.0%)\n   CONTACT: 9 (0.0%)\n   FILE: 1 (0.0%)\n```\n:::\n:::\n\n\n::: {#cell-fig-grupos-mensagem .cell execution_count=19}\n``` {.python .cell-code}\n# Cores padronizadas por grupo\ncores_grupos = [COLORS.get(grupo, '#95a5a6') for grupo in grupo_counts.index]\n\nfig = px.pie(\n    names=grupo_counts.index,\n    values=grupo_counts.values,\n    title='Distribuição por Grupo de Mensagem',\n    color=grupo_counts.index,\n    color_discrete_map=COLORS,\n    hole=0.4\n)\n\nfig.update_traces(\n    textposition='inside',\n    textinfo='label+percent',\n    hovertemplate='<b>%{label}</b><br>Quantidade: %{value:,}<br>Percentual: %{percent}<extra></extra>'\n)\n\nfig.update_layout(height=500)\nfig.show()\n```\n\n::: {#fig-grupos-mensagem .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"944ae615-a83d-4b9f-8ba2-b1a67141e514\" class=\"plotly-graph-div\" style=\"height:500px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"944ae615-a83d-4b9f-8ba2-b1a67141e514\")) {                    Plotly.newPlot(                        \"944ae615-a83d-4b9f-8ba2-b1a67141e514\",                        [{\"customdata\":[[\"TEXT\"],[\"VID\"],[\"AUDIO\"],[\"IMG\"],[\"STICKER\"],[\"SYSTEM\"],[\"DOC\"],[\"GIF\"],[\"CALL\"],[\"CONTACT\"],[\"FILE\"]],\"domain\":{\"x\":[0.0,1.0],\"y\":[0.0,1.0]},\"hole\":0.4,\"hovertemplate\":\"\\u003cb\\u003e%{label}\\u003c\\u002fb\\u003e\\u003cbr\\u003eQuantidade: %{value:,}\\u003cbr\\u003ePercentual: %{percent}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"labels\":[\"TEXT\",\"VID\",\"AUDIO\",\"IMG\",\"STICKER\",\"SYSTEM\",\"DOC\",\"GIF\",\"CALL\",\"CONTACT\",\"FILE\"],\"legendgroup\":\"\",\"marker\":{\"colors\":[\"#636EFA\",\"#00CC96\",\"#EF553B\",\"#AB63FA\",\"#FF97FF\",\"#FECB52\",\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\"]},\"name\":\"\",\"showlegend\":true,\"values\":{\"dtype\":\"i4\",\"bdata\":\"4QYBAIIlAABoIQAAAQ4AAEUIAACqAgAAJgAAABwAAAANAAAACQAAAAEAAAA=\"},\"type\":\"pie\",\"textinfo\":\"label+percent\",\"textposition\":\"inside\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"legend\":{\"tracegroupgap\":0},\"title\":{\"text\":\"Distribui\\u00e7\\u00e3o por Grupo de Mensagem\"},\"height\":500},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('944ae615-a83d-4b9f-8ba2-b1a67141e514');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nDistribuição por grupo de mensagem\n:::\n:::\n\n\n---\n\n## Por Grupo × Remetente\n\n::: {#3e7540de .cell execution_count=20}\n``` {.python .cell-code}\n# Distribuição por grupo e remetente\ngrupo_remetente = df.groupby(['grupo_mensagem', 'remetente']).size().unstack(fill_value=0)\n\nprint(f\"📊 Distribuição por grupo e remetente:\\n\")\nprint(grupo_remetente)\n\n# Percentuais\ngrupo_remetente_pct = grupo_remetente.div(grupo_remetente.sum(axis=1), axis=0) * 100\nprint(f\"\\n📊 Percentuais (por grupo):\\n\")\nprint(grupo_remetente_pct.round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📊 Distribuição por grupo e remetente:\n\nremetente          P1     P2\ngrupo_mensagem              \nAUDIO            5334   3218\nCALL                0     13\nCONTACT             3      6\nDOC                24     14\nFILE                0      1\nGIF                10     18\nIMG              1965   1620\nSTICKER          1026   1091\nSYSTEM            422    260\nTEXT            33220  34077\nVID              4944   4658\n\n📊 Percentuais (por grupo):\n\nremetente         P1     P2\ngrupo_mensagem             \nAUDIO           62.4   37.6\nCALL             0.0  100.0\nCONTACT         33.3   66.7\nDOC             63.2   36.8\nFILE             0.0  100.0\nGIF             35.7   64.3\nIMG             54.8   45.2\nSTICKER         48.5   51.5\nSYSTEM          61.9   38.1\nTEXT            49.4   50.6\nVID             51.5   48.5\n```\n:::\n:::\n\n\n::: {#cell-fig-grupos-remetente .cell execution_count=21}\n``` {.python .cell-code}\n# Prepara dados\ndados_plot = grupo_remetente.reset_index().melt(\n    id_vars='grupo_mensagem',\n    var_name='remetente',\n    value_name='count'\n)\n\nfig = px.bar(\n    dados_plot,\n    x='grupo_mensagem',\n    y='count',\n    color='remetente',\n    barmode='group',\n    labels={'grupo_mensagem': 'Grupo', 'count': 'Quantidade', 'remetente': 'Remetente'},\n    title='Distribuição de Grupos por Remetente',\n    color_discrete_map={'P1': COLORS['P1'], 'P2': COLORS['P2']},\n    text='count'\n)\n\nfig.update_traces(texttemplate='%{text:,}', textposition='outside')\nfig.update_layout(height=400)\nfig.show()\n```\n\n::: {#fig-grupos-remetente .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"a3f03618-00a3-47cf-9a52-2431b05c5485\" class=\"plotly-graph-div\" style=\"height:400px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"a3f03618-00a3-47cf-9a52-2431b05c5485\")) {                    Plotly.newPlot(                        \"a3f03618-00a3-47cf-9a52-2431b05c5485\",                        [{\"alignmentgroup\":\"True\",\"hovertemplate\":\"Remetente=P1\\u003cbr\\u003eGrupo=%{x}\\u003cbr\\u003eQuantidade=%{text}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"P1\",\"marker\":{\"color\":\"#636EFA\",\"pattern\":{\"shape\":\"\"}},\"name\":\"P1\",\"offsetgroup\":\"P1\",\"orientation\":\"v\",\"showlegend\":true,\"text\":{\"dtype\":\"f8\",\"bdata\":\"AAAAAADWtEAAAAAAAAAAAAAAAAAAAAhAAAAAAAAAOEAAAAAAAAAAAAAAAAAAACRAAAAAAAC0nkAAAAAAAAiQQAAAAAAAYHpAAAAAAIA44EAAAAAAAFCzQA==\"},\"textposition\":\"outside\",\"x\":[\"AUDIO\",\"CALL\",\"CONTACT\",\"DOC\",\"FILE\",\"GIF\",\"IMG\",\"STICKER\",\"SYSTEM\",\"TEXT\",\"VID\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"i4\",\"bdata\":\"1hQAAAAAAAADAAAAGAAAAAAAAAAKAAAArQcAAAIEAACmAQAAxIEAAFATAAA=\"},\"yaxis\":\"y\",\"type\":\"bar\",\"texttemplate\":\"%{text:,}\"},{\"alignmentgroup\":\"True\",\"hovertemplate\":\"Remetente=P2\\u003cbr\\u003eGrupo=%{x}\\u003cbr\\u003eQuantidade=%{text}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"P2\",\"marker\":{\"color\":\"#EF553B\",\"pattern\":{\"shape\":\"\"}},\"name\":\"P2\",\"offsetgroup\":\"P2\",\"orientation\":\"v\",\"showlegend\":true,\"text\":{\"dtype\":\"f8\",\"bdata\":\"AAAAAAAkqUAAAAAAAAAqQAAAAAAAABhAAAAAAAAALEAAAAAAAADwPwAAAAAAADJAAAAAAABQmUAAAAAAAAyRQAAAAAAAQHBAAAAAAKCj4EAAAAAAADKyQA==\"},\"textposition\":\"outside\",\"x\":[\"AUDIO\",\"CALL\",\"CONTACT\",\"DOC\",\"FILE\",\"GIF\",\"IMG\",\"STICKER\",\"SYSTEM\",\"TEXT\",\"VID\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"i4\",\"bdata\":\"kgwAAA0AAAAGAAAADgAAAAEAAAASAAAAVAYAAEMEAAAEAQAAHYUAADISAAA=\"},\"yaxis\":\"y\",\"type\":\"bar\",\"texttemplate\":\"%{text:,}\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Grupo\"}},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Quantidade\"}},\"legend\":{\"title\":{\"text\":\"Remetente\"},\"tracegroupgap\":0},\"title\":{\"text\":\"Distribui\\u00e7\\u00e3o de Grupos por Remetente\"},\"barmode\":\"group\",\"height\":400},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('a3f03618-00a3-47cf-9a52-2431b05c5485');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nDistribuição de grupos por remetente\n:::\n:::\n\n\n---\n\n## Por Grupo × Contexto\n\n::: {#db055b63 .cell execution_count=22}\n``` {.python .cell-code}\n# Distribuição por grupo e contexto\ngrupo_contexto = df.groupby(['grupo_mensagem', 'em_encontro']).size().unstack(fill_value=0)\ngrupo_contexto.columns = ['Separados', 'Juntos']\n\nprint(f\"📊 Distribuição por grupo e contexto:\\n\")\nprint(grupo_contexto)\n\n# Percentuais (dentro de cada grupo)\ngrupo_contexto_pct = grupo_contexto.div(grupo_contexto.sum(axis=1), axis=0) * 100\nprint(f\"\\n📊 Percentuais (por grupo):\\n\")\nprint(grupo_contexto_pct.round(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n📊 Distribuição por grupo e contexto:\n\n                Separados  Juntos\ngrupo_mensagem                   \nAUDIO                7583     969\nCALL                    5       8\nCONTACT                 6       3\nDOC                    35       3\nFILE                    0       1\nGIF                    27       1\nIMG                  2928     657\nSTICKER              1761     356\nSYSTEM                585      97\nTEXT                56232   11065\nVID                  9330     272\n\n📊 Percentuais (por grupo):\n\n                Separados  Juntos\ngrupo_mensagem                   \nAUDIO                88.7    11.3\nCALL                 38.5    61.5\nCONTACT              66.7    33.3\nDOC                  92.1     7.9\nFILE                  0.0   100.0\nGIF                  96.4     3.6\nIMG                  81.7    18.3\nSTICKER              83.2    16.8\nSYSTEM               85.8    14.2\nTEXT                 83.6    16.4\nVID                  97.2     2.8\n```\n:::\n:::\n\n\n::: {#cell-fig-grupos-contexto .cell execution_count=23}\n``` {.python .cell-code}\n# Prepara dados\ndados_plot = grupo_contexto.reset_index().melt(\n    id_vars='grupo_mensagem',\n    var_name='contexto',\n    value_name='count'\n)\n\nfig = px.bar(\n    dados_plot,\n    x='grupo_mensagem',\n    y='count',\n    color='contexto',\n    barmode='group',\n    labels={'grupo_mensagem': 'Grupo', 'count': 'Quantidade', 'contexto': 'Contexto'},\n    title='Distribuição de Grupos por Contexto (Junto vs Separado)',\n    color_discrete_map={'Separados': COLORS['separados'], 'Juntos': COLORS['juntos']},\n    text='count'\n)\n\nfig.update_traces(texttemplate='%{text:,}', textposition='outside')\nfig.update_layout(height=400)\nfig.show()\n```\n\n::: {#fig-grupos-contexto .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.5.0.min.js\" integrity=\"sha256-fHbNLP+GlIXN+efbQec78UkemUz3NJp7UmfGxC1tNxs=\" crossorigin=\"anonymous\"></script>                <div id=\"fa48a383-f1df-4b57-bb94-bfe7c6c03c44\" class=\"plotly-graph-div\" style=\"height:400px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"fa48a383-f1df-4b57-bb94-bfe7c6c03c44\")) {                    Plotly.newPlot(                        \"fa48a383-f1df-4b57-bb94-bfe7c6c03c44\",                        [{\"alignmentgroup\":\"True\",\"hovertemplate\":\"Contexto=Separados\\u003cbr\\u003eGrupo=%{x}\\u003cbr\\u003eQuantidade=%{text}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"Separados\",\"marker\":{\"color\":\"#636EFA\",\"pattern\":{\"shape\":\"\"}},\"name\":\"Separados\",\"offsetgroup\":\"Separados\",\"orientation\":\"v\",\"showlegend\":true,\"text\":{\"dtype\":\"f8\",\"bdata\":\"AAAAAACfvUAAAAAAAAAUQAAAAAAAABhAAAAAAACAQUAAAAAAAAAAAAAAAAAAADtAAAAAAADgpkAAAAAAAISbQAAAAAAASIJAAAAAAAB160AAAAAAADnCQA==\"},\"textposition\":\"outside\",\"x\":[\"AUDIO\",\"CALL\",\"CONTACT\",\"DOC\",\"FILE\",\"GIF\",\"IMG\",\"STICKER\",\"SYSTEM\",\"TEXT\",\"VID\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"i4\",\"bdata\":\"nx0AAAUAAAAGAAAAIwAAAAAAAAAbAAAAcAsAAOEGAABJAgAAqNsAAHIkAAA=\"},\"yaxis\":\"y\",\"type\":\"bar\",\"texttemplate\":\"%{text:,}\"},{\"alignmentgroup\":\"True\",\"hovertemplate\":\"Contexto=Juntos\\u003cbr\\u003eGrupo=%{x}\\u003cbr\\u003eQuantidade=%{text}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"Juntos\",\"marker\":{\"color\":\"#00CC96\",\"pattern\":{\"shape\":\"\"}},\"name\":\"Juntos\",\"offsetgroup\":\"Juntos\",\"orientation\":\"v\",\"showlegend\":true,\"text\":{\"dtype\":\"f8\",\"bdata\":\"AAAAAABIjkAAAAAAAAAgQAAAAAAAAAhAAAAAAAAACEAAAAAAAADwPwAAAAAAAPA\\u002fAAAAAACIhEAAAAAAAEB2QAAAAAAAQFhAAAAAAICcxUAAAAAAAABxQA==\"},\"textposition\":\"outside\",\"x\":[\"AUDIO\",\"CALL\",\"CONTACT\",\"DOC\",\"FILE\",\"GIF\",\"IMG\",\"STICKER\",\"SYSTEM\",\"TEXT\",\"VID\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"i2\",\"bdata\":\"yQMIAAMAAwABAAEAkQJkAWEAOSsQAQ==\"},\"yaxis\":\"y\",\"type\":\"bar\",\"texttemplate\":\"%{text:,}\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Grupo\"}},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Quantidade\"}},\"legend\":{\"title\":{\"text\":\"Contexto\"},\"tracegroupgap\":0},\"title\":{\"text\":\"Distribui\\u00e7\\u00e3o de Grupos por Contexto (Junto vs Separado)\"},\"barmode\":\"group\",\"height\":400},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('fa48a383-f1df-4b57-bb94-bfe7c6c03c44');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n\nDistribuição de grupos por contexto\n:::\n:::\n\n\n---\n\n## Síntese - Tipos de Mensagem\n\n::: {.callout-note}\n#### 💡 Insight - Tipos de Mensagem\n\n**Composição geral (dataset completo):**\n- **TEXT domina:** 73.2% (67.297 msgs) - comunicação objetiva e rápida\n- **VID:** 10.4% (9.602 msgs) - mídia rica\n- **AUDIO:** 9.3% (8.552 msgs) - expressividade e afeto\n- **IMG:** 3.9% (3.585 msgs) - compartilhamento visual\n- **Outros:** 3.2% (stickers, calls, docs, etc)\n\n**Concentração:** Top 3 tipos (TEXT, VID, AUDIO) = 92.9% das mensagens\n\n---\n\n**Por remetente - Assimetrias identificadas:**\n\n| Grupo | P1 | P2 | Diferença | Interpretação |\n|-------|----|----|-----------|---------------|\n| **TEXT** | 49.4% | 50.6% | +1.2pp | Equilibrado |\n| **AUDIO** | **62.4%** | 37.6% | **+24.8pp** 🔥 | P1 prefere áudio! |\n| **VID** | 51.5% | 48.5% | +3.0pp | Equilibrado |\n| **IMG** | 54.8% | 45.2% | +9.6pp | P1 levemente mais visual |\n\n**Descoberta:** P1 usa **62.4%** de todos os áudios (quase 2/3!) - preferência clara por voz vs P2 que prefere texto.\n\n---\n\n**Por contexto - MUDANÇA DRAMÁTICA:**\n\n| Grupo | Separados | Juntos | Interpretação |\n|-------|-----------|--------|---------------|\n| **VID** | **97.2%** | **2.8%** | **VID some quando juntos!** 🔥 |\n| **AUDIO** | 88.7% | 11.3% | Cai drasticamente |\n| **TEXT** | 83.6% | 16.4% | Mais equilibrado |\n| **IMG** | 81.7% | 18.3% | Cai moderadamente |\n\n**Descobertas CRÍTICAS:**\n\n1. **VID é mídia de SEPARAÇÃO pura:**\n   - 97.2% quando separados (compensa distância visual)\n   - Apenas 2.8% quando juntos (presença física > vídeo)\n   - **Redução de 34.6x no uso!**\n\n2. **AUDIO também é ferramenta de distância:**\n   - 88.7% quando separados (ouvir a voz conecta)\n   - 11.3% quando juntos (convívio substitui)\n\n3. **TEXT é mais estável:**\n   - Proporção mais equilibrada (83.6% vs 16.4%)\n   - Funciona em ambos contextos (coordenação universal)\n\n**Conclusão:** Presença física não só reduz VOLUME (-68%), mas também muda **TIPO** de mídia. Relacionamento tem dois \"idiomas\": mídia rica quando separados (VID/AUDIO para conexão) vs texto quando juntos (coordenação rápida).\n:::\n\n------------------------------------------------------------------------\n\n# Análise de Sentimento\n\n## A Subjetividade do Sentimento\n\nTestamos dois modelos de IA para classificar o sentimento das mensagens. O resultado? **Eles concordam em apenas 37% dos casos!**\n\nIsso revela algo importante: **não existe interpretação \"objetiva\" de sentimento.**\n\n-   Um modelo vê neutralidade onde o outro vê positividade\n-   Mensagens ambíguas podem ser interpretadas de formas opostas\n-   Assim como pessoas diferentes interpretam conversas diferentemente\n\n**Qual usar?** Depende da pergunta:\n- \"Como estavam as conversas objetivamente?\" → RoBERTa\n- \"Qual o tom emocional predominante?\" → DistilBERT\n\n## Análise Comparativa: DistilBERT vs RoBERTa\n\nDistribuições completamente diferentes:\n\n| Métrica | RoBERTa | DistilBERT | Diferença |\n|---------|---------|------------|-----------|\n| Positive | 28.3% | 62.1% | +33.8% 🟢⬆️ |\n| Neutral | 48.9% | 5.0% | -43.9% ⚪⬇️ |\n| Negative | 22.8% | 32.9% | +10.1% 🔴⬆️ |\n\n**Concordância: APENAS 37%!** Isso significa que em 63% das mensagens, os modelos discordam!\n\n## O Que Está Acontecendo?\n\n### 1. Viés dos Modelos Muito Diferente\n\n**RoBERTa: Conservador e cauteloso**\n\n- Quando não tem certeza → classifica como neutral\n- 49% das mensagens são neutras\n- Confiança média: 0.672 (alta)\n\n**DistilBERT: Polarizador e ousado**\n\n- Quando não tem certeza → escolhe positivo ou negativo\n- Apenas 5% neutras (quase ignora essa classe!)\n- Confiança média: 0.544 (mais baixa)\n\n### 2. Por Que Isso Acontece?\n\n**Treinamento Diferente:**\n\n- RoBERTa: Tweets (ambiente neutro/informativo comum)\n- DistilBERT: Destilado de BERT (pode ter viés do dataset)\n\n**Filosofia:**\n\n- RoBERTa: \"Se não tenho certeza, é neutro\"\n- DistilBERT: \"Se não tenho certeza, escolho um lado\"\n\n### 3. Qual Está \"Certo\"?\n\nNenhum e ambos! Depende do que você quer:\n\n**Se quer análise conservadora:** ✅ Use RoBERTa\n\n- Mais confiança\n- Não \"inventa\" sentimento onde não tem\n- Bom para análise objetiva\n\n**Se quer análise polarizada:** ✅ Use DistilBERT\n\n- Captura nuances sutis\n- Força uma interpretação\n- Bom para identificar tendências\n\n### Exemplos Reveladores\n\nExemplos do DistilBERT classificados como positivo:\n\n- \"https://www.localiza.com/brasil...\" → positive (0.540)\n- \"Arrasou\" → positive (0.551)\n- \"confortável\" → positive (0.915) ← Alta confiança!\n\nRoBERTa provavelmente classificou URL como neutral (mais sensato).\n\nE como neutral no DistilBERT:\n\n- \"Total tá, não por pessoa\" → neutral (0.507)\n- \"Ai não rola kkkkkk\" → neutral (0.569)\n\nRoBERTa pode ter visto \"kkkkkk\" como positivo!\n\n## Código para Análise de Discordância\n\n::: {#sentiment-discordance .cell execution_count=24}\n``` {.python .cell-code}\n# Mensagens onde modelos discordam\nif 'sentimento_roberta_label' in df.columns and 'sentimento_distilbert_label' in df.columns:\n    df_discordantes = df[\n        (df['sentimento_roberta_label'] != df['sentimento_distilbert_label']) &\n        df['sentimento_roberta_label'].notna() &\n        df['sentimento_distilbert_label'].notna()\n    ]\n\n    print(f\"Mensagens discordantes: {len(df_discordantes):,} ({len(df_discordantes)/len(df)*100:.1f}%)\")\n\n    # Padrões de discordância\n    from collections import Counter\n    padroes = Counter(\n        zip(df_discordantes['sentimento_roberta_label'], df_discordantes['sentimento_distilbert_label'])\n    )\n\n    print(\"\\nPadrões de discordância:\")\n    for (roberta, distilbert), count in padroes.most_common():\n        print(f\"  RoBERTa: {roberta:8s} → DistilBERT: {distilbert:8s} : {count:,} casos\")\nelse:\n    print(\"⚠️ Colunas de sentimento não encontradas no dataset.\")\n    print(\"   Execute o pipeline de sentimento antes desta análise.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n⚠️ Colunas de sentimento não encontradas no dataset.\n   Execute o pipeline de sentimento antes desta análise.\n```\n:::\n:::\n\n\n## Recomendação: RoBERTa 🏆\n\n**Por quê:**\n\n- ✅ Maior confiança (0.67 vs 0.54)\n- ✅ Mais equilibrado (não ignora neutral)\n- ✅ Treinado em texto curto (tweets = WhatsApp)\n- ✅ Resultados mais \"crível\" (62% positivo parece alto demais)\n\n**Mas mantenha DistilBERT para:**\n\n- Comparações e discussões\n- Mostrar a subjetividade\n- Identificar mensagens polarizadas\n\n✅ No EDA, use `sentimento_roberta_label` como principal.\n✅ Crie uma seção de comparação mostrando a discordância.\n\n------------------------------------------------------------------------\n\n# Síntese e Conclusões\n\n## Resumo - Contexto Externo (Notebook 02)\n\n::: {.callout-note}\n### 📌 Descobertas do Notebook Anterior\n\n**Contexto externo integrado:**\n- 10 encontros presenciais (122 dias juntos = 33.2% do tempo)\n- 2 períodos distintos: Amizade (2.8%) vs Relacionamento (97.2%)\n- Zero dias sem falar quando separados (100% gaps = encontros)\n\n**Impacto do contexto validado:**\n- Volume: -68.3% quando juntos (372 → 118 msgs/dia)\n- Timing: Noturno (19h) → Diurno (12h)\n- Semanal: Uniforme → Segunda explode (26.8%), fim de semana some (3%)\n\n**Conclusão:** `em_encontro` é switch de protocolo - muda volume, timing e comportamento.\n:::\n\n---\n\n## Síntese Final - Overview do Dataset\n\n::: {.callout-important}\n### 🎯 Conclusão Geral - Características do Dataset\n\n**Estrutura do dataset:**\n- 91.924 mensagens em 367 dias\n- Participação equilibrada: P1 (51.1%) vs P2 (48.9%)\n- Dominância do relacionamento: 97.2% pós 16/dez\n\n---\n\n**VOLUME - Reativo ao contexto:**\n- Separados: 372 msgs/dia (ALTO, canal principal)\n- Juntos: 118 msgs/dia (BAIXO, -68%, coordenação)\n- Padrão temporal: picos = separação, vales = encontros\n\n---\n\n**TIPOS - Dois \"idiomas\" de comunicação:**\n\n**Quando SEPARADOS (mídia rica para conexão):**\n- VID: 97.2% de uso (compensa distância visual)\n- AUDIO: 88.7% de uso (ouvir a voz conecta)\n- Preferência: P1 usa 62.4% dos áudios (voz > texto)\n\n**Quando JUNTOS (texto para coordenação):**\n- TEXT: Mais estável (16.4% das mensagens)\n- VID: Redução de 34.6x (2.8% apenas!)\n- AUDIO: Cai para 11.3%\n\n---\n\n**SENTIMENTO - Subjetividade revelada:**\n- RoBERTa vs DistilBERT concordam em apenas 37%\n- RoBERTa recomendado (conservador, mais confiável)\n- Sentimento é complementar, não substituto de análise contextual\n\n---\n\n**Descoberta central:**\n> Relacionamento à distância opera em **DOIS MODOS DISTINTOS:**\n>\n> 1. **SEPARADOS:** WhatsApp = conexão emocional (volume alto, mídia rica, noturno)\n> 2. **JUNTOS:** WhatsApp = coordenação prática (volume baixo, texto, diurno)\n:::\n\n------------------------------------------------------------------------\n\n# Próximos Passos\n\nCom a exploração inicial completa, seguimos para:\n\n1.  [**Análise Avançada**](06-advanced-analysis.qmd) — Técnicas avançadas\n    -   Clustering usando embeddings\n    -   Análise temporal de sentimento\n    -   Cluster, PCA, MCA\n    -   Modelagem preditiva\n\n",
    "supporting": [
      "05-eda-overview_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n<script>\nwindow.PlotlyConfig = {MathJaxConfig: 'local'};\nif (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n</script>\n<script type=\"module\">import \"https://cdn.plot.ly/plotly-3.5.0.min\"</script>\n\n"
      ]
    }
  }
}