{
  "hash": "0947756cde727dcc296f095e822e9cdc",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Data Cleaning\"\nsubtitle: \"Limpeza e normalização do arquivo bruto\"\nauthor: \"Marlon L.\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    theme: cosmo\nexecute:\n  warning: false\n  echo: false\n---\n\n\n\n📁 Projeto: whatsapp\\-interaction\\-analysis\n\n# Data Cleaning\n\nCom base nas descobertas documentadas no [Data Profiling](00-data-profiling.qmd), esta etapa implementa as transformações de limpeza necessárias para preparar o arquivo bruto para parsing e análise.\n\n## Objetivo\n\nTransformar o arquivo bruto exportado do WhatsApp em um arquivo limpo e otimizado, removendo caracteres invisíveis, linhas vazias, normalizando espaços e anonimizando participantes.\n\n------------------------------------------------------------------------\n\n## Configuração do Pipeline\n\n::: {#1204e55f .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_c5a68\">\n  <thead>\n    <tr>\n      <th id=\"T_c5a68_level0_col0\" class=\"col_heading level0 col0\" >Parâmetro</th>\n      <th id=\"T_c5a68_level0_col1\" class=\"col_heading level0 col1\" >Valor</th>\n      <th id=\"T_c5a68_level0_col2\" class=\"col_heading level0 col2\" >Path</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_c5a68_row0_col0\" class=\"data row0 col0\" >Entrada</td>\n      <td id=\"T_c5a68_row0_col1\" class=\"data row0 col1\" ><code>raw-data.txt</code></td>\n      <td id=\"T_c5a68_row0_col2\" class=\"data row0 col2\" >~/whatsapp-interaction-analysis/data/raw/export_2024-10_2025-10</td>\n    </tr>\n    <tr>\n      <td id=\"T_c5a68_row1_col0\" class=\"data row1 col0\" >Saída</td>\n      <td id=\"T_c5a68_row1_col1\" class=\"data row1 col1\" ><code>export_2024-10_2025-10</code></td>\n      <td id=\"T_c5a68_row1_col2\" class=\"data row1 col2\" >~/whatsapp-interaction-analysis/data/interim/export_2024-10_2025-10</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Execução do Pipeline\n\n\n\n\n\n::: {#a5d3d06a .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_e1f4c\">\n  <thead>\n    <tr>\n      <th id=\"T_e1f4c_level0_col0\" class=\"col_heading level0 col0\" >#</th>\n      <th id=\"T_e1f4c_level0_col1\" class=\"col_heading level0 col1\" >Etapa</th>\n      <th id=\"T_e1f4c_level0_col2\" class=\"col_heading level0 col2\" >Resultado</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_e1f4c_row0_col0\" class=\"data row0 col0\" >1</td>\n      <td id=\"T_e1f4c_row0_col1\" class=\"data row0 col1\" >Remoção U+200E</td>\n      <td id=\"T_e1f4c_row0_col2\" class=\"data row0 col2\" >48,699 caracteres</td>\n    </tr>\n    <tr>\n      <td id=\"T_e1f4c_row1_col0\" class=\"data row1 col0\" >2</td>\n      <td id=\"T_e1f4c_row1_col1\" class=\"data row1 col1\" >Anonimização</td>\n      <td id=\"T_e1f4c_row1_col2\" class=\"data row1 col2\" >91,968 substituições</td>\n    </tr>\n    <tr>\n      <td id=\"T_e1f4c_row2_col0\" class=\"data row2 col0\" >3</td>\n      <td id=\"T_e1f4c_row2_col1\" class=\"data row2 col1\" >Otimização timestamps</td>\n      <td id=\"T_e1f4c_row2_col2\" class=\"data row2 col2\" >91,968 timestamps</td>\n    </tr>\n    <tr>\n      <td id=\"T_e1f4c_row3_col0\" class=\"data row3 col0\" >4</td>\n      <td id=\"T_e1f4c_row3_col1\" class=\"data row3 col1\" >Normalização indentação</td>\n      <td id=\"T_e1f4c_row3_col2\" class=\"data row3 col2\" >3,038 espaços</td>\n    </tr>\n    <tr>\n      <td id=\"T_e1f4c_row4_col0\" class=\"data row4 col0\" >5</td>\n      <td id=\"T_e1f4c_row4_col1\" class=\"data row4 col1\" >Remoção linhas vazias</td>\n      <td id=\"T_e1f4c_row4_col2\" class=\"data row4 col2\" >1,156 linhas</td>\n    </tr>\n    <tr>\n      <td id=\"T_e1f4c_row5_col0\" class=\"data row5 col0\" >6</td>\n      <td id=\"T_e1f4c_row5_col1\" class=\"data row5 col1\" >Normalização espaços</td>\n      <td id=\"T_e1f4c_row5_col2\" class=\"data row5 col2\" >1,003 bytes</td>\n    </tr>\n    <tr>\n      <td id=\"T_e1f4c_row6_col0\" class=\"data row6 col0\" >7</td>\n      <td id=\"T_e1f4c_row6_col1\" class=\"data row6 col1\" >Remoção timestamps vazios</td>\n      <td id=\"T_e1f4c_row6_col2\" class=\"data row6 col2\" >39 linhas</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n✅ Pipeline concluído!\n\n📉 Redução: 5.04 MB → 4.10 MB (18.6%)\n📄 Arquivo: raw-data_cln7.txt\n```\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Pipeline de Transformação\n\n::: {#render-pipeline .cell execution_count=6}\n### Etapa 1: Remoção U+200E\n\nO caractere `U+200E` (Left-to-Right Mark) é um caractere de formatação invisível \nusado para controle de direção de texto. O WhatsApp o insere sistematicamente \ndurante a exportação, mas não carrega informação semântica útil.\n\n**Impacto identificado:** ~48.700 ocorrências, ~243 KB, presente em ~50% das linhas.\n\n**Resultado:**\n\n- Caracteres Removidos: 48,699\n\n**Auditoria:**\n\n| Métrica | Valor |\n|---------|-------|\n| Entrada | 5.04 MB (97,333 linhas) |\n| Saída | 4.81 MB (97,333 linhas) |\n| Redução | 243,430 bytes (4.61%) |\n\n### Etapa 2: Anonimização\n\nSubstitui nomes dos participantes por identificadores genéricos:\n- Marlon → P1\n- Lê 🖤 → P2\n\n**Resultado:**\n\n- Marlon: 46,975\n- Lê 🖤: 44,993\n\n**Auditoria:**\n\n| Métrica | Valor |\n|---------|-------|\n| Entrada | 4.81 MB (97,333 linhas) |\n| Saída | 4.37 MB (97,333 linhas) |\n| Redução | 457,858 bytes (9.08%) |\n\n### Etapa 3: Otimização timestamps\n\nRemove delimitadores redundantes para facilitar o parsing:\n- De: `[28/11/24, 19:30:05] P1: Mensagem`\n- Para: `28/11/24 19:30:05 P1: Mensagem`\n\n**Resultado:**\n\n- Timestamps Otimizados: 91,968\n\n**Auditoria:**\n\n| Métrica | Valor |\n|---------|-------|\n| Entrada | 4.37 MB (97,333 linhas) |\n| Saída | 4.11 MB (97,333 linhas) |\n| Redução | 275,904 bytes (6.02%) |\n\n### Etapa 4: Normalização indentação\n\nRemove espaços/tabs iniciais de linhas de continuação (mensagens multilinha).\nEsses espaços são visuais e não carregam informação semântica.\n\n**Resultado:**\n\n- Espacos Removidos: 3,038\n\n**Auditoria:**\n\n| Métrica | Valor |\n|---------|-------|\n| Entrada | 4.11 MB (97,333 linhas) |\n| Saída | 4.10 MB (97,333 linhas) |\n| Redução | 3,038 bytes (0.07%) |\n\n### Etapa 5: Remoção linhas vazias\n\nLinhas completamente vazias (apenas `\\n`) aparecem entre mensagens e não \ncarregam informação. Serão removidas preservando a formatação interna.\n\n**Resultado:**\n\n- Linhas Removidas: 1,156\n\n**Auditoria:**\n\n| Métrica | Valor |\n|---------|-------|\n| Entrada | 4.10 MB (97,333 linhas) |\n| Saída | 4.10 MB (96,177 linhas) |\n| Redução | 1,156 bytes (0.03%) |\n\n### Etapa 6: Normalização espaços\n\nNormaliza espaços em branco internos:\n- Múltiplos espaços → espaço único\n- Tabs → espaço único  \n- Trailing whitespace → removido\n- **Preserva:** Indentação inicial\n\n**Resultado:**\n\n- Bytes Economizados: 1,003\n\n**Auditoria:**\n\n| Métrica | Valor |\n|---------|-------|\n| Entrada | 4.10 MB (96,177 linhas) |\n| Saída | 4.10 MB (96,177 linhas) |\n| Redução | 1,003 bytes (0.02%) |\n\n### Etapa 7: Remoção timestamps vazios\n\nQuando múltiplas mídias são enviadas simultaneamente, o WhatsApp registra uma \nlinha com timestamp vazio seguida das mídias. A primeira linha é redundante.\n\n**Resultado:**\n\n- Linhas Removidas: 39\n\n**Auditoria:**\n\n| Métrica | Valor |\n|---------|-------|\n| Entrada | 4.10 MB (96,177 linhas) |\n| Saída | 4.10 MB (96,138 linhas) |\n| Redução | 858 bytes (0.02%) |\n\n:::\n\n\n------------------------------------------------------------------------\n\n## Auditoria Final do Pipeline\n\n\n\n::: panel-tabset\n## Comparação de Estágios\n\n::: {#cell-show-audit-table .cell execution_count=8}\n\n::: {#show-audit-table .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_eabfd\">\n  <thead>\n    <tr>\n      <th id=\"T_eabfd_level0_col0\" class=\"col_heading level0 col0\" >Estágio</th>\n      <th id=\"T_eabfd_level0_col1\" class=\"col_heading level0 col1\" >Linhas</th>\n      <th id=\"T_eabfd_level0_col2\" class=\"col_heading level0 col2\" >Chars</th>\n      <th id=\"T_eabfd_level0_col3\" class=\"col_heading level0 col3\" >Tamanho</th>\n      <th id=\"T_eabfd_level0_col4\" class=\"col_heading level0 col4\" >Δ Linhas</th>\n      <th id=\"T_eabfd_level0_col5\" class=\"col_heading level0 col5\" >Δ Chars</th>\n      <th id=\"T_eabfd_level0_col6\" class=\"col_heading level0 col6\" >Δ %</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_eabfd_row0_col0\" class=\"data row0 col0\" >📄 Original (raw-data.txt)</td>\n      <td id=\"T_eabfd_row0_col1\" class=\"data row0 col1\" >97,333</td>\n      <td id=\"T_eabfd_row0_col2\" class=\"data row0 col2\" >4,846,244</td>\n      <td id=\"T_eabfd_row0_col3\" class=\"data row0 col3\" >5.04 MB</td>\n      <td id=\"T_eabfd_row0_col4\" class=\"data row0 col4\" >-</td>\n      <td id=\"T_eabfd_row0_col5\" class=\"data row0 col5\" >-</td>\n      <td id=\"T_eabfd_row0_col6\" class=\"data row0 col6\" >-</td>\n    </tr>\n    <tr>\n      <td id=\"T_eabfd_row1_col0\" class=\"data row1 col0\" >└─ Remoção U+200E</td>\n      <td id=\"T_eabfd_row1_col1\" class=\"data row1 col1\" >97,333</td>\n      <td id=\"T_eabfd_row1_col2\" class=\"data row1 col2\" >4,797,545</td>\n      <td id=\"T_eabfd_row1_col3\" class=\"data row1 col3\" >4.81 MB</td>\n      <td id=\"T_eabfd_row1_col4\" class=\"data row1 col4\" >-</td>\n      <td id=\"T_eabfd_row1_col5\" class=\"data row1 col5\" >-48,699</td>\n      <td id=\"T_eabfd_row1_col6\" class=\"data row1 col6\" >-4.61%</td>\n    </tr>\n    <tr>\n      <td id=\"T_eabfd_row2_col0\" class=\"data row2 col0\" >└─ Anonimização</td>\n      <td id=\"T_eabfd_row2_col1\" class=\"data row2 col1\" >97,333</td>\n      <td id=\"T_eabfd_row2_col2\" class=\"data row2 col2\" >4,519,659</td>\n      <td id=\"T_eabfd_row2_col3\" class=\"data row2 col3\" >4.37 MB</td>\n      <td id=\"T_eabfd_row2_col4\" class=\"data row2 col4\" >-</td>\n      <td id=\"T_eabfd_row2_col5\" class=\"data row2 col5\" >-277,886</td>\n      <td id=\"T_eabfd_row2_col6\" class=\"data row2 col6\" >-9.08%</td>\n    </tr>\n    <tr>\n      <td id=\"T_eabfd_row3_col0\" class=\"data row3 col0\" >└─ Otimização timestamps</td>\n      <td id=\"T_eabfd_row3_col1\" class=\"data row3 col1\" >97,333</td>\n      <td id=\"T_eabfd_row3_col2\" class=\"data row3 col2\" >4,243,755</td>\n      <td id=\"T_eabfd_row3_col3\" class=\"data row3 col3\" >4.11 MB</td>\n      <td id=\"T_eabfd_row3_col4\" class=\"data row3 col4\" >-</td>\n      <td id=\"T_eabfd_row3_col5\" class=\"data row3 col5\" >-275,904</td>\n      <td id=\"T_eabfd_row3_col6\" class=\"data row3 col6\" >-6.02%</td>\n    </tr>\n    <tr>\n      <td id=\"T_eabfd_row4_col0\" class=\"data row4 col0\" >└─ Normalização indentação</td>\n      <td id=\"T_eabfd_row4_col1\" class=\"data row4 col1\" >97,333</td>\n      <td id=\"T_eabfd_row4_col2\" class=\"data row4 col2\" >4,240,717</td>\n      <td id=\"T_eabfd_row4_col3\" class=\"data row4 col3\" >4.10 MB</td>\n      <td id=\"T_eabfd_row4_col4\" class=\"data row4 col4\" >-</td>\n      <td id=\"T_eabfd_row4_col5\" class=\"data row4 col5\" >-3,038</td>\n      <td id=\"T_eabfd_row4_col6\" class=\"data row4 col6\" >-0.07%</td>\n    </tr>\n    <tr>\n      <td id=\"T_eabfd_row5_col0\" class=\"data row5 col0\" >└─ Remoção linhas vazias</td>\n      <td id=\"T_eabfd_row5_col1\" class=\"data row5 col1\" >96,177</td>\n      <td id=\"T_eabfd_row5_col2\" class=\"data row5 col2\" >4,239,561</td>\n      <td id=\"T_eabfd_row5_col3\" class=\"data row5 col3\" >4.10 MB</td>\n      <td id=\"T_eabfd_row5_col4\" class=\"data row5 col4\" >-1,156</td>\n      <td id=\"T_eabfd_row5_col5\" class=\"data row5 col5\" >-1,156</td>\n      <td id=\"T_eabfd_row5_col6\" class=\"data row5 col6\" >-0.03%</td>\n    </tr>\n    <tr>\n      <td id=\"T_eabfd_row6_col0\" class=\"data row6 col0\" >└─ Normalização espaços</td>\n      <td id=\"T_eabfd_row6_col1\" class=\"data row6 col1\" >96,177</td>\n      <td id=\"T_eabfd_row6_col2\" class=\"data row6 col2\" >4,238,560</td>\n      <td id=\"T_eabfd_row6_col3\" class=\"data row6 col3\" >4.10 MB</td>\n      <td id=\"T_eabfd_row6_col4\" class=\"data row6 col4\" >-</td>\n      <td id=\"T_eabfd_row6_col5\" class=\"data row6 col5\" >-1,001</td>\n      <td id=\"T_eabfd_row6_col6\" class=\"data row6 col6\" >-0.02%</td>\n    </tr>\n    <tr>\n      <td id=\"T_eabfd_row7_col0\" class=\"data row7 col0\" >└─ Remoção timestamps vazios</td>\n      <td id=\"T_eabfd_row7_col1\" class=\"data row7 col1\" >96,138</td>\n      <td id=\"T_eabfd_row7_col2\" class=\"data row7 col2\" >4,237,702</td>\n      <td id=\"T_eabfd_row7_col3\" class=\"data row7 col3\" >4.10 MB</td>\n      <td id=\"T_eabfd_row7_col4\" class=\"data row7 col4\" >-39</td>\n      <td id=\"T_eabfd_row7_col5\" class=\"data row7 col5\" >-858</td>\n      <td id=\"T_eabfd_row7_col6\" class=\"data row7 col6\" >-0.02%</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n## Resumo por Etapa\n\n::: {#cell-show-summary .cell execution_count=9}\n\n::: {#show-summary .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_4464a\">\n  <thead>\n    <tr>\n      <th id=\"T_4464a_level0_col0\" class=\"col_heading level0 col0\" >Etapa</th>\n      <th id=\"T_4464a_level0_col1\" class=\"col_heading level0 col1\" >Tamanho Após</th>\n      <th id=\"T_4464a_level0_col2\" class=\"col_heading level0 col2\" >Bytes Removidos</th>\n      <th id=\"T_4464a_level0_col3\" class=\"col_heading level0 col3\" >Linhas Removidas</th>\n      <th id=\"T_4464a_level0_col4\" class=\"col_heading level0 col4\" >Chars Removidos</th>\n      <th id=\"T_4464a_level0_col5\" class=\"col_heading level0 col5\" >Redução %</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_4464a_row0_col0\" class=\"data row0 col0\" >1️⃣ Remoção U+200E</td>\n      <td id=\"T_4464a_row0_col1\" class=\"data row0 col1\" >4.81 MB</td>\n      <td id=\"T_4464a_row0_col2\" class=\"data row0 col2\" >243,430</td>\n      <td id=\"T_4464a_row0_col3\" class=\"data row0 col3\" >-</td>\n      <td id=\"T_4464a_row0_col4\" class=\"data row0 col4\" >48,699</td>\n      <td id=\"T_4464a_row0_col5\" class=\"data row0 col5\" >4.61%</td>\n    </tr>\n    <tr>\n      <td id=\"T_4464a_row1_col0\" class=\"data row1 col0\" >2️⃣ Anonimização</td>\n      <td id=\"T_4464a_row1_col1\" class=\"data row1 col1\" >4.37 MB</td>\n      <td id=\"T_4464a_row1_col2\" class=\"data row1 col2\" >457,858</td>\n      <td id=\"T_4464a_row1_col3\" class=\"data row1 col3\" >-</td>\n      <td id=\"T_4464a_row1_col4\" class=\"data row1 col4\" >277,886</td>\n      <td id=\"T_4464a_row1_col5\" class=\"data row1 col5\" >9.08%</td>\n    </tr>\n    <tr>\n      <td id=\"T_4464a_row2_col0\" class=\"data row2 col0\" >3️⃣ Otimização timestamps</td>\n      <td id=\"T_4464a_row2_col1\" class=\"data row2 col1\" >4.11 MB</td>\n      <td id=\"T_4464a_row2_col2\" class=\"data row2 col2\" >275,904</td>\n      <td id=\"T_4464a_row2_col3\" class=\"data row2 col3\" >-</td>\n      <td id=\"T_4464a_row2_col4\" class=\"data row2 col4\" >275,904</td>\n      <td id=\"T_4464a_row2_col5\" class=\"data row2 col5\" >6.02%</td>\n    </tr>\n    <tr>\n      <td id=\"T_4464a_row3_col0\" class=\"data row3 col0\" >4️⃣ Normalização indentação</td>\n      <td id=\"T_4464a_row3_col1\" class=\"data row3 col1\" >4.10 MB</td>\n      <td id=\"T_4464a_row3_col2\" class=\"data row3 col2\" >3,038</td>\n      <td id=\"T_4464a_row3_col3\" class=\"data row3 col3\" >-</td>\n      <td id=\"T_4464a_row3_col4\" class=\"data row3 col4\" >3,038</td>\n      <td id=\"T_4464a_row3_col5\" class=\"data row3 col5\" >0.07%</td>\n    </tr>\n    <tr>\n      <td id=\"T_4464a_row4_col0\" class=\"data row4 col0\" >5️⃣ Remoção linhas vazias</td>\n      <td id=\"T_4464a_row4_col1\" class=\"data row4 col1\" >4.10 MB</td>\n      <td id=\"T_4464a_row4_col2\" class=\"data row4 col2\" >1,156</td>\n      <td id=\"T_4464a_row4_col3\" class=\"data row4 col3\" >1,156</td>\n      <td id=\"T_4464a_row4_col4\" class=\"data row4 col4\" >1,156</td>\n      <td id=\"T_4464a_row4_col5\" class=\"data row4 col5\" >0.03%</td>\n    </tr>\n    <tr>\n      <td id=\"T_4464a_row5_col0\" class=\"data row5 col0\" >6️⃣ Normalização espaços</td>\n      <td id=\"T_4464a_row5_col1\" class=\"data row5 col1\" >4.10 MB</td>\n      <td id=\"T_4464a_row5_col2\" class=\"data row5 col2\" >1,003</td>\n      <td id=\"T_4464a_row5_col3\" class=\"data row5 col3\" >-</td>\n      <td id=\"T_4464a_row5_col4\" class=\"data row5 col4\" >1,001</td>\n      <td id=\"T_4464a_row5_col5\" class=\"data row5 col5\" >0.02%</td>\n    </tr>\n    <tr>\n      <td id=\"T_4464a_row6_col0\" class=\"data row6 col0\" >7️⃣ Remoção timestamps vazios</td>\n      <td id=\"T_4464a_row6_col1\" class=\"data row6 col1\" >4.10 MB</td>\n      <td id=\"T_4464a_row6_col2\" class=\"data row6 col2\" >858</td>\n      <td id=\"T_4464a_row6_col3\" class=\"data row6 col3\" >39</td>\n      <td id=\"T_4464a_row6_col4\" class=\"data row6 col4\" >858</td>\n      <td id=\"T_4464a_row6_col5\" class=\"data row6 col5\" >0.02%</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n:::\n\n------------------------------------------------------------------------\n\n## 🎯 Resultado Final\n\n\n\n::: {#cell-show-final-summary .cell execution_count=11}\n\n::: {#show-final-summary .cell-output .cell-output-display}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_6a9a8\">\n  <thead>\n    <tr>\n      <th id=\"T_6a9a8_level0_col0\" class=\"col_heading level0 col0\" >Métrica</th>\n      <th id=\"T_6a9a8_level0_col1\" class=\"col_heading level0 col1\" >Valor</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_6a9a8_row0_col0\" class=\"data row0 col0\" >Arquivo original</td>\n      <td id=\"T_6a9a8_row0_col1\" class=\"data row0 col1\" >5.04 MB</td>\n    </tr>\n    <tr>\n      <td id=\"T_6a9a8_row1_col0\" class=\"data row1 col0\" >Arquivo final</td>\n      <td id=\"T_6a9a8_row1_col1\" class=\"data row1 col1\" >4.10 MB</td>\n    </tr>\n    <tr>\n      <td id=\"T_6a9a8_row2_col0\" class=\"data row2 col0\" >Redução (bytes)</td>\n      <td id=\"T_6a9a8_row2_col1\" class=\"data row2 col1\" >983,247</td>\n    </tr>\n    <tr>\n      <td id=\"T_6a9a8_row3_col0\" class=\"data row3 col0\" >Redução (%)</td>\n      <td id=\"T_6a9a8_row3_col1\" class=\"data row3 col1\" >18.61%</td>\n    </tr>\n    <tr>\n      <td id=\"T_6a9a8_row4_col0\" class=\"data row4 col0\" >Linhas removidas</td>\n      <td id=\"T_6a9a8_row4_col1\" class=\"data row4 col1\" >1,195</td>\n    </tr>\n    <tr>\n      <td id=\"T_6a9a8_row5_col0\" class=\"data row5 col0\" >Caracteres removidos</td>\n      <td id=\"T_6a9a8_row5_col1\" class=\"data row5 col1\" >608,542</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n✅ **Arquivo de saída:** raw\\-data\\_cln7\\.txt\n\nO arquivo limpo está pronto para a próxima etapa: **parsing e estruturação em DataFrame**.\n\n------------------------------------------------------------------------\n\n## 💡 Impacto da Limpeza\n\n::: {#b68eb60f .cell execution_count=12}\n\n::: {.cell-output .cell-output-stdout}\n```\n**Redução no Arquivo Bruto:**\n\n- Original: 5.04 MB\n- Após limpeza: 4.10 MB\n- Redução: 18.61%\n\n**Projeção para Dataset Enriquecido (~8x):**\n\n- Sem otimização: ~40.3 MB\n- Com otimização: ~32.8 MB\n- Economia projetada: ~7.5 MB\n```\n:::\n:::\n\n\n**Benefícios:**\n\n-   Menos dados para armazenar\n-   Processamento mais rápido\n-   Transferências mais eficientes\n\n------------------------------------------------------------------------\n\n## Arquivo de Saída\n\nO arquivo final agora possui:\n\n-   ✅ Formato otimizado: `DD/MM/YY HH:MM:SS Remetente: Conteúdo`\n-   ✅ Participantes anonimizados (P1, P2)\n-   ✅ Sem caracteres invisíveis\n-   ✅ Sem linhas/timestamps vazios\n-   ✅ Espaços e indentação normalizados\n\n::: {.callout-note appearance=\"simple\" collapse=\"true\"}\n### 📋 Regex para parsing do arquivo limpo\n\n``` python\n# Padrão para identificar início de mensagem\nmessage_pattern = r'^(\\d{2}/\\d{2}/\\d{2}) (\\d{2}:\\d{2}:\\d{2}) (.+?): (.*)$'\n\n# Grupos de captura:\n# 1: Data (DD/MM/YY)\n# 2: Hora (HH:MM:SS)\n# 3: Remetente (P1 ou P2)\n# 4: Conteúdo da mensagem\n```\n:::\n\n------------------------------------------------------------------------\n\n# Próximos Passos\n\nCom o arquivo limpo, seguimos para:\n\n1.  [**Data Wrangling**](02-data-wrangling.qmd) — Parsing, agregação de multilinha, vinculação de mídia\n\n",
    "supporting": [
      "01-data-cleaning_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}